---
title: "Courses I've Taught"
---

## Courses as primary instructor

**Geog4/6366: Maps and the City (Instructor \@ U of Georgia, 2026-present) \| [Syllabus](https://docs.google.com/document/d/1GN-McuqKseNJ8OCBLa-3qRtHZpo6AyBPKMrc3T3nWok/edit?usp=drive_link)

This mixed level course borrowed from the 2023 seminar listed below and follows a similar organization. Students spend time considering the history of urban mapping, from Charles Booth through contemporary zoning practices and spatial analysis. They also spend time in UGA's special collections library to think about how maps fit within a broader historical and political context.

------------------------------------------------------------------------

**GEOG8730: Maps and the City** (graduate seminar, U of Georgia, 2023) \| [Syllabus](https://docs.google.com/document/d/1rMT_CL1URm6PenLXetXthZdaSufOboQ7zPHOCIxkKRM/edit?usp=sharing)

This graduate seminar introduced students to critical cartography and its applicability to urban mapping and spatial analysis. We read a mix of historical works (DuBois' *Philadelphia Negro,* Material on redlining), spent time at UGA Special Collections looking at urban maps, and considered contemporary cartographic approaches like indigenous mapping and counter-cartographies.

------------------------------------------------------------------------

**GEOG2011: Introduction to GIScience** (Instructor \@ U of Georgia, 2016-23) \| [Syllabus from Spring 2025](https://docs.google.com/document/d/18pUXPwBdEPTG7HZpQyhkm1jD9IvdiwIYdQL8_TJ8h3Q/edit?usp=sharing) Introduction to GIScience provides both the theoretical and technical fundamentals for a range of undergraduate students. The course covers basic principles of cartography and spatial analysis, as well as a range of frameworks used to understand the use of maps in society, including exposure to both positivist viewpoints and post-structuralist critiques. Students use a range of tools, including the open source desktop GIS software QGIS, the web mapping platform Carto, and the 3D imaging tool Autodesk ReMake. Students also hear about a range of applications for GIScience, including coastal management, UGA's Cubesat program, and the use of GIS in health and urban planning.

------------------------------------------------------------------------

**GEOG4385: Community GIS (Instructor \@ U of Georgia, 2016-present)** \| [Syllabus from Spring 2026](https://docs.google.com/document/d/1TnpF4aetBg0_Z73-zfJZyZWPwBTFxWB5Db7-5iVw_3k/edit?usp=drive_link) This course draws from existing work on participatory research and critical GIS to consider the role of maps in shaping politics and policy related to urban communities. Students also use a range of open source GIS software and online mapping tools. Students have done work developing local data sources for community stakeholders, mapping housing eviction and neighborhood gentrification, analyzing access to green space, and multiple other partnerships.

------------------------------------------------------------------------

**GEOG4300/6300: Data Science in Geography (Instructor \@ U of Georgia, 2013-23)** \| [Github repo with labs/materials](https://github.com/jshannon75/geog4300) All geography graduate students are required to take this course, which covers basic elements of descriptive and inferential statistics, ranging from measures of central tendency through multivariate regression. This course also introduces students to the fundamentals of spatial statistics, such as measures of spatial clustering/autocorrelation and spatial regression. Students completed seven labs and a final take-home project.

------------------------------------------------------------------------

**GEOG1101: Introduction to Human Geography (Instructor \@ U of Georgia, 2013-15)** This introductory 300 student lecture course covers the main themes of human geography, such as population geography, nature-society, cultural geography, geographies of food, and urban geography. Through a mix of lecture, in-class discussion and activities, and films, students gained more knowledge about these sub-fields. They completed one short "fieldwork" assignment, regular reading quizzes, and three exams.

## Courses as teaching assistant

**GIS 5555: Basic Spatial Analysis** (TA for Prof. Steven Manson, U of Minnesota, Fall 2010)

I helped prep and grade labs for this graduate level course on spatial analysis methods. Labs primarily used GeoDa software and covered exploratory data analysis, spatial weighing schemes, measures of local and global autocorrelation, and univariate and multivariate spatial regression.

------------------------------------------------------------------------

**GEOG1502: Mapping Our World** (TA for Prof. Steven Manson, U of Minnesota, Fall 2010)

I helped design this freshman level course on the technical and social aspects of new mapping technologies. I wrote and administered course labs, which primarily involved online mapping tools and covered basic pattern analysis, data evaluation and preparation, geocoding points, creating raw rates, and working with tracking data. I also graded labs and final projects, designed and ran several in-class activities, delivered a guest lecture, and provided input on course exams.

------------------------------------------------------------------------

**GEOG3561: Principles of GIS** (TA for lab section, U of Minnesota, Summer 2010)

I prepared, ran, and graded students on labs for an introductory GIS course using both ArcGIS and Idrisi software. Topics covered included projections, georeferencing images, geocoding, multivariate maps, fuzzy suitability analysis, distance buffers, and raster image processing. I also created a laboratory practical exam.
