---
title: "Links for Grad Students"
---

## Academic writing guides

- [Academic writing](https://subjectguides.york.ac.uk/academic-writing/home) (York University)
- [Academic style](https://students.unimelb.edu.au/academic-skills/resources/reading,-writing-and-referencing/writing-effectively/academic-style) (University of Melbourne)
- [Tone and Style in Academic Writing](https://opentextbc.ca/buildingblocks/chapter/tone-and-style/) (BC Campus)
- [Style in Academic Writing](https://wac.colostate.edu/docs/books/centrality/chapter10.pdf) (Nora Bacon, University of Nebraska at Omaha)
- [The Style of Graduate Writing](https://grad.uc.edu/content/dam/refresh/grad-62/docs/events/conference/The-Style-of-Graduate-Writing.pdf) (slides from Academic Writing Center, University of Cincinnati)
- [Academic Writing Style](https://www.port.ac.uk/student-life/help-and-advice/study-skills/written-assignments/academic-writing-style) (University of Portsmouth)
- Book: [Air and Light and Time and Space](https://www.hup.harvard.edu/books/9780674737709) (Helen Sword)
- Book: [Thriving as a Graduate Writer](https://press.umich.edu/Books/T/Thriving-as-a-Graduate-Writer2) (Rachael Cayley)

## CVs, resumes, and the job hunt

- [Creating and Maintaining Your CV](https://www.chronicle.com/blogs/profhacker/creatingmaintaining-your-cv/26887) (Chronicle of Higher Education)
- [The CV Doctor Returns](https://www.chronicle.com/article/The-CV-Doctor-Returns-2010/124492) (Chronicle, 2010)
- [Me and My Shadow CV](https://www.chronicle.com/article/MeMy-Shadow-CV/233801) (Chronicle, 2015)
- [CV vs. Resume](https://theundercoverrecruiter.com/cv-vs-resume-difference-and-when-use-which/) (Undercover Recruiter)
- [CV vs. Resume](https://writingcenter.unc.edu/tips-and-tools/curricula-vitae-cvs-versus-resumes/) (UNC Writing Center)
- [Do Not Apply for an Academic Job](https://docs.google.com/document/d/1-r6OWiPQ_0HkA-ExgIDknqciMy5qZUeO_jQ5rK52LBM/edit) (Steve Manson, UMN)
