---
title: "Teaching Experience and Philosophy"
---

My approach to teaching is informed by nearly two decades of experience in college classrooms, including ten years as a first-year writing instructor before returning to school for a Ph.D. and subsequently being hired at the University of Georgia. At Georgia, I have taught courses ranging from the introductory human geography course, with an enrollment of 300, to small graduate seminars in geospatial analysis and urban theory. Currently, I regularly teach an introductory course on geographic information science (GIScience) which I designed from scratch and now enrolls nearly 40 students per semester. I also teach two split level courses open to both graduate and undergraduate students: one on quantitative methods and another on using GIScience to do community engaged research.. I have also individually mentored fourteen undergraduates as research assistants, mostly through the UGA’s Center for Undergraduate Research Opportunities (CURO). Through my Community GIS course and these CURO fellowships, students have engaged with multiple community partners.

I have pursued professional development opportunities in my teaching and been recognized for excellence in instruction.  During my time at University of Georgia, I have participated in the Teaching Academy Fellows Program, the Office of Service-Learning Fellowship program, and the Lilly Fellowship program. In addition, I have received both the Service-Learning Teaching Excellence Award and the Sandy Beaver Excellence in Teaching Award, and I have also been recognized by UGA’s Career Center for my contributions to undergraduate student learning. In 2019, I received the Richard B. Russell Award for Excellence in Undergraduate Instruction, the top honor for early career faculty members. Lastly, I took the lead in applying for and managing a grant from the President’s office for Active-Learning classrooms, and these funds have allowed for a complete redesign of Geography’s two primary computer labs to better support active learning pedagogy.

In the sections below, I summarize the main principles that shape my pedagogical approach.

## Design authentic, relevant course assignments and research opportunities
I have a deep commitment to authentic learning, one that comes from a broader background in pragmatist models of education. Within pragmatism, knowledge is created through tangible engagements with the world outside the classroom, and through my use of service-learning, I provide students to see how course concepts and approaches are relevant (and often more complicated) than what we talk about in class. This is most evident in the Community GIS class, where students partner with a community-based organization. Rather than completing a pre-designed lab assignment, students must work with both this partner and me to develop a project proposal and collaboratively work together to develop skills and data needed to complete this project. CURO students do similar work, and I work with each student individually and as a cohort throughout the semester to help them develop their projects and research techniques.

While students are often initially unnerved by the lack of a clear project goal, most develop a greater sense of independence and confidence, as well as a more robust understanding of spatial analysis, through this process. I try to make use of authentic assignments in my introductory GIS course as well. There, students collectively generate and analyze information about UGA’s campus—places to study or relax. Doing so generates interest and enthusiasm for students, which in turn deepens their learning.

## Emphasize critical spatial thinking
Spatial thinking is at the core of geographic inquiry, referring to the ways we conceptualize, model, and communicate people’s interactions with their environments. Much of my current teaching is done in our department’s “techniques” courses, ones that focus on quantitative analysis and geographic information systems (GIS). These courses can sometimes take a top-down approach, including step-by-step lab instruction that emphasizes task completion. Although my courses are certainly a place for students to develop new competencies, I am intentional at also engaging them in higher-level thinking. For example, I repeatedly remind students that, in the famous words of Mark Monmonier, “all maps lie,” and that as mapmakers they make constant decisions about what to include on their maps and how to show it. Their lab assignments, as a result, are not simply examples of technical proficiency but a place where students justify the choices they made in constructing the map and the story it tells as a result. In my upper level data science course, students must translate programming code into plain English, describing their workflow in a non-technical manner. This means that they must demonstrate a conceptual grasp of the analytical techniques they are using, not just adapt code from the examples provided in class. These techniques place them at the center of the analysis, emphasizing their role as thoughtful experts with an active role in the process of geospatial analysis.

In addition, I also ask students to consider the social context of geographic inquiry, drawing from past research into critical cartography. Most of my courses use free and open source (FOSS) software—most commonly the R programming language and the QGIS geographic information program. This is practical (students can access to these tools outside of class) but also philosophical. Students read and discuss principles of open science in each class I teach, and we together talk through the potential and problems of using freely available software and  data in scientific research. Similarly, in my introductory GIScience course, we discuss both how the growth of “big data” shifts the ways we conduct geographic research as well as the potential problems it creates, including issues of individual privacy, implicit bias, and data quality. In sum, students in my courses consider how geographic analysis is neither objective nor neutral, but always situated within a particular social context.

## Incorporate active learning and multiple instructional modalities
I incorporate multiple active learning methods into my teaching, providing pathways for student engagement inside and outside the classroom. As one example, many of my courses include a “question of the week” posted on ELC, most often asking students to respond to something from the assigned reading for the week. This low stakes assignment primes the pump for our classtimes by asking students to reflect on the assignment material prior to class discussion. I often integrate student question or comments from these posts into the course, which brings a greater diversity of voices into our conversation. Over the past two semesters, students in my introductory GIS course have been responsible for providing a “five minute recap” prior to each class where they remind us of material covered the previous week but also, more importantly, extend that material by finding relevant examples that go beyond what was covered in class. This higher level work of synthesis and extension is a valuable opportunity for students to engage with course material. To facilitate a more interactive classroom environment, I also took the lead in applying for funds from the president’s Active Learning Classroom grant, which provided nearly $70,000 of improvements to our main GIScience instructional spaces.

My teaching also makes use of multiple modalities of instruction and student response. Most notably, for my project as a Lilly Fellow, I adapted lab assignments in my introductory GIS class to include video as well as written responses from students. While sometimes daunting for students, many expressed a feeling of greater confidence from these videos, with one saying she now “felt like I actually knew” the course material. Another wrote, “The videos were where I really got to see myself realizing what I had done.” These responses show how a change in format provides students with the opportunity both to construct knowledge in a different way but also to observe their own competence. In my data science course, I use playing cards and dice to test the statistical rules of probability we are learning, moving these principles from the abstract to something more concrete. Through these and other in-class activities, students actively engage with course material in a variety of ways.
