---
title: "Here Be Dragons: Recognizing the monsters in our maps"
date: "2018-11-24"
---

Jerry Shannon and CML membersThe margins of medieval European maps are home to some fantastic creatures. These beasts were based on actual accounts by sailors, demonstrating the ways mapmakers relied on first hand accounts of regions that (at least for them) remained unnamed. This article, published by the Smithsonian in 2013, details a few of them: an ichthyocentaur (human, horse, and fish), a sea pig, and a lobster several times larger than the ships it swallowed.

Popular legend holds that the phrase “Here Be Dragons” (or “Hic sunt dracones”) was added to some of these ancient maps in regions deemed particularly dangerous. While probably apocryphal, the phrase remains in the lexicon of our cartographic imaginations, appearing in fantasy novels, multiple films, and even code for the open source Firefox web browser. In many of these instances, the phrase refers to areas where the world becomes unfamiliar, at least to sailors and mapmakers. These paper dragons are are a reminder to practice epistemological humility, recognizing the limits to our ability to know and name the world.
In the current era, big data and informatics promise a panoptic understanding of social and environmental processes, where algorithms and massive datasets can supposedly help us see into every corner of the world. We--members of the Community Mapping Lab--hope to use this blog to uncover stubbornly persistent blind spots in geographic research, dragons that underscore the continued partiality of our knowledge. Contemporary maps may often draw from larger and more complex datasets than these medieval efforts, but this may simply mean that the dragons--unspoken assumptions, biases in the data, extractive research practices--are more artfully hidden. 

Adapting Haraway’s famous phrase, maps are always a view from somewhere. Dalton and Mason-Deese similarly describe an “and, and, and…” approach to mapping, resisting a single authoritative perspective in favor of “continual questioning and the production of alternative knowledges” (p. 460). By working through multiple ways to frame and map the world, such as the the Counter-cartographies Collective’s campus disorientation guide, we highlight the useful, if limited, insight each map provides. We study maps understood both literally (e.g., online and print maps) and metaphorically (e.g., theories of community development), in all cases understanding ways these name and produce the world.
Our group of authors is, at least initially, comprised of students and faculty at the University of Georgia, and our perspectives are inevitably shaped by our daily lives within that institution. This blog is, in part, an effort to make that explicit in our research--to be reflexive, in scholarly terms. Just as early cartographers drew on first hand accounts from sailors, we also develop partnerships with local communities to collaboratively develop alternative ways of mapping the world. We work toward research practices that are inclusive of marginalized groups, reveal the social processes that shape inequality, and promote social and environmental justice. We critically examine the conditions that produce geographic knowledge, placing maps in their social and historical context.

More specifically, the posts on this blog will cluster around four core themes. First, we are interested in community engaged and participatory research practices and their use in both spatial analysis--maps and number crunching--and qualitative research--interviews and participant observation. Second, we critically examine how gender and race matter to the ways research in geographic research is conducted, drawing from work in feminist and black geographies. Third, we explore new forms of data collection and alternative tools for analysis and scholarly conversation. This includes the ways free and open source software can be used within geographic research, the use of volunteered geographic data (VGI) and citizen science as sources of knowledge, and the potential of open science practices--such as shared code, data, and publications--to encourage transparency, public engagement, and reproducible research. Lastly, we highlight the ways that maps and other forms of geographic research are employed to support social activism and promote progressive public policy goals. 
Our posts will vary in format, including reports from our own research, reflections on recent work by others, reports from conferences or workshops, and walkthroughs of new tools or methodological techniques. While our posts will often explicitly mention mapping and GIS, they are seldom just about these tools, and many of us regularly use multiple methods in our research. Through our posts, we hope to spur public conversation about maps and mapping within and outside of the academy.

In sum, Here Be Dragons is a blog focused on emergent ways of mapping the world, ones that are more participatory and inclusive. It’s a blog about the ways geographic research makes our world and its potential role in activism for social and environmental justice. Just like the maps we make, we’re not sure exactly where this blog will go, but we welcome everyone along for the journey.


Author

Jerry Shannon is an Assistant Professor at the University of Georgia in the Departments of Geography and Financial Planning, Housing, & Consumer Economics. He is the director of the Community Mapping Lab.Images from the Carta Marina map. ​
​
