---
title: "Mapping the Dragon: The Worlds We Support & the Worlds We Assimilate"
date: "2019-01-18"
---

David HechtImagine you are a project officer with an international development agency. You are charged with assessing the water resources, quality of access, and management-related challenges of a rural community in Eastern Tibet. You are provided substantial funds by your organization to facilitate a Participatory Rural Appraisal (PRA), an increasingly common method to involve community members in planning, knowledge exchange, and decision-making to address perceived local problems.

You, your development project team, and volunteers from the community work together on a map to document land and water management issues in the region. This map will be a key product for future planning with your agency and will be included in the annual report. One community mapping participant remembers seeing twice as much winter snow accumulating along the mountain ridgeline, just 10 years ago. You put it on the map. Another participant notes the declining abundance of suitable alpine grasslands for their herds of sheep and yak. You put it on the map. Every participant remembers the day they saw a dragon ascending into the sky near a glacier-fed stream. You pause. You don’t put it on the map.

For many Tibetan Drokpa, dragons are real. They’ve seen them. In the positivistic world of western science, a legacy that deeply informs our governmental, non-governmental, and academic institutions, dragons belong to folklore, to myth, and to metaphor. 

As makers of participatory maps, I think we need to map the dragon. Beyond metaphor. Beyond folklore. Dragons have a place in this map because they exist in the shared cultural worlds of the map makers. Drokpa knowledge of dragons does not need a western positivist knowledge filter. It does not need to be validated by scientific objectivity, or confirmed under foreign protocols of “data” or “evidence”.
As makers of participatory maps, I think we need to challenge the space of assumptions associated with other cultural realities. Beyond fiction. Beyond myth. I think we need to interrogate the epistemological foundations of our institutions, and recognize that the edge of our maps of knowing may be the beginning (or center) of somebody else’s. After all, there are no neutral ways to represent “reality” on a map; any “reality” depicted is largely informed by ones’ intellectual and cultural predecessors.

In “Dragons, Drokpa, and a Drukpa Kargyu Master”, Diane Barker, recounts testimonies of those who have seen dragons in Tibet, positioning them alongside stunning depictions by Choegyal Rinpoche. Her article makes me pause. It forces me to re-consider the perspectives and worlds deemed legible in academia, and the constraints of the technologies we employ to help compartmentalize and categorize our complex world. Maps and map making can help us to visualize spatially complex interrelationships between social and natural forces. Relationships between water scarcity and elevation, for example, or grassland abundance and shifts in human land-use over time. Maps produced with Geographical Information Software (GIS) can take us even further and help us to measure these complex interactions by experimenting with scale-dependent variables and spatial layers. GIS, as such, is a powerfully important spatial toolset for map making. It is, however, worth recognizing both its technical and epistemological constraints.

Rundstrom (1995) suggests that “GIS technology, when applied cross-culturally, is essentially a tool for epistemological assimilation, and as such, is the newest link in a long chain of attempts by Western societies to subsume or destroy indigenous cultures”. Perhaps it is, in certain contexts. This point is considered in depth by Dr. Kenneth Bauer (2009) who notes that embracing GIS, and the worlds we create through mapping, means embracing a “mode of thinking”.

Bauer argues that “one’s knowledge of the environment lies not in the ideas in our heads but in the world that our predecessors reveal to us”. If our intellectual predecessors are international development officers, who focus on the material and societal needs of the “developing” world, not only will our maps reflect these priorities, but the edge of our maps will hold epistemologically particular metaphorical dragons. If our predecessors are geospatial scientists, many of whom focus on the scalar dynamics between social and natural systems, the edge of our maps will hold equally specific metaphorical dragons. And if our intellectual predecessors are nomadic Drokpa herders, the center of our maps might include real, non-metaphorical dragons. Then, the edge of our map, the boundaries of our known world, may hold something entirely different. Something as foreign as Participatory Rural Appraisal (PRA). Something as foreign as “development”, “geospatial science” or “conservation”. 

“Dru gu Choegyal Rinpoche's painting of a dragon sucking up water from a stream in Tibet, 2012” Dragons, Drokpa, and a Drukpa Kargyu MasterIn the end, local Drokpa knowledge of dragons may not be commensurate with western knowledge mapping traditions; spatial frameworks that we, as academically-inclined map makers, can know and interpret: 2D, cardinal direction, cartographic maps. Unless we expand our definition of “map”, perhaps Choegyal Rinpoche’s paintings can simply remind us that the edge of our mappable world does not mean the world’s end. Certain cultural realities and worlds of knowing may simply be invisible to us, unless we choose to radically challenge our own preconceptions, trusting and supporting the deeply held realities of our community mapping partners.

Indeed, there are different worlds in each of us. There are also shared cultural worlds that invisibly govern our institutions, design our technologies of visualization (i.e. GIS), and condition what we deem “mappable”. What if, when reaching the boundaries of our own mappable knowledge, we consider how to support other worlds of knowing in our work. We must ask ourselves how we diminish other worlds of knowing by assimilation into our own. Perhaps we can recognize our privileged positionality as map-makers and practice radical epistemological reflexivity, challenging our categories of “data” and “evidence” to produce new maps. Maybe we map the dragon. As mappable as increasing annual glacial snow melt. As mappable as declining range and extent of alpine grasslands. 

But can we truly re-consider and re-evaluate our core perspectives, biases, and beliefs during this process? The worlds we know and occupy? Perhaps not completely. What’s more, would such radical reflexivity necessarily dis-empower our scientific perspective in a post-truth world? I don’t think so. I think it broadens our capacity as social scientists to engage in and practice epistemological humility rather than epistemological assimilation. 

​In my research in Bhutan, known as the Land of the Thunder Dragon, we use participatory mapping as a medium to talk about spatially-explicit, place-based deities, spirits, and divinities that reside and preside over forests, lakes, trees, rivers, and mountains. These more-than-human beings have significant bearing on the ways people make land-use decisions, and conceptualize foreign concepts of development, conservation, and natural resource management. By including dragon sightings in the Drokpa community map, without pause, without filter, our Participatory Rural Appraisal (PRA) will not simply pay lip service to aspirations of “participation”. Instead, the map will be a better reflection of the different worlds that reside in each participant, and more representative of the worlds inherited by our intellectual predecessors.

When the map is complete, it will inevitably be incomplete. Maps will always hold unknowns & uncertainties, assumptions and biases, at their edges. If our aim is to challenge these assumptions, we must put the dragon on the map. Beyond myth. Beyond metaphor. We must challenge who has the power to define the “we”: the voices and viewpoints at the table. A map of this type, however partial, may be a stepping stone to increasingly egalitarian representations of our respective cultural worlds: as academics, international development officers, geospatial scientists, and Drokpa herders.Author
David Hecht is a PhD candidate in the Integrative Conservation & Anthropology program at the University of Georgia. His research explores the intricacies of sacred landscapes and lived religion in relation to community-based conservation programs for priority bird species in Bhutan. Follow him on Twitter at @davidmhecht.
