---
title: "Workshop in Community Geography: A first report"
date: "2019-02-14"
---

By: Jerry Shannon​At the end of last month, I and several students from the Community Mapping Lab were able to help run the first international workshop in community geography, or #commgeog19 for short. This two day workshop, supported through a grant from the National Science Foundation, was held on the campus of Georgia State University in downtown Atlanta. It featured presentations from 41 workshop fellows and collaborative breakout groups around topics of common interest. While we will eventually be posting more materials from the workshop, in this blog post I give a brief overview of some of the highlights of the workshop and what stood out to me as one of its organizers.

Community geography is a relatively new subfield within our discipline. In a paper that I and others are working on, we currently define it as

"a form of praxis, one rooted in collaborations between academic and public scholars resulting in mutually beneficial and co-produced knowledge. It draws from and contributes to geographic theorizations of space and place, engaging with research in fields including development, urban geography, political ecology, critical food studies, and health geography. Community geography employs a mix of qualitative and quantitative methods, often makes use of participatory research approaches, and has, as its epistemological framing, a commitment to address pressing social and environmental problems and work toward systemic change. A commitment to praxis entails a fundamental integration of research and action, one that explicitly values excluded and marginalized perspectives and fosters just and sustainable communities."

Geography has a long tradition of participatory and engaged research, and we recognize our connection to past work in public participatory GIS (PPGIS), feminist and black geographies, and participatory action research. Organizing around community geography has provided a formalized way to recognize this work, particularly through the creation of positions explicitly devoted to it at Syracuse University, Columbus State University, University of Central Florida, Chicago State University, and at my institution, the University of Georgia. By recognizing community engagement as an explicit expectation for promotion and tenure, these positions provide a model of academic work that blurs lines between the university and broader publics. While often based at academic institutions, community geography also includes the work of community scholars who partner in research and teaching.

The community geography program at Syracuse--the nation’s first--is now over a decade old, but thus far this group has been relatively small. Community geographers are predominantly academic faculty and staff, most of whom identify as White. To broaden the range of folks at this table, we successfully applied for a grant from the National Science Foundation to hold an international workshop for the full range of scholars interested in community geography. This grant allowed for the workshop to be offered without charge and provided significant travel assistance to many of the workshop fellows who presented their work.

The call for participation to this workshop elicited a strong response. We received 91 applications, many of whom came from scholars new to community geography. From these, we invited 42 workshop fellows. Among these fellows, we had seventeen academic faculty/staff, sixteen graduate and undergraduate students, and none community scholars. Twenty three fellows identified as White, eight as African-American, three as Hispanic/Latinx, four as Asian-American, and two as mixed race. While still predominantly academic and White, this group was more diverse than both the planning team (almost all of whom were White academics) and the academic geographers as a whole.

The workshop itself was structured to promote sharing and connection. The full program is available here. The first day was structured around a series of eight minute presentations, delivered in two concurrent tracks across three sessions. These presentations shared highlights from each fellows’ work while leaving room for questions and discussion of shared themes across presentations. Workshop fellows and other attendees identified these themes, sharing thoughts on large post-it sheets throughout the day.
Photo by Dorris Scott
At the end of the first day, we identified multiple themes from these shared notes:
Participation and engagement
Accessibility and inclusivity
(In)visibility and representation
Teaching and pedagogy
Providing support for community geography
Power and positionality
Creative research methods
​Workshop attendees then signed up for breakout groups, each focused on one of these themes. For much of the second day, these groups outlined potential shared collaborations that could be continued after the workshop. Summaries of these discussions are currently being compiled and will be shared on the conference page, linked at the top of this post.

During the second day, we also took a field trip to the National Center for Civil and Human Rights, just a short walk away from our workshop site. This field trip got us out of the conference space and provided an opportunity to reflect on other struggles many of us address through our teaching and research.
We are still working through evaluations and feedback from the workshop. Many participants expressed strong appreciation for the chance to connect with others doing similar work, and most also expressed a strong interest in continuing to participate in conversations around community geography and collaborating with others at the workshop. We will encourage this work in multiple ways: creating an email list for discussion of topics and events relevant to group interests, sponsoring sessions at conferences hosted by the American Association of Geographers (AAG) and similar groups, organizing a special journal issue for topics presented at the workshop, and securing funding for future events and collaborations for community geographers.

I share a few other photos below, with special thanks to Dorris Scott for being our official photographer. Video from many workshop presentations will be available soon on the workshop webpage.

As the principal investigator for this grant, I’m thankful for the work of others on this team who helped make this event happen. Most notably, Katherine Hankins and the Department of Geosciences at Georgia State University provided significant logistical and financial support for the workshop. The other planning team members were Danny Block, Amber Bosse, Tim Hawthorne, Jonnell Robinson, Dorris Scott, and Andy Walter.

​In sum, the first ever Workshop in Community Geography was a smashing success, welcoming many new voices to the conversation and spurring ideas for future work. Check back on the workshop page for more information and opportunities in the coming weeks and months!
Author: Jerry Shannon is an Assistant Professor at the University of Georgia in the Departments of Geography and Financial Planning, Housing, & Consumer Economics. He is the director of the Community Mapping Lab.
