---
title: "Recognizing Indigenous Cultural Ecosystem Services through Participatory GIS in Southeast Ecuador"
date: "2019-04-14"
---

Estefania Palacios-Tamayo
"We do not have weapons, but now we have GIS to protect our territory. We plan to conserve our natural resources for present and future generations through the maps, our maps."
Domingo Ankuash, ​Shuar Indigenous Leader
During the last five years, campesinos* (peasants) and indigenous people from Southeast Ecuador have started to use maps as a powerful tool for protect their territory against mining companies. Local people believe by mapping their biocultural ecosystem services and territorial boundaries, they are avoiding being cheated by mining companies or by the government. Between Amazon and Andes Ecuadorian region, there is located El Collay Territorial Association, that it is set up by campesino and Shuar indigenous population. 15 years ago, the Shuar communities were the first ecuadorian indigenous population in Ecuador to used participatory GIS. In order to go deeply into campesinos and indigenous Shuar's GIS experience defending their territory, I participated in some community participatory mapping workshops in the El Collay Territorial Association, for the past four years . In this article, I will talk about methodological experiences I have gained over these years and I will show a few maps about biocultural services identified by local communities actors.

Background
El Collay Territorial Association is a political and administrative entity formed by six local municipalities. All six are autonomous, decentralized governments: Paute, Gualaceo, El Pan, Chordeleg, Sevilla de Oro and Santiago de Méndez. This Territorial Association is in the northeastern corner of the Azuay Province in Southern Ecuador. One of the most important inhabitants of this Territorial Association is the Shuar indigenous people. They represent one of the most prominent ethnic group in the Amazonian Region, with around 35,000-40,000 living mainly in the Ecuadorian provinces of Pastaza, Morona Santiago and Zamora Chinchipe, in the southeast of the country. Since 2000, Shuar’s ancestral lands have been assigned for copper mining concessions “for the sake of development”** and, as a result, indigenous communities have suffered persecution and violence. The expropriation of the Shuars’ lands and resources has forced the indigenous community to fight off industrial-scale copper mine and oil extraction and threats to their lands and way of life.

The Shuars struggle to protect their land despite peaceful marches, legal actions, and an international pressure campaign. However, in the last ten years, the Shuars have turned to mapping as a strategy in this effort. Four years ago, as part of my research process to obtain my master’s degree, I started working with campesinos and Shuars indigenous communities. In several conversations, local people pointed out that it is a need to establish community mapping workshops that allow them to delimit their ancestral territories and recognize biocultural services. Later and thanks to local governments and some Shuar leaders support, I managed few meetings and workshops where we gathered an important group of participants that contributed significantly to the project.

My experience in Participatory GIS and Indigenous communities
First, I had some meetings with local actors to explain them the objectives of this project and how Participatory GIS methodology works. There were around 30 participants between indigenous and peasants leaders, that they came from each small villages of El Collay. In a second meeting, I asked the community leaders to make a sketch of their nearest territory, that is, neighborhood or Municipality. Local people had to identify important cultural and natural sites. They used colors, pins and stickers to identify the different types of assets in the community. Once, first workshop finished, I realized that there were major criteria to characterize each small village. Therefore, we used the largest number of responses and create biocultural categories and then units of ecosystem services. As a result, we identified together the categories for important values by local people (i.e. arts, crafts and sacred sites). This outcomes helped me out to make the first map (fig 1). In addition, those decisions over their territory allowed me to integrate each biocultural category as a landscape units in order to give each small village a biocultural unique identity (see fig 2).

Figure 1. Map of Biocultural assets Services at El Collay
The last workshop, I used a local map. In order to avoid bias about indigenous boundaries, I used data from the National Institute of Statistics and Census. I asked them to locate conflict points, that is, environmental, social and cultural problems affecting their territory and changing the landscape. According to local people, the principal territorial problemas are mining companies activities and deficiente local governments administrations. Third, once I finished workshops, I moved to geocoding some biocultural assets exposed by local actors, using ArcGIS 10.5.

Finally, I made two maps about biocultural assets and biocultural ecosystem services. The first map (see fig 1) represents what local actors considered the five essential biocultural elements in their land: archeological sites or sacred sites, traditional skills, food heritage, immovable heritage, and forest (natural elements). Using the biocultural assets map base, I made a map about ecosystem services. So, I grouped characteristics of each small community and made ecosystem services landscape. However, each category can overlap each other, since each village could has all biocultural category in its territory. There are five landscape units: El Collay Forest, Ancestral Knowledge, Sense of Territory, Forbidden Place and the Heritage Food Place (fig 2). The criteria for the cultural ecosystem services classification are the following:

El Collay Forest - This area represents an important element for the El Collay inhabitants, since in addition to be a zone of protection, it is considered a sacred space.
Ancestral Knowledge - It refers to all the knowledge that has been acquired from generation to generation. As for example, the elaboration of crafts, textiles, food preparation, among others.
Sense of Territory - It implies a closeness and an intimacy that is a product of experience, history and time. It demands that people develop an aesthetic sensibility that one gains only when population lives in one place for a long time. This service is mostly located in the Shuar indigenous territory, because for them the sense of territory is linked to the land where their ancestors were born and where future generations will belong.
Forbidden Places - They are sacred places and therefore forbidden to carry out any human activity against natural resources.
Heritage Food - They are characteristic places at local and national level for their gastronomy.
Figure 2. Map of Providers of Biocultural Ecosystem Services
Conclusion and Future projects
There is still much left to do. I plan to continue working over this process in this summer 2019, using counter-mapping approach. The main future objectives are to map sites at risk and conflict, and resilience and resistance areas lead by local communities to mining companies impacts. In conclusion, the maps that have been generated from this participatory GIS process with indigenous and campesinos communities, provide a new way of understanding the world from different worldviews. PGIS maps also demand the integration of these new conceptions of territory, in local territorial planning and national protect biocultural heritage politics of ancestral populations.

Notes
*I use campesinos in Spanish because the word peasants has a negative connotation in English language
**This phrase was part of the neo-extractivism speech by ecuadorian government, during 2014

Author
Estefania Palacios-Tamayo is a PhD student in Geography at the University of Georgia. Her research focuses on biocultural landscape dynamics for territorial planning and conservation of local heritage.
