---
title: "Reflection on Community GIS: Aidan"
date: "2020-05-15"
author: "Aidan Hysjulien"
---

By Aidan Hysjulien

In this post I reflect on my experience working to map the history of Linnentown’s existence and destruction to explore how maps can become part of the historical narratives they tell. The overarching goal of this project was to create a geographic dataset of Linnentown and begin using it to tell some of the stories that make up Linnentown’s history. In many ways, the history of Linnentown tells a far too familiar story of 1960s Urban Renewal used as a tool for private capital, municipal governments, powerful institutions to dispossess and displace black Americans. Linnentown is somewhat unique as an example of an Urban Renewal project undertaken by a public institution of higher education, the University of Georgia. 
 
Mapping a historical narrative presents the additional challenge of working with and against the existing historical record. Throughout the course of this project I felt a nagging tension between a commitment to ‘countermapping’ Linnentown and the necessity of often relying on historical documents created for disassembling Linnentown. These included removal records, maps used to document parcel/building ownership (Image 1), and correspondence between university officials involved in the project. 
 
In working on this project I began to recognize four ways of engaging this uncomfortable tension. First, a critique of the historical records themselves. Second, repurposing the record by highlighting something it contained, but was never intended to show. Third, to animate some dimension of the history by bringing into dialogue multiple records. Fourth, by incorporating historical accounts of those whose voices, perspectives, and experiences were never included in the historical record. 
 
Analysis of maps as a tool of power has a long history if critical/qualitative cartography. The image below is one of the historical maps we used to build our dataset, but it is also a map created by UGA to facilitate the acquisition of the territory. The information these map makers chose to include show what was most important to UGA -- who owns the property, the area of land that will be acquired, when/whether a property had been acquired, and the race of property owners. All property already acquired by UGA was associated with no information beyond stating UGA as the owner. This map was very clearly a tool for the dispossession and displacement that our work with Linnentown seeks to counter, but it was also one of the few records we have of Linnentown. By understanding this map as a tool of power used to translate space into an object of action, I could more carefully glean information from a troubling historical record. The story of the map as a tool of Urban Renewal can then become part of the story ‘countermaps’ can tell. 
 
As our data set began to take shape, I started to see how problematic records contain stories of the past that do make themselves readily apparent. These stories must be teased out by highlighting and recontextualizing some aspect of the data. An example of this can be found in the map above by looking at how vacancy was used as a tool of erasure. For most of the vacant properties there is minimal information beyond the parcel owner. Once determined to be vacant, the property loses its street address, thus breaking one of the paths for building an historical. For many of the properties in Linnentown it was possible to use data from the 1940 census to extend Linnentown’s history by linking people based on address. For vacant properties this link is ruptured. While erasures of the past can involve omission or exclusion, erasure can also involve obscuring the connections that allow us to accurately reconstruct historical narratives. 
 
While there were challenges bringing the 1940 Census together with our data set, bringing these historical records together on the same map provided opportunities to uncover aspects of Linnentown’s history that no single historical record could show. One of the most striking examples of this involved shifts in homeownership between 1940 and 1960 in Linnentown. By visualizing owners/renters for these two datasets it was possible to see a rapid increase in black property ownership in Linnentown between 1940 and 1960s. This finding helps to problematize the characterization of Linnentown by UGA officials as a ‘total slum’. By bringing together unconnected historical datasets the stories of the past can be illuminated in new ways. 
 
In the end, these strategies for destabilizing historical records remain constrained by what they contain and how they can be brought into relations with other records. What continues to be missed here are stories from the people who lived this history, but whose voices and perspectives were never included in historical documents. When we spoke with some of the Linnentown residents still in Athens it became clear their lived experience was a glaring blindspot in the historical documents we had so heavily relied on. It is through community engagement with people affected by the histories we seek to make visible that these stories long left out can be heard and told. 
 
I close this post by taking a step back to reflect on the importance of mobilizing the framework of community GIS to enable an institutional auto-critique by engaging communities affected by the practices of the institution. Community geographers have argued that it is possible to “leverage university community partnerships to facilitate access to spatial technologies, data, and analysis” (Robinson, Block, and Rees 2016). For some qualitative cartographers, the goal is to empower non-specialist communities to use GIS as a political and/or narratives tool. This project has shown me what there is an oft missing dimension to community GIS. Institutional partnerships with local communities can become part of a project that can put forth critiques of institutional practices, past and present, from within the institution. By telling stories about the past that disrupt the present and call for a better future, Community GIS has the potential to be a powerful tool for challenging Universities to recognize and address the problematic practices in their past and present. 
 
References
Robinson JA, Block D and Rees A (2016) Community Geography: Addressing Barriers in Public Participation GIS. The Cartographic Journal 54(1): 5–13. DOI: 10.1080/00087041.2016.1244322.
