---
title: "A reaction to Wilson’s “GIScience I: Social histories and disciplinary crucibles”"
date: "2020-07-29"
author: "Jerry Shannon, Taylor Hafley, and Katrina Henn"
---

By Jerry Shannon, Taylor Hafley, and Katrina Henn

This summer, our lab has started a regular reading group, CML Reads. While students in the lab do research in a lot of different areas, the goal of CML Reads is to get us all on the same page, so to speak--reading, thinking, and responding to a common set of ideas and research practices. We hope to use this blog as a place to summarise these pieces and our reactions to them. 

At our most recent meeting, we discussed Matt Wilson’s new article, “GIScience I: Social histories and disciplinary crucibles,” published in Progress in Human Geography. As the title suggests, this article in the end is about the social histories we tell about GIScience as a discipline. This article is divided into two main sections. The first provides a survey of work published about GIScience within Progress, going back to Peter Gould’s 1969 survey of work on quantitative methods and mapping. Wilson divides these articles into three major periods: (1) 1977 through 1988, where computer driven mapping becomes increasingly common, (2) 1988 through 2002, when GIScience becomes a recognized field and critical responses are also recognized, and (3) 2002 through the present, when GIScience becomes a field distinct from cartography. 

The second half of the article draws from the work of Cindy Katz and other scholars to sketch out whether “minor GISciences” might aptly summarise an ongoing body of work that is not easily categorizable within this subfield. Giving several examples of “radical, critical, and ‘retrograde cartographies,’” (p. 7), Wilson describes how Sarah Elwood, Agnieszka Leszczynski, Biran Jordan Jefferson, and many others open lines of flight with the potential to disrupt and transform work in GIS. This, in our opinion, was the most valuable part of the article. It’s worth reading through Wilson’s description of what minor GISciences means in practice, as it’s difficult to summarise in a brief post (though Jerry did play a minor version of the national anthem to try to capture the basic idea). The article ends by arguing for the value of “minor” work to continually nudge GIScience out of its comfortable disciplinary boundaries, preventing epistemic closure around familiar histories. 

As a group, we appreciated Wilson’s arguments and the histories this piece highlights. That said, there were a few omissions in this article that struck us as curious. Scholars with a long history of critical engagement in this area--including Eric Sheppard and Mei-Po Kwan--were notably absent from Wilson’s history. Even so, we agreed this history was a valuable review and respected how the historical narrative put the six-decade origins of GIScience in conversation within Human Geographers.

More strikingly, there were few explicit references to work in public participation GIS, a strange absence given the way that work in this area has tried to create new forms of research praxis that decenter technical expertise while amplifying voices outside the academy. In our work within community geography, this has been a main focus, and certainly acts as a “minor” form of GISciences. Indeed, some cited examples do rely heavily on participatory research methods, most notably the work of the Anti-Eviction Mapping Project. Yet these are praised for their contribution to topics of critical interest (e.g., mapping eviction) or attempts to blend critical theory with GIS methodology, without reference to the social context for this research. That said, all pieces have limited space, and we do not know what will be included in the next two progress reports.In addition, the three of us in this meeting all came in with clear commitments to critical GIS as a way to define our work. While we were sympathetic to the “minor” label, we struggled to identify clear areas where it was easy to differentiate it from other threads of work in this area (e.g., qualitative GIS, feminist GIS, and 'doing' critical GIS). The article itself didn’t attempt to do so, perhaps again because of limited space. but justifying the need for yet another brand of critically informed geoscience research would have been helpful.

In the end, Wilson rightly notes that we need more diverse histories of GIScience within our discipline and that it is crucial that we resist the drive to “reduce geography to a dashboard” (p. 8). We appreciated reading this piece and look forward to future entries within the series.

Authors
Jerry Shannon is an Associate Professor at the University of Georgia in the Departments of Geography and Financial Planning, Housing, & Consumer Economics. He is the director of the Community Mapping Lab.

Taylor Hafley is a PhD student in the Department of Geography at the University of Georgia.Katrina Henn is a Master's student in the Warnell School of Forestry and Natural Resources at the University of Georgia
