---
title: "Reflection on Community GIS: Katrina"
date: "2020-05-15"
author: "Katrina Henn"
---

By Katrina Henn

This semester was one of many tumultuous twists and turns. No duh. But seriously, this semester was incredible, obvious COVID-19 happenings aside. It was one long film reel, where each scene fit perfectly in some way with all those preceding and all those to come. Sometimes they would melt together in a wonderfully confusing mess of academic discovery and crossover episodes: my thesis project was going to include an historic African American neighborhood in Athens, and I was beginning a small pilot study for it to fulfill a requirement for one of my classes. My other 2 courses involved working alongside and learning from other African American residents and neighborhoods, both those gone by and those still here. I learned about blatant racism and classism in the past and discussed with classmates a shared unease of its existence today in the present projects. One thing I learned this semester: we (as in UGA, Athens, other communities, the state, and the country) still have a long way to go.

The Community GIS class was no exception in providing these strings of discoveries and realizations. Like everything else this semester, it was serendipitous given that I had to come up with some community mapping exercises for the neighborhood I would be working with for my thesis. To risk sounding borderline cliché, the course swept away so many of my previously held notions on cartography. You think maps are scientific and objective? Wrong—they can portray a myriad of perspectives on the same topic and make an argument for or against anything. You think maps are only good for orienting yourself? Wrong again: they can be a statement on a community’s identity. You believe the mapmaking process is a lone routine on your individual computer? Think bigger and more collaborative. Sometimes, it is the process that empowers the community and that matters more than the actual product.

This paradigm shift extended its grasp even further to the way I simplythoughtabout our class project and my thesis in relation to the residents. Indeed, it felt strangely (and humbly) akin to having to learn about manners and respect in grade school again. One afternoon when seeking Dr. Shannon’s counsel on my thesis, no sooner did the phrase “help the residents” roll off my tongue than when he stopped me to prove a critical point: I/we are not swooping in to “help” people and save the day. I/we are not just coming in and providing much needed education or information and changing everything. We each bring something different to the table, with each thing being just as valuable as the last. We may bring a level of academic knowledge or computer literacy skill, while some residents offer community knowledge and history. Some might bring other technical skills or a refreshing perspective. The point is everyone has something to offer.

What I thought the Linnentown residents really brought when they stepped into our classroom, however, was the beating heart and life of a community we never knew. My classmates and I had spent many hours digitizing parts of Linnentown and creating maps of the place. We had read some documentation on its removal and gotten to visit the archives with Joey and Rachelle, both part of the Linnentown Project. Those were good first steps to becoming acquainted with the neighborhood, but nothing made the place feel alive like the residents themselves that day. Stories of the good and the bad abounded, of childhoods spent traveling the neighborhood paths and organizing ball games to fearful nights listening to the neighbor’s home being destroyed. Of how only one resident had a phone, so everyone shared it. Of an uncle with multiple sclerosis who carved steps out the mud on a hill so one person’s mother could walk more safely to and from work at UGA. These were stories of a tight-knit community so many of us wish we had today. These were stories of resilience which made Linnentown that much more alive. I believe it is these stories that really motivated the class to pour our best into the project. And, I believe it is these stories that humanize the neighborhood to others. Now we know the people whose homes were ripped away. Now we know the people whose tight-knit social networks were disrupted. All of this arose from simply trying to map a community. We were experiencing truth in what we had read: that the process itself is actually meaningful. I think the residents felt similarly, as one explained:
 
“You know, Linnentown may have been destroyed and taken but in our minds and hearts as long as we live it just, something about that community. And the way it was taken from us, I guess. That's what put this pain on our brains, it’s just a waste and the way the communication was in the neighborhood everybody knew everybody. You know, I mean it was really like a family thing and a lot of people today may not understand what I'm talking about because I have to go to neighborhoods now and a lot of people don't know who stays down the street. But in Linnentown, everybody knew everybody. So, you know, this is just fascinating to me to be here and…just let out things that we have held for 50 something years because it was like Linnentown was forgotten.”
--Bobbie (Linnentown resident)

 
Linnentown residents are continuing to seek redress from the city of Athens and UGA. When you feel like you actually know someone or even a whole neighborhood, you feel that much more strongly about it. I hope they get the outcomes that they are asking for, and perhaps some of our work will aid their mission. The process, however, was full of lessons and experiences I will be taking with me wherever I go. Not only will I be more aware of the continued presence of our past ghosts and grievances, but I hope to become a more active, empathetic, and responsible citizen in bringing these issues to the forefront.
