---
title: "CURO Reflection--Mapping Social Services"
date: "2020-02-01"
---

By Jenny Gallucci

[Note: This was Jenny's second time working as a CURO student in the lab. In her first fellowship, she assisted in collecting data on gentrification and housing displacement in Athens' Hancock neighborhood.]
Fall semester 2019 concluded my second and final experience with CURO, a program providing undergraduate students with funded independent research opportunities, at UGA. This time around with CURO, my work focused on creating a large print map of agencies offering services for those experiencing homelessness that would hang on the wall at the Sparrow’s Nest, an agency providing help to those experiencing housing transition. An online map of these services was created in Dr. Shannon’s Community GIS course in the spring and is currently accessible via the Sparrow’s Nest website . Jamie Scott, the director of Sparrow’s Nest, expressed there was a need for a print map for those who are not computer literate.

I re-created a map of services using data collected by Dr. Shannon’s students, complete with bus routes, parks, rivers, and roads. I then used PowerPoint to arrange the map and other elements such as agency information and contextual information into a printable 36 x 24 in. poster. I largely based the format of my poster off a downloadable map of services on United Way’s website, created by another CML student in years past, although my final product ended up deviating from that template a bit.


One thing that CURO has repeatedly illustrated to me is that it takes a village; reflecting on this semester, I reached out to and collaborated with five people from completely different offices/walks of life to get this map done. I contacted Daniel Sizemore at the ACC Park Planning office to get the parks data set, visited Meagan Duever in the UGA map library several times to solve some GIS issues that came up, and asked Adam Salway, who now works for Wesley Church, for some details about how he made his map, which I followed as a template. I of course also collaborated with Jamie Scott of Sparrow’s Nest and Dr. Shannon to create a cohesive final product. I’ve really come to understand the importance of knowing who to reach out to and not being afraid to ask for help when you need it. The connections I’ve made through internships and classes during my time at UGA really benefited me as I was conducting independent research. CURO has really taught me how to effectively troubleshoot my problems and tackle them in the most effective way, which is without a doubt going to be a skill that I’m going to take with me into any career I chose to enter.
Jenny (right) handing off the final map to a staff person at Sparrow's Nest
This semester’s CURO project proved to be different than my first project technically; the Sparrow’s Nest project was largely a cartography project, unlike my project last year, which was less primarily focused on aesthetics and more a mix of transcription and qualitative data collection in addition to map-making. Through my project, I started to learn some more cartography basics and programs best suited for cartographical work. I have found that CURO opens doors for me—I wasn’t really aware of the ways geographers use Adobe Illustrator to make high quality maps and the extent of the world of cartography. Both years, CURO has allowed me to explore the intersection of GIS and community, showed me the potential of what’s possible, and reminded me of just how much I have left to learn. I’m so appreciative of everyone that has helped me on the journey through these projects and the unique experience CURO has been.Download a PDF of the map Jenny made
