---
title: "Creating a Bike Route Network for Athens-Clarke County"
date: "2021-05-05"
author: "Emilie Castillo"
---

By Emilie Castillo

For the past two semesters, I have worked as a CURO Research Assistant in the service of the Community Mapping Lab and BikeAthens towards the goal of creating a comprehensive cycling map of Athens-Clarke County (ACC). While the project will most likely continue into next fall, as of the end of this semester we have succeeded in creating a web-based map of biking routes throughout the county with classifications noting the safety/preference level of each route, bike lanes, multi-use trails, slope, points of interest, and bus stops. This project was undertaken at the request of BikeAthens for the purpose of making cycling in Athens an easier and safer alternate form of transportation. Alongside Olivia Gilliam, a fellow CURO Research Assistant, I worked as an aid to Dr. Jerry Shannon, who headed up this project in the Fall of 2019.
 
In recent years, Athens-Clarke County Government as well as several community organizations have been interested in building up and refining the cycling infrastructure and resources of ACC. BikeAthens in particular operates with the mission of creating equity in transportation; when they requested the Community Mapping Lab undertake this project, they hoped the map would assist both novice and seasoned cyclists in planning rides throughout the county. That being said, this project was not concerned with classifying the safety level of every existing road or path in ACC, nor was its purpose to showcase recreational rides. The web map, as it is today, displays and classifies those routes necessary for travel throughout the county along with destinations determined as useful or necessary for those using a bike as their main form of transportation.
 
When Olivia and I began working on this project in Fall 2020, a former student, Regina Nasrallah, had already worked with Dr. Shannon to determine some points of interest and classify some existing road data. Olivia and I began our research by collecting more points of interest (POI). First, we had to determine what were “useful and necessary” destinations for the people in this community and for cyclists in general. Grocery stores, healthcare clinics, bike shops, bike repair stations, bike parking, pharmacies, dollar stores and coffee shops were some of the categories we discussed; we needed to make sure we were being as inclusive as possible when compiling this list because we did not want our map biased towards any particular demographic, rendering it useless to large portions of the Athens community. After determining this list, we needed to collect the location, name, and service type of all the destinations in ACC falling under these categories. I relied heavily on Reference USA, a database of businesses located in the U.S. available through UGA’s Library website. We also extracted several locations from OpenStreetMap. In some cases, a list had already been partially compiled for some destination types, but for the most part we had to search around to make sure we were getting everything. We then organized all these collected data points into a single spreadsheet and mapped it. At this point, we noticed how few points of interest are located to the East of the Loop/ SR10 and we added random location points occurring on the eastside in order to ensure our routes were not missing large chunks of the county.
 
With the comprehensive POI data mapped, Dr. Shannon used R software in conjunction with Google, HERE, and Mapbox routing APIs to generate approximately 1,500 routes for each routing service between all our identified POI’s (over 600 points). We identified common streets used by those three services and aggregated them to make our first draft routes.
 
At this point we began to classify the routes, relying heavily on speed limit as an indicator of safety. Later, BikeAthens helped us better classify routes as safe and unsafe from their personal experiences as cyclists in Athens. We were using Strava Heatmap data as a point of reference to determine if the routes we had were ones actually travelled by cyclists and to identify routes we may have missed entirely. I georeferenced screenshots of the Strava Heatmap for the entire county so we could easily compare and edit our data within QGIS.


A large portion of this spring semester has been focused on editing the existing bike routes. Dr. Shannon generated slope data for all the road routes from elevation data provided by Athens-Clarke County. We attempted to gather public feedback through a Survey123 form that allows the user to comment on specific locations of our draft map; however, as the COVID-19 pandemic persisted, public feedback became challenging and often disappointing.
 
Once we had edited our draft routes to some degree of satisfaction, we began transferring our data from QGIS to ArcGIS Online to begin configuring the web app. We focused on cleaning things up to ensure the map would be easy and intuitive to read. We trimmed down our initial POI data to a smaller pool of points and set the transparency level of that data as smaller than that of the routes so as not to overwhelm the reader upon opening the WebApp. We also began to discuss the best way to color routes, bike lanes, and trails. Further, we determined the best symbols to denote our points of interest and slope. Daniel Sizemore, Bicycle, Pedestrian, and Safety Coordinator from ACC Unified Government, assisted us and is still in the process of organizing data to provide our map with a more comprehensive list of bike lanes. We reviewed several other similar bike route maps of other cities such as Vancouver, Portland, Madison, etc. to get a better idea of how to visualize the data. Dr. Shannon and I worked on creating a print map for BikeAthens staff and patrons to mark up physically, but again, community feedback was difficult and less fruitful than we hoped.
 
Now, as the semester is ending, we feel that we have a solid draft to start distributing to the public, with the understanding that the routes will continue to be refined and updated throughout the rest of the year. In our final meeting with BikeAthens, we discussed the possibility of one more semester’s worth of work in collecting that much-need feedback from the community. BikeAthens is interested in creating some formats of the map that can be easily printed, possibly even some pocket size maps to be kept at BikeAthens and other biking resource locations.
 
I really enjoyed working on this project and feel I learned a lot about GIS project management. It was extremely valuable to see first-hand what it is like to work with local organizations and utilize those available resources in showcasing data. Before this experience I would not know how to even start, and now I feel confident in my ability to organize the steps of a project like this and be a part of the construction. The COVID-19 pandemic kept us from meeting in person and facilitating more community events where we could have generated feedback and creative collaboration, and that setback was felt by all of us. Zoom fatigue and generally busy schedules made me feel like I did not engage with this project as whole-heartedly as I could have. A part of me wonders if we had been able to meet in person whether we would have gotten more done in that first semester, giving us more space for creativity in the second semester. All things said, I am really proud of our final product and I hope to stay in the loop about the future of this map and its impact.

Emilie Castillo recently received an undergraduate degree in Geography alongside a certificate in GIS at the University of Georgia.
