---
title: "Reflections on UGA and Linnentown"
date: "2022-03-18"
author: "Bryant BeallStudent in Community GIS, Spring 2022"
---

By Bryant BeallStudent in Community GIS, Spring 2022I am currently taking a class called Community GIS. Community GIS teaches how GIS is used to research by local agencies, and community groups. In Community GIS we have mainly focused on a small former community in Athens called Linnentown. I always really enjoy learning more about local history because it can help explain why things the way they are today. History is even more interesting to me when it involves people or organizations that I know of or are physically close to. This is partly why I have found our study of Linnentown to be so encapsulating. Linnentown was a historically black neighborhood off of Baxter Street near the campus. In the 1960’s Linnentown was demolished by the University of Georgia so that they could build the dorms. The residents of Linnentown were forced to leave their homes and community as the University slowly acquired all plots of land through eminent domain or private sales. Residents were forced to leave their communities that they had lived with and trusted some for generations. In class one of our required readings was from a book titled Giving Voice to Linnentown. This was a story of what it was like to live in Linnentown from the point of view of a former resident Hattie Thomas Whitehead. This personal account struck me hard because it shows the fears and experiences that someone had when they were told they have to leave their community. She tells a story that the university had bought the land that their rented house was on so they bought a different Linnentown plot and built a house on it. The city approved the construction and said they would add plumbing to the house, but they never did. Soon after, the rest of Linnentown was acquired by the University, even the new house. The city knew that this land would soon be owned by the university, so that raises the question. Why did the city approve of this construction and waste this families time and money when they knew the whole time that it would soon be university property? After learning about this story I could not help but feel shameful about the school that I love. I love this city and I love this school but it makes me feel very sad to think about some of the extreme wrong doings done that they are responsible for. I wish that the University of Georgia would acknowledge what happened and issue an apology or do anything about this situation. I know a statement could never fix what they did and the families they uprooted, but it is at least a start and better than ignoring the blame like they are currently doing. In my Community GIS class we are currently working on a story map project covering the history of Linnentown. My hope is that when people come across this story map they will not only be informed of Linnentown and the hardships its residents experienced, but that it will inspire people to speak up and raise awareness for Linnentown and other communities that underwent urban renewal projects.
