---
title: "Mapping and Multiple Perspectives"
date: "2022-04-20"
author: "Phillip Jones"
---

By Phillip Jones
Student in Community GIS, Spring 2022
Imagine you were tasked with creating a map of your hometown. How would you go about doing this? You may start with popular roads, neighborhoods, and parks. Then, you may throw in some popular landmarks like the city hall, schools, and libraries. This may seem like a straightforward and fact-oriented task. However, you can’t possibly map everything in the town, as this would be overwhelming for the reader and impossible for you do to by memory. You may find yourself choosing landmarks that are most important to you. You may also find that the overall impression of your map reflects your perception of your hometown. The map may be dreary or dull if that is your perception of the town, or it may be brightly lit and exciting if you have fond memories of your childhood.
 
Maps often give the impression of being concrete and factually correct. However, like any other form of media, they are narratives being proposed by their authors. In our Community GIS course, we have been introduced to theoretical frameworks that help us question the intention behind a map: Who created this map? Who is the intended audience? What biases may the author be influenced by? What narrative does this media promote? What voices are missing from this map? Ultimately, we have learned to be wary of the predominant narrative of maps, as they may be reflective of the loudest and most powerful.
 
Most recently in our Community GIS course, we have finished a project about the Linnentown neighborhood in Athens, Georgia. Linnentown was a Black neighborhood along Baxter Street that was destroyed by UGA and the City of Athens in the 1960s through a federal Urban Renewal grant. All houses in the urban renewal area were torn down and all residents were displaced. In their place, UGA built three large dormitories and a parking lot to house freshman UGA students. Through their power, the city and the university characterized the neighborhood as run down and a “slum” to justify displacing a proud and close-knit Black community.
 
Because of the efforts of first descendants of Linnentown and organizations such as the Linnentown Project, the neighborhood’s story has been told, and steps have been made to acknowledge the harms done and provide reparations. To support their efforts, the Spring 2022 UGA Community GIS class has created an ArcGIS Storymap to support the Linnentown Project and first descendants of the neighborhood to bring memories of the neighborhood to life. The Storymap synthesizes first-hand accounts from first descendants Ms. Hattie Whitehead and Mr. Bobby Crook, archived records from the UGA Special Collections Library, and research by UGA professors to tell the story of the Linnentown community, its erasure, and the resistance of its residents to their removal. For example, through a guided video tour, Ms. Whitehead and Mr. Crook share their memories of the neighborhood, which is a sharp juxtaposition from what the area looks like today. It also the process of UGA acquiring properties in the area, aerial imagery displaying the destruction and replacement of the Linnentown community, and evidence of the resident’s resistance to being displaced. The Storymap culminates with a timeline of advocates’ efforts to demand redress and resources on how to become involved.
 
In Community GIS, we have learned that there is no one correct way to describe an area. Instead, many perspectives can all coexist at the same time. However, the perspective of the area around Baxter and Finley Street as just freshman dorms is incomplete and is an injustice to the community of people in Linnentown that were displaced from this area. Using digital storytelling technology, we can share memories, identify important landmarks, and explain how Athens and UGA used their institutional power to transform these areas at the expense of the Linnentown community. Doing so will not bring back what was lost, but this tragic history must be exposed. It is never too late to hold institutions and people to account for their actions, as doing so will communicate that the unjust destruction of people’s homes is unacceptable and prevent it from happening again in the future.
