---
title: "Building Trust in Community Research"
date: "2022-04-20"
author: "Trevor UnderwoodStudent in Community GIS, Spring 2022"
---

By Trevor UnderwoodStudent in Community GIS, Spring 2022

As a student in Community GIS, taught by Dr. Shannon, I’ve been faced with various readings and opportunities surrounding-of course-community GIS. Through exposure to the practices and ideas that have been taught, my approach to mapping (from idea conception to completion) has evolved. By education I’m an ecology major, and most of my experience mapping up until this course had been in mapping ecological phenomena like population dynamics, habitat ranges, and ecosystem boundaries. While those mapping focuses may seem different to the Linnentown storymap and Athens 1958 maps we’ve mapped throughout this course, I think there’s a bounty of approaches to mapping that could stand to be adopted in my niche of GIS.

In this blog post, I want to talk about how I would have applied what I know now to past projects I’ve worked on; specifically, as a fisheries technician for the United States Forest Service (USFS) in Oregon. I want to focus on this experience because of the importance of the projects I did there, but also because of the community-project interactions that were present. There’s one specific project I was a part of that I think, if I had known what I know now, could have been handled differently by both myself and those in charge of the project.

One of the largest things that struck me during my time in Oregon was the importance of PR. The public’s perception of the USFS in Tiller where I was working was polarized; some people loved you and others hated you. For some, the Forest Service was doing important work that would end up benefitting the public, for others, the forest service was a clandestine organization that was trespassing on “their land”.
Our project I was a part of was doing snorkel surveys for the Umpqua Chub, a state-threatened fish species. We would get in wetsuits and hop in rivers/streams at public access points like bridge crossings, boat launches, and roadside pull-offs and record the number of fish we saw along with the coordinates to map later. People would come up to us during/after the surveys and ask what we were doing. After we gave them an answer as to what the surveys were for and why we were doing them, most people would respond with a friendly “cool!” or “that’s neat”, but sometimes people would say we had no business being there and, in a few instances, would harass us.

I think if the Forest Service had involved the communities around where we were doing surveys more, we would not only have been on better terms with those communities, but would also see a higher degree of approval for that specific project. In this course we talked about community involvement in GIS, and broke down a figure (Arnstein’s ladder) showing different levels of this type of involvement. In a federally sponsored project, including citizens in a research project to the degree of letting them do GIS analysis would be difficult, but at least getting to the higher rung of “partnership” from “informant” on Arnstein’s ladder would have been satisfactory. In my experience there, the people that engaged in harassment seemed to feel undermined when being informed about what we were doing, maybe feeling as though they were being treated as unintelligent.

Building a trust between the groups doing research and the communities in which the research is being done is mutually beneficial, and something I’ll always reflect on when performing work like that again. That shared vulnerability makes for a stronger flow of ideas, and a better product. In our Linnentown storymap project, the experiences and feedback of resident Hattie Whitehead were directly incorporated into the final product. Our project aimed at telling the story of Linnentown, both how it was, and how it’s been erased by The University of Georgia Urban Renewal Project. I was able to benefit from learning from a first-account of the story we were trying to tell. Getting to see and hear about her experiences and having feedback directly from her was extremely helpful, and largely the basis of the depth of quality for our finished product. There wasn’t any preconceived animosity between the parties working on the Linnentown storymap project like there was between the USFS and communities in Oregon, but just the action of communication and transparency like in the project our class worked on are enough to build a foundation of trust. This class has challenged me to think beyond a cartographic result; rather, it’s encouraged me to think of the process of reaching that result.
