---
title: "Linnentown, Eminent Domain, and Generational Wealth"
date: "2022-03-23"
author: "Elijah HumphriesStudent in Community GIS, Spring 2022"
---

By Elijah HumphriesStudent in Community GIS, Spring 2022
When discussing topics of racial justice, generational wealth is a topic of utmost importance, and land ownership specifically is well explored. The “land as liberation” ideal and the historical factors surrounding different movements towards and away from the accumulation of generational wealth in the form of land ownership for the African American population in the South has been tested by various movements. For example, Fannie Lou Hamer’s Freedom Farms sought to return land to Black people in the South and achieve a level of autonomy and independence from a political and economic system that shamelessly segregated and disadvantaged them. But the benefits of land ownership are multiplicative. A landowner gains a larger stake in their community and the ability to slowly build that wealth, then pass it on to their children. By 2021, 27% of American wealth was in the hands of the top 1.0% of the population, this gap has only grown since then, and about 40% of wealth in the US is inherited (Source). So when we consider how, despite movements to fix the divide, generations of African Americans were denied the ability to buy and own land, there’s a clearly forced inequality in that sphere which allows people to build generational wealth.

It was intentional, too. The Housing Act of 1949 cleared the way, quite literally, for a clean sweeping of the urban poor, because it allowed governments to do away with poor or substandard housing in urban areas, called urban renewal, as more affluent citizens moved to the suburbs. With the advent of urban renewal projects, governmental officials had the toolset to clear “blighted” or “dilapidated” areas in their jurisdictions, but these overwhelmingly targeted Black populations and other minority groups. In more recent years, urban renewal practices are viewed as discriminatory across the board. The U.S. Commission on Civil Rights published a briefing report in 2014 titled The Civil Rights Implications of Eminent Domain Abuse, which analyzed two Supreme Court cases, Berman v. Parker and Kelo v. City of New London, looking at the decisions, critiques, and several studies and briefings that identified cases of eminent domain abuse and its effect on poor and minority communities and how that might be interconnected with civil rights. The report noted a 2007 study titled Victimizing the Vulnerable: The Demographics of Eminent Domain Abuse which found a disproportionate impact on communities with the least power: “more residents in areas targeted by eminent domain-as compared to those in surrounding communities-are ethnic or racial minorities, have completed significantly less education, live on significantly less income, and significantly more of them live at or below the federal poverty line.

Here in Athens, one such area was Linnentown, a neighborhood adjacent to the University of Georgia campus. Starting in the 1950s, the University and the City of Athens began making moves to condemn land so that the University could expand. The University of Georgia campus was almost entirely surrounded by residential properties, and had plenty of land to look at for expansion, including through buying it at a fair price, but instead worked to have the Linnentown residents forcefully removed from their homes. First, by making it a completely unsafe place to live, and followed by more aggressive measures, until they were told that they simply could not live in their own homes anymore, that they had been bought by the University at a pittance, and that they would have to find new places to stay. The University refuses to acknowledge its role in these proceedings, or that it participated in what is widely known to be racially discriminatory practices for its own benefit. As students, and people interested in doing what is best for our community, we should keep pushing for recognition and reparation.

Our class is working to create more recognition for the people who seek to right these wrongs. By offering our time and capacity as students, we help put together marketable information that will help more people understand what the University and the City did, and why those actions were detestable and worthy of condemnation. As more and more of the information we consume is transferred over a digital medium, it becomes more important to make history more accessible and clear to others. By contextualizing and narrating the circumstances and proceedings of the urban renewal project that destroyed Linnentown, we bring the issue back to the attention of our peers and contemporaries. I’ve been working on a storymap, a web page that allows anyone to scroll through a narrative experience curated by myself and the rest of the class, that will display much of the information surrounding both the historical events and the contemporary actions we and others have taken.
