---
title: "Opening access to GIS in support of AADM"
date: "2022-05-06"
author: "Amber Orozco, Student in Community GIS, Spring 2022"
---

By Amber Orozco, Student in Community GIS, Spring 2022

What do you think of when you hear the word “open access” in relation to research or community-based work? Perhaps it brings to mind programs, tools, and academic publications that have no paywall? Or maybe you think of a community that shares resources, such as software code? But in what ways can the approach of open access be a way to support local community organizations?
 
In our Community GIS class, we have spent the last few weeks of the semester thinking through these questions as we work to support the campaign of a local organization, the Athens Anti-Discrimination Movement (AADM). AADM “advocates for racial and social justice and strives to combat discrimination through education and activism”. Part of their efforts includes their “United Against Discrimination” sticker campaign where they ask local businesses to pledge to creating a more diverse and inclusive work environment. If the business decides to participate, they receive a AADM sticker (see photo below) to place on their business’s front window. As a class, our goal is to create a map that will be hosted on AADM’s website, showing the businesses in downtown Athens that are supporters of the campaign.


Local businesses in Athens supporting the AADM United Against Discrimination campaign (Photo Credit: AADM)
For this project, open access can be understood in two different ways. First, open access for our work takes the form of a process-based approach (Shannon & Walker, 2018), meaning our class is working collaboratively with AADM to gather input on the project, including the timeline, goals, exchange of resources (i.e. AADM provides our class the list of business supporters of the campaign from 2019), and how the map will be both stored and accessed. Our collaboration with AADM is consistent throughout the process, which included us meeting with Denise Sunta (AADM Administrative Assistant and Events/Community Outreach Coordinator and also UGA alumna) at the beginning stages of the project and we will be ending the project with presenting our final map designs to AADM for their approval.
 
Second, our class is leveraging our technical skills to create this map through an open access mapping program (QGIS) and coding library (Leaflet). Our class was tasked with verifying whether the list of businesses provided by AADM were still participating in the campaign. To do this, our class divided up sections of downtown Athens to assess which businesses had the AADM sticker displayed on their front window. We used ArcGIS’s Field Map data collection application to update this information, including adding new business supporters of the campaign. Our class was able to utilize our university membership to access paid GIS applications, such as Field Map, for this project.
 
Once this list was updated, our class added the geographic coordinates to each business. We were then able to upload this list through excel to QGIS and map out the businesses. Using Leaflet for codes to customize the functionality and appearance of the map, our task is now to develop a map that serves the needs and goals of AADM. Our class is currently divided into different teams, and we are working to develop different options for AADM. For example, my group is working to use codes from Leaflet to develop a pop-up label that will appear when someone clicks on a business that is a supporter of the campaign. We intend to include information on each business, such as the hours of operation, website link, a photo of the business. Additionally, we are developing an option on the map that allows a visitor to filter for the type of business, such as “restaurant, bar, and retail shop”. Once we decide on the format on the map, it will eventually be uploaded and hosted on Github. Personally, this process of transitioning from ArcGIS to QGIS and Leaflet has been challenging because some coding knowledge is required to format the map in my group’s vision. The last time I encountered html was in high school, but I think getting comfortable with these open access programs are a matter of practice and will require more time learning compared to more user-friendly programs, such as ArcGIS.
 
From this experience, I have learned that open access is more than free programs and resources. It can mean leveraging technical expertise as students to support the efforts of community organizations, while engaging the community organization through the process to ensure the organization’s perspectives are centered as the tool becomes developed. Open access extends to the programs we used with no paywall and those programs that we had access to through our university membership. Each of these elements play an important role when partnering and supporting the GIS work of community organizations.
