---
title: "Working Geo(graphically)"
date: "2022-05-06"
author: "Eli Vinson, Student in Community GIS, Spring 2022"
---

By Eli Vinson, Student in Community GIS, Spring 2022“I study Geography and Graphic Design; I know it’s kind of a random mix.” - A line I have used the majority of my time at UGA when introducing myself, until this year. For a long time, I failed to realize that two of my biggest interests were far more intertwined than I had thought.
 
This semester I took a class called Community GIS where I actively learned real-world applications for GIS concepts and methods. One of these concepts was ‘qualitiative’ GIS. Qualitative GIS incorporates non-quantitative data into GIS in an effort to give perspective and narrative to a research topic. A great example of qualitative GIS that the class was first introduced to was a project by Meghan Kelly (2019) titled, “Mapping Syrian Refugee Border Crossings: A Feminist Approach.”
 
In her project, Kelly wanted to provide a fuller representation of Syrian peoples’ border experiences using cartography, as opposed to Western media’s cartographic practices that aggregated refugees into flow lines, proportional symbols, and frequently simplified border experiences into homogenous, black line symbols. Kelly wanted to discover both how can the cartographic portrayal of Syrian border experiences be improved to more fully represent their lived experiences and further, how can a feminist perspective inform an alternative mapping of borders and border experiences. Kelly states, “Through a feminist lens, I have developed an alternative mapping technique that emphasizes borders as a theoretical and conceptual advancement in cartographic design and border symbolization.” At this point, while reading through Kelly’s methods, I began to recognize the deeper relationship held between Geography and Graphic Design. By projecting Syrian stories and experiences through cartography, Kelly’s qualitative GIS work gives Syrians a geographic voice unavailable to them through conventional cartographies.
 
Up until this reading, I viewed design within geography/cartography as nothing more than functional, with little room for creativity. The kind of formulaic and simple, generalized designs that I had attributed to the whole of research-based cartography, did very little to grab my interest. I knew there could be aesthetically pleasing or thoughtful and uniquely designed maps, but I thought the only place for these designs would be on the wall above your couch rather than in a serious research paper.
 
Kelly’s cartographic design wanted to give a fuller and unique value to borders. Kelly describes that, typically, cartographers place borders near the bottom of the visual hierarchy, receding into the background as part of the base map or reference material. The designs for borders typically default to thin, solid black lines and symbolize them homogeneously. These design choices remove the true image of a border including individual experiences, such as the danger and legal issues involved with crossing borders.

To achieve a more robust symbolization of borders and to move towards qualitative/narrative GIS, Kelly presents a design technique that aggregates the border experiences of seven Syrian interviewees. After immersing herself in the stories of each experience, Kelly used ArcMap to create the design that served to symbolize a truthful and emotional depiction of the stories. Kelly defined spaces and borders abstractly by bounding them with an abstract square shape that could be easily applied to a variety of non-traditional borders found in Syria. Kelly describes that this design choice enabled her to bring both non-traditional space and non-traditional borders, such as the human body, into the maps.
 
The most interesting design choices to me were that each border in the map is symbolized according to the intensity of individual experiences and the border’s passibility. A line of a border increases in size if the emotional toll of the experience increases and becomes thinner if the experience is understated or minimal. To distinguish her own voice and to elevate the voice of the interviewee, Kelly utilized different typographic choices. The interviewee’s voice was identified in a black, sans serif typeface called Myriad Pro, while Kelly’s voice was written in a gray, serif typeface named Garamond. I think the color and individual typefaces place each voice at different volumes and formalities, (Serif = more formal, gray = lower volume, black = higher volume/more importance).
 
Discovering this combination of Graphic Design and Geography and recognizing their importance to each other in creating a meaningful research project was very impactful for me. I now have an entirely new thought process in creating maps moving forward where I will utilize my design experience and creativity more so than following a general map template. I hope that any geographers reading this will consider a creative and thoughtful approach to their map designs in the future as well in order to help create more engaging and impactful maps.
