---
title: "The Impact and Importance of Community GIS"
date: "2022-04-20"
author: "Molly DunnStudent in Community GIS, Spring 2022"
---

By Molly DunnStudent in Community GIS, Spring 2022
 
GIS has the ability to tell a powerful story by legitimizing the perspective of an individual or group that has struggled to be taken seriously. In Sarah Elwood’s book Qualitative GIS, she says “many of the powerful actors and institutions whom they seek to influence treat GIS-based data and maps as illustrations of what is real or true about a place, and as evidence of an expert (and therefore, legitimate) portrayal of that place” (Chapter 4: “Multiple Representations, Significations And Epistemologies In Community-Based GIS”, page 70). Throughout my time in our Community GIS class, I have learned the importance of making maps with caution and consideration, especially when they will be used to persuade or provoke.
 
For the past few weeks, my class has been working on an informational StoryMap (a collection of public, multimedia web maps) about Linnentown, a Black community erased by UGA and the City of Athens to build dorm buildings in the 1960s. From the beginning steps of the project, it was evident that we had an important task to complete. We were not working with simulation data or practice labs. We were working with real stories, from real people, about real places. As the project developed and I heard more from Hattie Whitehead, a resident of Linnentown, I began to see the impact that our StoryMap could potentially have in aiding her mission to bring redress to the people who lived there. The importance of being cautious with each choice we made throughout the project was clear. In one of our meetings, she told us that when brainstorming the book she recently wrote about her experience, she wanted to compile the data together before she wrote and published it. It was then that I understood the point that Sarah Elwood was making - there is power in a visual representation with data behind it. It can be the tipping point that allows a movement or a story to be recognized as legitimate.
 
One of the ways that a map can be made with consideration is by capturing the emotion in the place it is portraying. In Meghan Kelly’s article “Mapping Syrian Refugee Border Crossings: A Feminist Approach,” she walks the readers through the development of her map of Amal’s story, a man living through the conflict in Syria. She chooses symbology that alludes to the ways that he experienced the borders - for example, how difficult it could truly be to move from one place to another. This kind of information can be difficult to show through maps, but if done correctly it can add an entirely new layer that is meaningful and informational. She was able to transform his story into an immersive piece that showed the way he experienced life in Syria. She prioritized his voice over her own, a skill that makes a map center around individual experience within a physical place. We were able to use this in our own StoryMap by continuously meeting with Hattie Whitehead and others working towards Linnentown’s redress. We used their feedback and suggestions to ensure that the story we were telling was helpful, accurate, and focused.
 
The point I want to make is that the work of people in GIS is important. It can inform people about issues that they were unaware of and inspire change based on their new knowledge. It can also provide evidence of reality to powerful people that have the resources to aid causes and fix problems. This is one of the first times that I have worked on a project with “real” data and the goal of being shared - the skills that I learned in classes prior to this only equipped me with technical skills. Community GIS requires the creator to be open-minded and adaptable. It is practical, it is effective, and it is real. It can back up the perspective of someone who may have gone a long time without it being taken seriously. In 2019, I went to the ESRI User Conference - an event hosted by the Environmental Systems Research Institute, a GIS company. They were launching a new campaign called “See What Others Can’t,” to promote the usefulness and potential of GIS. This phrase encompasses what I have learned in this class: when you can turn existing information into a compelling illustration, you are able to elicit worthwhile conversation and crucial change.
