---
title: "Get Lost"
date: "2022-05-06"
author: "Jared Grant, Student in Community GIS, Spring 2022"
---

By Jared Grant, Student in Community GIS, Spring 2022

Cynthia Lewis once said, “Getting lost teaches you how to read a map.” I resonated with this quote because in order to understand a map, you must create one by questioning the landscape. In essence, canvassing everything in an area helps you realize that you might be lost and helps you develop your reasoning to find a solution. There are many reasons to create a map: to seek direction, to seek perspective, or to seek information. You can even map for a cause. This quote is also interesting when you realize how canvassing or reading a map has evolved over time. Back in the day, people would have to canvas an area using stencils and paper to create a physical static map. Nowadays, we can canvas an area using mobile apps such as ESRI ArcGIS Field Maps that features an ever-changing map.
 
In my Community GIS course, we actually used Field Maps for a project with the Athens Anti-Discrimination Movement (AADM). The objective was to map out the businesses that had a sticker supporting their 2016 United Against Discrimination campaign. The campaign’s objective is to encourage business owners to stand in solidarity against discrimination regardless of race, gender, age, sexual orientation, or immigration status. As we started working on this project, we immediately realized there were many questions that arose when thinking how to map out the area such as “how many businesses are in downtown Athens?”, or “Do these businesses still have a sticker?”. We focused on answering these questions by using Field Maps to canvas downtown Athens. Using Field Maps, we divided downtown Athens into blocks. Every student was assigned a block of downtown Athens and had to ask all businesses in the block if they had an AADM sticker. We then verified and updated the attribute fields for each business point on the app. if the location did not appear on field maps, we had to create the point and fill in all information. The map (as shown below) was formatted so that points with a sticker were red and those without a sticker were black.

I really enjoyed working on this project because I had to learn how to create and read a map using Field Maps. We initially did not know how many businesses were located in downtown Athens but by using Field Maps, google sheets, OpenStreetMap and QGIS, we were able to answer all of our mapping questions. This project was efficient because at the click of a button we were able to update or customize the map as we walked around the blocks of downtown Athens. I also liked how Field Maps allowed multiple users to collaborate on a project. This means each student could focus on a specific block and spread the working load of the project.

Prior to canvassing my block, I expected there to be 3 businesses, but I was not 100% sure of the actual number. While canvassing, I found there were 8 businesses in my block. Ironically, I actually got lost while canvassing because I was near an area that I never ventured to and found businesses that I either never entered or didn’t know existed. While canvassing my block, I entered the Chase bank for the first time. I’ve always driven past it, but I never had a reason to enter before working on this project. I also didn’t realize that next to the bank was building that offered community office spaces for small companies to work at.

Overall, the major lesson I learned from canvassing was that I gained a new enhanced perception of downtown Athens simply by getting lost. I have lived in Athens for five years and I had no idea the number of businesses that could be located in single block of downtown. Through canvassing, not only did I gain this enhanced perception, I also helped create a map for the AADM that can be used to help people know what business support the United Against Discrimination campaign. So after working on this project, I highly encourage every geographer to enjoy the map making process. Also, Field Maps is an excellent software for your map making needs if you would like to canvas an area at the convenience of your phone.
