---
title: "Reflecting on the Practices of Geographic Information Science"
date: "2023-05-05"
author: "Nathan Castro, Community GIS Student in Spring 2023"
---

By Nathan Castro, Community GIS Student in Spring 2023Beginning my college career I decided to choose geography as my major simply because of the fact that I enjoyed Earth and atmospheric sciences, not knowing what else was waiting to be uncovered. Passing through my freshman and sophomore years at school I was pleased to dig into the material and content I have known and heard about since high school: tectonic plates, geology, weather systems. It wasn't until my spring semester of sophomore year that I decided to take my first course in geographic information science (GIS). I have heard about what GIS was briefly before but did not truly understand the magnitude of its implications. Growing up in my hometown, some of my friend’s parents were GIS analysts so I knew the study was something practicable and enjoyable. Taking that first class, I was hooked on the content, combining my interests of computers and geography! I felt as if I gained a lot of new knowledge out of that intro to GIS course as our professor shared with us his point of view on not only the various programs but also his real life experiences. I remember being told that GIS is an extremely versatile skill that could be paired and applied to practically any discipline. This at first shocked and excited me since up until then, most of the work we had been doing were tutorials in ArcGIS Pro on how to utilize the program’s features. I had far off ideas of what I could personally use GIS for but still felt a disconnect of what meaningful work could really be done.
Fast forward to the Spring semester of 2023, I am currently enrolled in the Community GIS Service Learning Course at the University of Georgia. I will be honest, during the registration period, I did not know what a service learning course was or what to expect from one. I had assumed that we would be learning more about using ArcGIS or QGIS but with more emphasis on community problems like traffic or resource management. I would soon come to realize what a service learning course entailed: learning and gaining real world experience and reflecting on those after having performed services to a community. This was not going to be a course of rote learning functions on a computer, this was going to be applying all of the skills I have accumulated over the years to help Athens residents and I was very excited to finally be of use to the community. 
The community GIS course this semester had been split into two major projects. The first taking the time span of the beginning of the year up until the beginning of March was our work with the Brooklyn Cemetery here in Athens, GA. Many people might not know too much about or even recognize the name of this cemetery as it had been abandoned and unkept for many years, but this place is of great importance to the Athens community as it holds many African-American ancestors of the present generation. Our professor had gotten a hold of the founder of the Friends of Brooklyn Cemetery organization, Mrs Linda Davis, to come talk to our class about the history and importance of the cemetery. This was an eye-opening experience hearing Mrs Davis speak about her connection to the space as a site of remembrance to the community but also herself personally. She herself is so passionate about maintaining and improving the cemetery that if our class could only do enough to assist her in her endeavors, then it would be a very rewarding experience and a success for the class in my eyes. Realizing that GIS could improve Athens changed my view of myself from a student, to a GIS analyst. 
The class was split into groups to tackle multiple tasks to benefit Brooklyn Cemetery. Some groups were asked to produce new maps of the cemetery grounds, others were in charge of cleaning and organizing data retrieved regarding grave markers, my group was set to produce brand new section markers to post around the cemetery. I was very pleased with this assignment as I could instantly see the value being brought to the community. New section markers would allow for better organization and ease of navigation around the grounds, not only for visitors but also volunteers working to improve the space on community work days. During this process I was able to really get my hands involved in multiple avenues. First we visited the cemetery to inspect the previous markers that had rotten and fallen off their posts to gain an idea of what purpose they served, how many replacements were needed and where they would be placed. Secondly we had the opportunity to create a new design for the markers that could provide visuals and even more information about the cemetery. This was a fun challenge for me since I have not had much experience with graphic design. My team got together and created various mock-ups with different design softwares until we decided on one. Lastly we crafted the signs out of plywood using the UGA Makerspace, a campus resource that provided us access to their laser-cutter and engraver. 
The final products are something I am proud of as they are a summation of all the various skills I have learned within my time with GIS. This service learning course has been very beneficial to my group working skills as well. Organizing group member’s time and efforts to efficiently get through this assignment has been a challenge but has taught me that the real world is not always so simply laid out. New skills like working with photoshop or a laser engraver have been exciting to learn but I really value the opportunity I had to learn community skills. Managing information between myself, group members and Athens has shown me what GIS can be when implemented with multiple people in mind. Finally seeing in person the impacts GIS can have on the community, I feel like I now have my own instance of providing something valuable through GIS which I wanted since my first intro GIS course.
