---
title: "The 'Community' in Community GIS"
date: "2023-05-06"
author: "Maya Rao, Community GIS student in Spring 2023"
---

By Maya Rao, Community GIS student in Spring 2023Earlier this year, I had a conversion with Dr. Jerry Shannon (my advisor, the professor of Community GIS, and director of the Community Mapping Lab) about project ideas for my Master’s thesis. As I spoke about wanting to do a community-based project, Dr. Shannon asked me “What do you mean by community?” This simple question made me start to think more about the heterogeneity of communities. As the field of community geography evolves, it is important to not equate the word “community” as always the same group of people.

When I pictured the word “community” prior to this class, my mental image was of individuals belonging to some kind of shared identity. I did not think of community as including organisations or an amalgamation of different groups and positionalities. Additionally, I failed to recognise how a person can be a part of interacting communities. My approach to the idea of community was extremely narrow, and I have been working to broaden my understanding of this term through the projects in Community GIS.
 
Community GIS
Currently I am a student in Community GIS, a class where we learn how to use GIS in community-based projects. In this class, we are working on two projects - first partnering with the Brooklyn Cemetery (a historic black cemetery in Athens, GA) and second looking at eviction in Athens. However, we have also spent time looking at the disciplines of Community GIS, Public/Participatory GIS (P/PGIS), Participatory Action Research (PAR), and community-based projects. Scholars differentiate these fields into their subcategories, but the idea of community still remains a central tenet. Although researchers from the articles we have read discuss the communities they have worked with, few detail a description of who makes up a community.
In our class, we are working with two different communities. What is the community we are talking about these projects?
Brooklyn Cemetery Project
Our first Community GIS project this semester was with Brooklyn Cemetery. This cemetery started housing graves in 1882, making it a final resting place for some former slaves in Athens. This place is full of history, and yet it is not given the public stature that similar historic white cemeteries have in the city. Brooklyn Cemetery has several unmarked and sunken graves. Of the graves that are marked, some markers have fallen over or are no longer visible.

For this class, we wanted to make Brooklyn Cemetery and the graves visible. By mapping the graves at Brooklyn Cemetery, we are making a conscious effort to think of these graves as permanent resting places of those marginalized in the past. Our work for the cemetery included making a physical and digital map of visible graves at Brooklyn Cemetery. We also created section markers for the cemetery to better understand how to locate the graves.

So who is the community here? We are a community of student-researchers from various backgrounds approaching this project. But who is it that we are helping? Our primary contact for this project was Ms. Linda Davis, the president of the Brooklyn Cemetery Society. Ms. Davis was a great partner to have due to her love for Brooklyn Cemetery and her dedication to preserve and upkeep the space. She provided us with ideas and feedback about our project. She was always appreciative and happy with the work that we completed. As a trustee of the Brooklyn Cemetery, she spoke about things that would help the cemetery and ways for us to assist with their vision. However, we didn’t meet with other members of the board of trustees of the cemetery until the end of the project, which limited our ability to interact with more people comprising the community.
The question arises then if this was truly a community based project. One of our class goals was to support not only the trustees of the cemetery, but also the descendants of those buried at Brooklyn Cemetery. Since we only spoke with Ms. Davis for the majority of this project, did we put too much focus on her as the sole representative of the cemetery? Or was this the best thing to do because of the obligations that other people who represent the community have (work, school, etc.).

Fitting with discussions we had earlier this semester in class, we discussed how doing community projects is a balance between the researchers and the community. We recognise that as students, we have more time to dedicate to this project compared our community partners. Forcing the other trustees to participate in more of this project may have been inappropriate and contractual. Doing this project made me understand that the rosy idea that UGA students and Brooklyn Cemetery have constant dialogue with each other is not the only way to do a community-based project. We provided deliverables (the maps and data) that the board of trustees of the cemetery were happy with. And, ultimately, this project is the first step in a long term relationship between the UGA Community Mapping Lab and Brooklyn Cemetery. We worked to establish trust and sow the foundations of future collaborations.
Eviction
In the second half of this class, we are working with the Athens Housing Advocacy Team (AHAT) to clean up data detailing evictions in Athens-Clarke County. We haven’t gotten too far into the project as of now, but our current goal is to clean and validate the data collected by undergraduate researchers and AHAT.

Through engaging with this project, I am better understanding the complex “community” we are working with. We have three members of AHAT either in or attending our classes, including one of the founders of the organization. AHAT is the group that we have been in correspondence with, but I question if our community with this organization or with the evicted tenants? If our work is with people facing eviction, what does it mean for us to be working through this middle organization?
Prior to this class, I may not have considered working with AHAT a community project, since we aren’t interacting with those directly facing eviction. Earlier in the semester, we read a piece about the Anti-Eviction Mapping Project in San Francisco. This is a project that I can clearly see the community angle, since the researchers are working, organizing, and mapping with people facing eviction in San Franscico. However, for the project that we are doing in this class, working with AHAT may be the best way for us to facilitate a community partnership. Our class has about twenty people (most if not all of whom are not currently facing eviction), so it may have been misguided if we were having conversations with evicted (or precariously housed) people. It may have created a dynamic and hierarchy between us as researchers and our community partners. Working with AHAT allows our class to still provide assistance to this project which will help illuminate the eviction problem in Athens.

I’m still struggling with the idea of a community not including evicted people in this project, but I can see how we are indirectly connected through AHAT. However, since we are still new to this project at this point in the semester, I am aware that my ideas may change as we move further in this project.
Overall Reflections
This class has helped me understand how the communities included in Community GIS are not amorphous and homogeneous. Additionally, the idea of “community” should not be imposed directly by the researcher, because the context of each project will necessitate different relationships between the researcher and the community. This is particularly important to acknowledge in our predominantly white group of students who are not facing eviction. In our class, I’ve had to wrestle with these ideas of who is included in our ideas of community and consider this word in a new setting. So, my original question of who is our community in Community GIS is more challenging than I originally thought. The communities we are working with are multifaceted groups of visible and non-visible members.
