---
title: "Reflection on the importance of community GIS as an Indigenous scholar"
date: "2023-05-05"
author: "Maya Henderson, Community GIS student in Spring 2023"
---

By Maya Henderson, Community GIS student in Spring 2023

My driving goal is to be of service to my community, Native nation, and broader Indian Country. Sometimes, however, I struggle to see how obtaining my PhD in Geography so far from home and at a university with limited support for Indigenous students is helping me achieve that foundational goal. I often find myself in this headspace when my coursework and tasks as a PhD student aren’t aligning with my areas of interest and values as a Seneca-Cayuga person and scholar. This semester Community GIS has helped me to recenter me, reminding me why the skills, tools, and knowledge I am obtaining here in Geography at UGA are still in line with my driving goal. I say this for two reasons, the skill sets I am gaining through the course and the involvement and direct aid to the local community. 

Community engaged scholarship and GIS are skill sets that I can directly employ to be of service to my community. These methodological and technical mapping skills are highly sought after and needed by Native communities and nations. Spatial analysis and more specifically GIS are becoming increasingly used by Native nations for projects including but not limited to land use planning, environmental and sustainability projects, and jurisdiction and political purposes. Since Native nations and communities are employing spatial analysis for community and nation-building projects this has also led to outside partnerships. This often means working with non-Native partners, a reality that although can be fruitful, can also add to the precarity of the Native nation and community. I see Community GIS as allowing me to craft the skills needed to be a Native academic partner for Indian Country.

One key reason for precarity concerns when working with non-Native partners is the data required on Native nations and communities for spatial analysis projects. Here the principles of Indigenous data sovereignty and trust become key. Data collection and analysis has always existed within Indigenous communities but data collection and open data under the settler colonial structure in which we live can increase rather than decrease Indigenous precarity. By this I mean that while data can aid Native nation’s sovereignty and goals it also “sits at the nexus of current and historic data challenges as a result of colonisation, bias, and a lack of knowledge of Indigenous rights” (Rainie et al. 2019). It is for this reason that I, as an Indigenous person who is part of Indian Country and accountable to my people, wants to develop these community GIS skills. Our nations and communities can and do benefit from spatial data and its analysis but because of its precarious potential, keeping Indigenous data in Indigenous hands is equally important.

Although the Community GIS course has not touched on the idea of data sovereignty explicitly, there has been an iterative process of reflection and intentional decision-making regarding the data we obtain, clean, use, and store. One keyway that I have seen the tenant of data sovereignty in the course is through discussion of data access, storage, and ownership. For one project regarding the historic Black cemetery in Athens, GA we discussed at length where the data should be stored and who could host and gain permanent access. After reviewing accessibility and stability concerns, we decided upon google drive with the community mapping lab rather than a single person hosting the data and permanent access shared with the board members of the cemetery. Carefully considering accessibility, location of data, digital access, and more are essential steps and principles of data sovereignty in the context of community engagement, and I consider them necessary skills, just like those of geocoding and physical map creation. Engaging in these discussions allowed me to draw on what I know of Indigenous data sovereignty and begin to see how data sovereignty tenants can be applied more broadly in community projects.

In addition to teaching me necessary skills, Community GIS allowed me to become more grounded in the local community and space where I am living as a guest while I obtain my PhD. Although I aim to always be accountable to my community back home and Indian Country overall, my protocol and teachings as a Seneca-Cayuga woman remind me of my responsibility to be a good guest. By this I mean that I am responsible to and for those around me. Being a PhD student means that I am constantly overscheduled, and it can become hard to find time to engage in community efforts outside the academy. Therefore, Dr. Shannon’s Community GIS course is uniquely situated to aid students, undergraduate and graduate, in becoming more grounded in Athens. The course teaches us about the historical-present of Athens, GA and allows us to meet community members and organizers that we likely wouldn’t otherwise through the various projects we work on in class. For example, working on the eviction mapping project we got to speak with former County Commissioners, City of Athens GIS employees, and engage with representatives of community groups like the Athens Housing Advocacy Team. In doing this we learned more about how the local government operates, the housing landscape of Athens, and what can be done using GIS to aid the community.
 
One project that taught technical and community geography skills alongside place-based histories and present was the Brooklyn Cemetery Project. Working with members of the Black community in Athens on restoring and mapping their cemetery, Brooklyn Cemetery, was particularly impactful for me in regard to engaging my traditional protocol in the Athens context. As an Indigenous person, I am taught deep reverence for our ancestors and the sacredness of their burial grounds. Therefore, it was particularly meaningful for me to be able to aid the Black community here in Athens in mapping their cemetery. The most powerful moment of that project was being able to locate one community member's grandparents in the cemetery using the searchable web map created in the class. Although I am not part of that community and those buried in Brooklyn Cemetery are not my ancestors, I was doing right by my people here in Georgia by aiding the local community in this way.
 
Reflecting on the Community GIS course has helped me recenter my purpose here at UGA. It reminded me that obtaining my PhD is allowing me to create and sharpen many tools that my Native nation and broader Indian Country need and want for our people to have for ourselves. The projects we’ve engaged with this semester, like Brooklyn Cemetery and eviction mapping, have also reinforced the ways that I can be accountable to my people while being far from home.
 
Citations
Rainie, S. C., Kukutai, T., Walter, M., Figueroa-Rodriguez, O. L., Walker, J., & Axelsson, P. (1970, January 1). Issues in open data. Indigenous Data Sovereignty. Retrieved April 30, 2023, from https://www.stateofopendata.od4d.net/chapters/issues/indigenous-data.html
