---
title: "Community GIS from the Prospective of an Archaeology Student"
date: "2023-05-06"
author: "Reyd Mahan, Community GIS student in Spring 2023"
---

By Reyd Mahan, Community GIS student in Spring 2023

Mapping and Geographic Informational Systems (GIS) have always interested me because they have significant practical use for me as an archaeologist. However, before taking this Community GIS class, I saw GIS as checking a box for my career. I never really thought about the applications of GIS outside of what I needed to do for class or work. As an archaeologist, I typically use GIS to create basic maps of an archaeological site and overlay different forms of data on top of it, such as artifact density or ground penetrating radar (GPR). While these maps are helpful for archaeologists to find where artifacts might be, the public will never see these maps or even know where the archaeological site is located to prevent looting. GIS in archaeology is private and not typically community oriented. Since I started working on the community-based projects for this class, I have gained a new appreciation for the positive impacts GIS can have in local communities that I never thought possible before.

I engaged with Community GIS because it allowed me to gain valuable, practical skills and improve soft skills in working with others while also improving the local community through various projects. The first project I worked on was at Brooklyn Cemetery. Brooklyn Cemetery is a historically black cemetery important to the local Athens community. Unfortunately, several graves were damaged over time or lost their marker entirely. Our job as a class was to record the points of each marked grave along with the grave’s information and then create a map that would be useful to cemetery visitors. During the project, we made trips to the cemetery to determine the accuracy of the data we already had from previous projects. Visiting helped me connect with the project by seeing the graves I recorded in person. It gave my work more meaning because I saw its impact in person, not in a spreadsheet. I saw my work as helping to preserve the memory of the people buried there. By recording the location of each grave, descendants can utilize the map to pay their respects for years to come, and we can dignify the deceased by recognizing their burial location.

The project also presented some challenges along the way. After we visited the cemetery, we realized that much of the data concerning the location of each grave was inaccurate. On top of that, the GPS on our phones was not the most accurate in recording our active location. To update the data, we went back and personally recorded each point that we could find at the cemetery to make a new accurate point layer that could be used in the final map. The GPS issue was annoying but tolerable since we needed the points around the grave, and pinpoint accuracy was not required to make a helpful map. Much of the project was devoted to sorting our recorded data and correcting discrepancies or duplicates. I’m beginning to understand that much GIS work involves spreadsheets and data management, which is necessary but also tedious.

By working with the Brooklyn Cemetery directly, this project showed me that my GIS skills could be used to make positive community impacts and not just for private research-related use. I saw the people I was helping directly, giving my work a purpose. Work in archaeology is far from purposeless, but there are not typically people that are a direct connection to your work unless you are working in consultation or collaboration with indigenous communities. Furthermore, to ensure the protection of an archaeological site, all maps and data concerning the site are private and only accessible to professional archaeologists, which was the antithesis of what we were doing at Brooklyn Cemetery. We wanted the maps and data we made of the cemetery open to the local community so they could be best used. I hadn’t worked with GIS and mapping in a public way before, so it was amazing to see how our work as a class could directly help community members.

As of writing this post, we are getting into our second-semester project with the Athens Housing Advocacy Team (AHAT) to better identify and map housing evictions in Athens, GA. While the previous project utilized GIS through community service, the AHAT project focuses on using GIS for social change and advocacy. I am interested in seeing the maps we create at the end of the project that visualize the eviction problems in Athens. This class has shown me how public GIS can benefit the local community, which differs from the typically private GIS utilized in archaeology. More importantly, it has taught me skills that help build stronger community connections that I can use for the rest of my life.
