---
title: "Producing Landlord Maps and Countermapping Evictions"
date: "2023-05-05"
author: "Margaret Hersey, Community GIS student Spring 2023"
---

By Margaret Hersey, Community GIS student Spring 2023The Community GIS course functions similarly to other GIS courses by strengthening students’ technical skills in popular software such as ArcGIS Pro, QGis, and ArcGIS online. However, the scope extends far beyond the glowing monitors and classroom walls. During this course students are given the rare opportunity to step out of the classroom and collaborate in meaningful and equitable partnerships for community-based research. Our course instructor (Dr.Shannon) provides students with theoretical frameworks that illustrate the context in which we work with the community and enable us to work collaboratively and meaningfully towards community empowerment. Topics include Critical GIS, situated mapping, community geography, and counter-mapping. This semester we focused on two projects, each involving members of the Athens-Clarke county community.

For the second half of the semester, our class worked with the Athen’s Housing Advocacy Team (AHAT), whose goal is to empower the tenants of Athens-Clarke county to fight for housing justice by providing access to information and resources. Rather than simply documenting evictions, they actively challenge inequalities and the processes that produce them, leveraging maps to draw attention to and alter public perception of evictions within Athens, Georgia. AHAT team members spoke with our class and shared their experiences working with Athen-Clarke County tenants. Their willingness to share these experiences allowed us to gain new perspectives of social and spatial inequalities within Athens that an ‘objective’ map alone could not.

We learned that AHAT emerged shortly after the COVID-19 pandemic, following mass evictions of immigrant communities within Athens-Clarke County. Three years later, in 2023, many community members are still dealing with financial instability and economic hardships caused by the pandemic–now, without the protection of the CDC’s eviction moratorium (An order that allowed additional time for rent relief and prevented persons from being evicted from their homes). In addition to COVID, the county has faced increased housing demands due to an influx of students enrolling in the town's local college, the University of Georgia. The university has, on average since 2014, admitted 625 additional students per year– and doesn’t show signs of slowing anytime soon. Despite this, the university has only built one dormitory since 2014– causing many students to seek housing off-campus and compete for homes with permanent residents. The community has seen drastic rent increases followed by the displacement of community members who cannot accommodate the rising prices.

In recent years real estate companies have responded to this growing student market. One of these companies– Prosperity Capital Partners, purchased hundreds of working-class units in lower-income areas of Athens-Clarke County to renovate and sell at a higher price point. In some cases, they increased rent by as much as 93%. Many residents also received a 30-day notice to vacate their properties– a violation of Georgia law. Breaches like these are not uncommon in eviction cases, and AHAT aims to identify those violations and equip tenants to handle them through resources like their eviction defense manual. The eviction manual is designed to inform tenants of their rights and gives a brief walk-through of the eviction process.

Our Community GIS class worked together to identify what questions we could answer with the data we had. From there, we decided which of those questions were the most relevant, helpful, and feasible. Feasibility was a factor since we had only two weeks to work on the projects. Each group was then given a topic that focused on either landlords, tenants, or the Athens Eviction Prevention Program. One group mapped how housing stress affected eviction patterns, while another worked on determining the cause behind most evictions and the average eviction timeline in Athens. My group examined the distribution of landlords at local and global scales, choosing to map the locations of landlords who own the most properties and landlords with the highest number of evictions.

First, we filtered the Athens-Clarke County parcel zoning data to find parcels in residential zones without homestead exemptions. To be granted a homestead exemption, a person must occupy the home, which is considered their legal residence. So parcels without homestead exemptions were considered rental properties. For each remaining parcel, we obtained the owner's address and the number of properties they owned in Athens, Georgia. We then joined this dataset to our ArcGIS project and geocoded all owner addresses. We used a visualization technique referenced by Taylor Shelton in his article, “Situated Mapping: Visualizing Urban Inequality Between the God Trick and Strategic Positivism.” Using flow maps, Shelton mapped the relational geographies of vacant and abandoned properties in Louisville, Kentucky. We used flow mapping and proportional symbology to visualize the connection between landlord and tenant locations. Understanding the distribution of landlords can provide insight into housing and help inform decisions for zoning, housing policies, and rent control. It can also provide a source for future researchers to draw from.
