---
title: "Covid-19 Eviction crisis – Rent and Evictions on the Rise"
date: "2023-01-02"
author: "Dy'Amond Mcghee, CML CURO student"
---

By Dy'Amond Mcghee, CML CURO student

The COVID-19 pandemic has increased the number of people at risk for eviction. Since January 2021, Georgia’s rent prices have increased by 22% per year, making Georgia the sixth highest rent increase in the U.S (United States) [1]. In Athens-Clarke County, we believe that there is inadequate data on the number of evictions that have occurred during the COVID-19 pandemic. The number of evictions in Athens-Clarke County is estimated to be higher than people would believe due to the COVID-19 pandemic. With no eviction data collection or research, a lot of residents cannot take advantage of several COVID-19 emergency relief rental assistance programs. If we can prove that there is a large number of people being evicted in the Athens-Clarke County area, then more people could get rental assistance and help from government programs.

The Community Mapping Lab is currently working with community-based partners such as the Athens-Clarke County Magistrate court, to collect and visualize important data on the progression of evictions and levels of housing insecurity in Athens. While working with the Magistrate court we are able to go to the Magistrate court office once a week and scan up to 50 ACC eviction files per week. With this data we will be able to enter specific information from the file into a spreadsheet and an ArcGIS dashboard to see where and why people in ACC are getting evicted. Are people getting evicted for rent increases, loss of a job, or waiting on the GRA program?

For scanning the eviction files at the courthouse, we used the CZUR Shine Pro scanner. The scanner attaches to a laptop with a USB cord and has a foot petal attached to the scanner. This instant scanner allows us to scan an average completed eviction file in minutes. After scanning the eviction files, we enter the necessary data into a spreadsheet. The spreadsheet includes the case number, the property owner, the tenant's name, code name, the date the case was filed, and the result of the case. We take the data for each case in the spreadsheet, and then enter more data into the ArcGIS dashboard. ArcGIS is a cloud-based mapping software that allows us to make maps, analyze data, and share our findings. Some additional information that we input in the ArcGIS dashboard is a code name for the tenant, the location of the rental property, the reason for the eviction case, the action taken by the tenant, the court date of the case, and the results of the case.

Over the last ten weeks of working with the Athens Eviction Mapping project, I have found several interesting trends on evictions in ACC. First, the majority of the cases that were filled from January 2022 - February 2022 did not have an end result, meaning that we are unable to know if the tenant was officially evicted or if the voluntary vacated the premises. The second trend I found was that tenants that applied for the GRA program were sent a warrant to be evicted from their unit within a month or two of nonpayment. I realized that the GRA program is taking a long time to get back to tenants and rental properties on if they will grant assistance to a tenant or not. Lastly, I have seen a trend that people that were evicted in the beginning of 2021 were typically evicted from the same few apartment properties. If we continue with this eviction mapping project, we could find out why people are being eviction so much from these several apartments and try to get these tenants more help. The data that we have collected so far concludes that Athens-Clarke County does have a high eviction rate and that citizens here do indeed need funding for rental assistance from the State.
 
 
References:
[1] Raymond, Jonathan. 2021. “Rent Increases in Georgia This Year Were Sixth-Highest in the Country, According to Study.” 11Alive.
