---
title: "Empathy and Community Research"
date: "2023-03-03"
author: "Kayla McCartney, Community GIS student in Spring 2023"
---

By Kayla McCartney, Community GIS student in Spring 2023

At the start of the semester, my class begun a collaborative mapping project with the Brooklyn Cemetery. The Brooklyn Cemetery is one of the first African American cemeteries in Athens, GA. From my cursory observation, there seem to be two major kinds of cemeteries. The first kind is the one that remembers and celebrates the people who are buried there. The second kind is the one that people are buried in and forgotten about. Out of sight, out of mind. The Brooklyn Cemetery is an unobtrusive place that would become the second type of cemetery if it weren’t for a few select people fighting for its visibility such as Linda Davis. The purpose of this project was to take all existing data regarding the cemetery and combine and add to them to create a sustainable, informative, and accessible map for those interested in the cemetery.

Like many UGA students, I am not from Athens. I am not familiar with the history or layout of much of Athens. Before this project, I had never seen the Brooklyn Cemetery, heard of it, or even driven by it. I had no connection to the Brooklyn Cemetery. So, at the beginning of the project, I approached it like any other assignment: understand what needs to be done, then do it. However, it might be important to understand that while this is a geography class, I am a landscape architecture major, and I approach community engagement projects like a landscape architecture major. A lot of my experience with projects like these has been mostly in the realm of theoretical, and for the few projects actual communities were involved in, they said what they wanted then were majorly hands-off afterwards, somewhat similarly to this project. Something particularly relevant to me that I’ve learned by working more closely with a place like the Brooklyn Cemetery is a better understanding of the attachment to place in people regarding a place I am unattached to.

Linda Davis is the most visible advocate for the revival and maintenance of the Brooklyn Cemetery as a historical place. She came and spoke to our class about the cemetery’s historical and emotional significance. As it was established in 1880, only 15 years after slavery was abolished, it was likely many freed people had been buried there. Moreover, there was also a high likelihood her own ancestors were also buried there, which she explained as her strong personal connection. She then expressed to us how strongly she felt about the impact having access to their history and where they came from would have on future generations.

These things were significant and perhaps slightly confusing to me because they were things I don’t usually think about. My grandmothers on both sides of my family are Asian immigrants, and in coming to America, they more or less left their roots behind them. Both of my grandfathers have longer histories in the US, however maybe being veterans and not being as close to external living family members has made the history of how we got to this point less important to research or talk about. In my family, there is a much stronger emotional connection to family now than family gone, hence why Linda’s different emotional priorities felt very significant to me.

After she spoke to us, my perspective changed. Before, I had no attachment to the Brooklyn Cemetery, and I wouldn’t have necessarily called it important to me. However, after I was able to see how important this place was to Linda and how her connection to her family and roots felt mirrored to my connection to living family, I was able to develop a sense of empathy for this place through Linda’s attachment to the cemetery. More than that, I realized it was important to her. My mind then circled around to the idea that while importance is a relative concept, if looked at objectively, isn’t it universal? I can then start to think, because the Brooklyn Cemetery is important to her, it is important to me.

While I don’t know if this revelation truly changes how I approach this particular project, I believe that this kind of awareness of where my values end and another’s begin (how they relate and how to blur the lines) can be greatly impactful for future projects. It is the kind of thing that affects communication, understanding, and empathy which then affect how the project framework develops. When working on community projects, it can be easy to get stuck in the big picture headspace where you have a certain set of priorities and values. It’s easy to think in terms of “What is worth putting time into?”, “What will have the most impact?”, or “How can I best improve [this place] for [specific goals]?”. It’s easy to forget the about the people the change is for. It doesn’t help that many of my projects as a landscape architecture major has us working on community projects with limited if any contact with said communities. In building the world, it shouldn’t be so easy to forget who you are building it for.

What I’ve learned from the Brooklyn Cemetery project is that empathy is important. I’ve learned that when approaching projects, I need to come with my ego pre-dismantled. Because at the end of the day, I am not making design or planning decisions for myself. I am making places for people. People cannot be separated from place. So, when making a place, the first question I will ask from now on is who are these people, and what is important to them?
