---
title: "Reflections on Collaborative Design Processes"
date: "2023-04-18"
author: "Casey Serrano, student in Community GIS Spring 2023"
---

By Casey Serrano, student in Community GIS Spring 2023

This past week I finished laser-cutting and engraving the section markers part of our class designed to be placed at path intersections in Brooklyn Cemetery, a historically Black cemetery in Athens that was started in the aftermath of the Civil War to provide a respectful final resting place to Black Athenians. Unfortunately, the cemetery was abandoned for decades, and it has takenthe work of several trustees, most notably Linda Davis, to restore the Cemetery from an overgrown state. The Brooklyn Cemetery did have wooden section markers, but they were old and many had fallen off of the trees they were nailed to. With our class’ maps, my connection to the Shirley Mathis McBay Library Makerspace as a student worker, and funds from the Geography department, it was very easy for our group to create new markers for the Cemetery, and in a matter of weeks there will be markers with maps of the Cemetery that are sealed and stake in the ground so that visitors can navigate more easily. The Makerspace is open to any UGA-affiliated patrons of the library for free, and UGA students or staff could revisit this project to replace or update the section markers in the future. I want to use this blog as a place to explain the process of making the signage in detail, and provide some insight into how the process could be improved for the next round of markers.

At the most basic level, making these markers was fairly simple since all we really needed to do was design them, break the design into cut, engrave, and stroke files, use the laser cutter, seal the signs, attach them to signposts, and drive them into the ground. The Makerspace offers classes on laser cutting that are sufficient to prepare a group to use the cutter, and the sealing and implementation of the signs is not a very difficult process. As long as future groups do not want to re-do the signs and their design, the files for creating new ones are available in the Google Drive from this class and can be reused. With some support from the Makerspace, this is a project that any UGA affiliated group, even one not comfortable with mapping, could do.

The most difficult part for future groups that are interested in re-doing the signs will probably be the design process. Designing new signs to reflect updated sections, a desire for more information, or to use a different material would be simple, but creating a design that is compatible with the Makerspace’s lasercutter is more difficult. For the signs to be as legible as possible, it is best to engrave the design and then use the score setting to add extra deep and dark lines around the outside of the engraving. Scoring can be used for many things, but for this project it is functionally an outline. Due to technical limitations of our lasercutter’s software, the engraved image must be stored as a raster png file, but the score image must be stored as a vector svg. This is due to the way the machine processes different kinds of images to guide it to either laser larger areas for engraving or very precise lines for cutting and scoring. For a project like this that necessitates creating many similar files with just a few elements changed, it is also important to use one template so that all of the section markers look uniform and the scoring outlines perfectly match the engraving. For our project, we created the original template as a psd (Adobe Photoshop) file, which had some advantages as we were able to use the many design tools available in Photoshop. However, what I realized when I began trying to cut the designs was that the psd files were exporting missing elements when exported to svg files because not all of the elements in the Photoshop canvas were actually vector objects. Photoshop is primarily a raster environment while Inkscape (link here) is primarily a vector environment. This meant that I had to convert all of the elements to vector objects and recreate the design in Inkscape in order to create an editable template that could export well to pngs and to svgs. I would advise future designers to create all of their designs in InkScape or another vector environment from the beginning.

Another potential consideration for future groups would be sign material. For budgeting reasons, our group decided to use ¼” Birch plywood that we will treat to be weather resistant. However, there are other, potentially more durable materials that can be put through the laser cutter. Acrylic and anodized aluminum are both materials that can be used in the laser cutter, and with more budget would make good candidates for signage that will not age as poorly as wood.

A final consideration for future groups would be to collaborate more with the Brooklyn Cemetery trustees and community. Due to the short time frame of our class, it was not possible for us to work in concert with community members, but I think given more time this would have been a great opportunity to invite local artists to collaborate with us. The cemetery has iron gates, created by a local artist, that depict scenes symbolizing themes of knowledge, religion, and life. I think a project that integrates design elements of the gates into the section markers would be a good option for a future group.
