---
title: "A Different GIS Path"
date: "2023-04-18"
author: "Lan Nguyen, student in Community GIS, Spring 2023"
---

By Lan Nguyen, student in Community GIS, Spring 2023

As my time at the university comes to a close, I’m reflecting on my experiences in GIS, even though self-reflection is a generally difficult process for me. I began with an Introduction to GIS course at Georgia State University. After I had transferred to the University of Georgia, the next introductory course I enrolled in was Aerial Photographs and Image Interpretation. These courses taught two software programs: ArcGIS Pro and Google Earth. Through those programs, we applied direct step-by-step instructions with finite answers. Each student resulted with the same conclusion and final map, aside from some personal stylistic preferences. At the end of the semester, we would get into groups for a final project and presentation where we would receive little to no feedback and our classmates do not have enough interest to pay attention. We moved through both classes very similarly. It’s an overall average classroom experience, but I enjoyed the meticulous and intricate process of ArcGIS enough to continue toward a certificate.

Aerial Photography in Forestry, taught by Dr. Bettinger, and Community GIS, with Dr. Shannon, are the two last courses in GIS that will complete my certificate. Dr. Bettinger’s course turns the introductory Aerial Photographs and Image Interpretation course into a more specialized concept. I’ve learned practical concepts and interpretation skills that I never knew of before that follow along with US Forestry Service or National Park Service rules. These skills can interpret the difference between deciduous and evergreen forests, and takes another step further by identifying the possible species of the trees based on the regions the images were taken. He manages to capture the class's attention by sharing his own experiences when he was a student or intern for forestry companies. I appreciate these insights since I’m currently applying to internships myself for the next year. They often feel like a glimpse of what my career could look like, even though that’s the path I am unlikely to follow.

Dr. Shannon’s course follows a completely different route compared to all three of my other courses. His style and method of teaching are similar to mentorship or internships, except that it is for a class instead of a small group. It’s as if he’s the one that’s the passenger giving map directions and we are in the driver's seat doing the “work”. I want to say “work” in a light manner where we cannot take all the credit. Dr. Shannon is the head of the projects while we facilitate them. We take what we have learned through previous GIS classes, and we apply them here in our projects. During the week Dr. Shannon had to be out of town, I was surprised to find that the class followed the schedule as usual. We had students that took on to be class leaders in a way, we continued with fieldwork in our own times, and we never lost track of progress. If this was any other class, we would have had the class canceled or been assigned remote busy work. The amount of interest the class had for the Brooklyn Cemetery project was different from the other kinds of projects I had worked on in my previous GIS classes. I believe the fact that we had a strong, established, and local relationship with the founder Linda Davis encouraged us to keep working on the project.

I loved locally working with the Brooklyn Cemetery. There was a clear goal that we needed to get to even if it took awhile to get there because of the amount of data organization that was required. The metadata organization, at the beginning of the semester, was a concept I had heard of but never truly applied in practice before. In addition, I believe the use of ArcGIS Online, QGIS, and the fieldwork we did at Brooklyn Cemetery was beneficial to establish clear boundaries on a map for the cemetery. I prefer the application process that this class has allowed us to do. I love how this class is a culmination of what I had learned from my other courses into an operation. I can use everything I’ve ever learned for the Brooklyn Cemetery and anti-eviction projects, which is amazing since I’ll be graduating in a few weeks. I hope to apply what I’ve learned from this class to my near-future internship positions. This was a wonderful class to learn from, and I’m excited to see where it will take me on my journey with GIS.
