---
title: "Anti-Eviction Mapping and Community GIS"
date: "2023-05-05"
author: "Nick Taborsak, Community GIS student in Spring 2023"
---

By Nick Taborsak, Community GIS student in Spring 2023

Over the past several weeks, our Community GIS class has been hard at work researching various questions concerned with housing and evictions across the Athens community. Working in conjunction with the Athens Housing Advocacy Team (AHAT), the Athens-Clarke County Geospatial Office, and other community actors, our collective goal is to attain a deeper understanding of housing-related issues that plague our community. Our research questions include:

How can we categorize landlords based on the number of properties they own, eviction filings, and known outcomes? How do those three categories compare?
Where are landlords located nationally/globally?
Who participated in the EPP? Where were those properties located? What were the eviction outcomes?
What is the relationship between housing price, housing stress, and eviction patterns?
What is the eviction landscape?
 
Athens, historically categorized as a traditional “college town”, is home to over 120,000 permanent residents (not including the transitory student population) as well as a poverty rate upwards of 30% peracc.gov, nearly three times the national average. Additionally, the household median income in Athens is just over $38,000 annually, which represents approximately 54% of the national average. These statistics alone demonstrate the need for affordable housing across the county, something which is and has been severely lacking. The community is currently facing a shortage of affordable housing - a crisis - and the issue is perpetuated by the very nature of the city itself. The displacement of neighborhoods comprised predominantly by people of color at the hands of the university, such as Linnentown (seeUGA Community Mapping Lab), in favor of student housing developments, the prioritization of new housing developments for the much more affluent student and university demographic, and the failure of local policymakers to provide assistance for its most vulnerable of groups, are all influencing factors which have led to where things stand today.
 
With this being the current situation in Athens, our class has set out to find which landlords and property owners own the most rental properties across the county, and which are evicting the most. We’re also interested in precisely where these landlords are located - be it other parts of the country, world, or from within our community - to shed light upon the role inside/outside investors may play across the landscape of property management and displacement of evicted persons. Additionally, we’re researching which parties participated in the Eviction Prevention Program (EPP); specifically who received assistance, where they were located, and how this relates to the outcomes of those eviction filings. Our final area of focus is concerned with the relationship between housing price, housing stress, and patterns of eviction. Through these analyses, we hope to articulate how these processes tie back into the overall eviction landscape of Athens.
 
The spatiality of this project depicts the applicability that GIS has to work of this nature, as well as to the multitude of other community-based projects that geospatial analysis may contribute to. I’ve been part of the group tackling the categorization of landlords by number of properties owned, amount of eviction filings, and their known outcomes; we believe this to be an important topic to research so that we may establish a “spectrum” of which landlords are the most prominent of property owners in our communtiy, and whom most perpetuate the displacement of tenants via eviction filings. While we’ve used GIS platforms such as ArcGIS Pro as part of our analyses, our research has largely consisted of data cleaning and analysis amongst the datasets provided by AHAT and the ACC Geospatial Office. As part of this process, we’ve seen the complexity that is extrapolating meaningful data from various large sets of data and drawing substantive conclusions as a result of those analyses. One of the more interesting facets of this research has been seeing the multitude of operating names these landlords and property owners have as registered LLC/LTD’s, and establishing a standardized “umbrella” title for these ownership groups for the sake of our analysis has comprised a significant proportion of our research time. For example, one single entity may have separate operating names such as “Elite Realty”, “Elite Realty (Hallmark)”, and “Elite Realty Services”, all which represent the same ownership group in various capacities. Interestingly enough, this is done to insulate individual property owners from personal liability for their rental property, as well as so that if a lawsuit is filed pertaining to one of their properties, the rest of their properties will not be affected by the lawsuit, which effectively separates and protects each of the properties.
 
Practicing GIS in community-based settings as part of our class this semester has been an eye opening and enlightening experience for me personally. From our contributions to the Brooklyn Cemetery project to our work here with anti-eviction mapping, I’ve seen the role platforms such as Arc, QGIS, and R can play in work of this nature, and the applicability of many of my learned skills across GIScience in serving my immediate community. Geospatial analysis is oftentimes most needed by the most underserved and marginalized of groups, and it has been quite the holistic and fulfilling experience to take part in our work this semester. Through our efforts across this project and semester as a whole, we hope to leverage community-engaged work to promote a more inclusive and equitable community for all. Looking ahead, our class is most excited to share the results of our research with the community at the Athens-Clarke County Public Library on Friday, May 5th, 2023.
