---
title: "Collective Learning for Community Mapping"
date: "2023-05-05"
author: "Constanza Urresty Vargas, Community GIS student Spring 2023"
---

By Constanza Urresty Vargas, Community GIS student Spring 2023

Community GIS is a service-learning course in the Department of Geography at the University of Georgia, where students from different backgrounds and from different years (both undergrad and graduate) converge. This means that as students, we come to the course with diverse skills, knowledge, and interests; although we are all in the same class, we are not learning the same things or in the same ways.
During the semester we have engaged in two projects, contributing with GIS tools to local community organizations. The first was with the Friends of Brooklyn Cemetery, a local organization in Athens that works for restoring and rebuilding this cemetery, which is a resting place of former slaves. Their aim is to commemorate the individuals laid to rest there and bring their stories to the present. For the second project we have been working with the Athens Housing Advocacy Team (AHAT), a grassroots activist group that collaborates with renters and allies to fight for the right to affordable, healthy, dignified, stable housing as a human right.

Course activities have involved lectures, mapping, discussions, and sessions with several visitors talking about their experiences as researchers, practitioners, or organization members engaged in issues related to the projects. We also had various class discussions attempting to reflect on the purpose and meaning of our work as a class. What do we want to achieve in our projects? Why mapping? How are we contributing to community organizations through maps? Many of these discussions involved collective agreements about the goals of our work and how to address our questions.
So, this is a lot about “we” and “our”. Most of the course activities were collective, not individual. In my opinion, this is particularly meaningful, as many of us enrolled in this course because we think community is important. Community mapping processes need skills for working with, thinking with, and learning with others. Co-learning and knowledge co-production is what allows us to be co-producing maps.

As an international student in my first year in UGA and in the U.S., collectivity has been vital for my academic experience. Particularly in the Community GIS class, collectivity has been important for my learning process and for contributing to our projects. This is a community-engaged course, which means we are collaboratively working with local non-academic organizations or community members. Consequently, it requires an understanding of the context of these organizations/communities and learning about the problems they are facing.

Community GIS class at the Brooklyn Cemetery, in a meeting with Linda Davis (co-founder of Friends of Brooklyn Cemetery)
In the case of the Brooklyn Cemetery project, it was necessary to have some understanding about the history of both Athens ant the U.S.; it demanded familiarity with the past in this place, the role of slavery and how this shapes the present in diverse and complex ways. Furthermore, Athens eviction project requires understanding about the social context of housing access in the city, some basics about the housing and eviction legal framework in Georgia, and additionally understanding the nature of available data from local institutions and organizations. All these issues might seem simple, but they are not when you come from a different context, history, and culture. This means new administrative structures, specific concepts, and sometimes different worldviews and social problems. Even more so when you approach these issues not in your first language.

This can be complex and challenging, maybe unfeasible in a short time for international students, as we usually have lived a short time in the U.S. when starting a study program. In those conditions the course might be difficult, as it is highly contextual. However, rather than being an obstacle, all these issues become an interesting and meaningful learning process thanks to the collective. I’m not an individual foreign student navigating an incomprehensible context and struggling to complete the course work. I’m part of a collective, where different knowledges and skills contribute to a common project. Listening to others, being part of group discussions and asking many questions to my classmates is how I could gain some understanding about these issues and shed light on how local communities address their projects.

Collaborative and supportive relationships inside the classroom are what makes room for foreign students. It allows us to be part not only of the classroom community, but also the Athens community. This creates space for us, it opens the opportunity to learn from local communities and organizations, while contributing with our work. Sometimes we can also contribute with novel perspectives. coming from the amazement of observing and knowing a new place. While learning from other students about local context, as international student I can contribute with viewpoints as an outsider, which although has some drawbacks, it might be a “fresh” view, in some cases complemented with experiences from different contexts as well.

From this perspective the “co” prefix becomes applicable beyond community GIS. This means as a class, we are collaborating not only when creating maps with organizations outside academia (which is the key in this class), but also when doing collective work, co-learning, and co-producing knowledge inside the classroom.

Community mapping becomes an intertwining of relationships of collaboration occurring inside and outside the classroom. Community mapping is not only about mapping, but also about collective learning and knowledge co-production, where different skills, knowledge and ideas have a space.
