---
title: "Bringing Community Geography to the Environment"
date: "2023-05-05"
author: "Lilia Shorrock, Community GIS student Spring 2023"
---

By Lilia Shorrock, Community GIS student Spring 2023

My relation to geography has always been through the lens of the environment. I am studying ecology in school and took on the Certificate in Geographic Information Science here at UGA to add to my portfolio of hard skills. My advisor was the one to suggest it to me, as I had not heard of it before. When I started taking classes for it, they showed me how entrenched in my field of study GIS really was. I began to see the role of GIS everywhere. All of my classes use maps, aerial imagery, GPS tracking, and similar things to look at the climate, wildlife, vegetation, landforms, etc. Professional items like scientific journals and media for governmental organizations use the same. GIS is everywhere in the environmental sector, and so the environment is my basis for GIS.

In the spring of 2022, I became very interested in urban places, when I began to think about the effects of urban places on the environment. Where before I would spend my time reading about new river restoration projects or conservation of endangered species, I began to learn about the power of public spaces, street design, housing, and transportation poverty. I became very passionate about these things and my passion has only grown as time has passed. It was in these spaces that I saw how GIS was being used outside the environmental sector: maps used to designate municipal zoning, instead of burn units; aerial imagery used to show expansion of the built environment, rather than deforestation; transportation planning instead of trail guides; etc.

My new interests made their way into my schooling, and for this semester, I decided to take Community GIS. I did not know anyone who had taken the class before, so I was not exactly sure what it entailed, but it sounded like something I wanted to try. I wanted to have experience working with people in a community as a collective to solve a problem and to work on my own interpersonal, group project, and public speaking skills.

The class itself is about what I was expecting. We have had two community-based projects this semester, one working with the Brooklyn Cemetery and one working with local housing advocates on eviction. The Brooklyn Cemetery is a historic Black cemetery in Athens that we aided through GIS by locating graves and creating physical and online maps. We met with one of the trustees of the cemetery, and heard about its history, why she wanted to preserve it, and the types of things she wanted from us. In this project, I learned how to use Arc Online, use Field maps, and create a searchable webapp. I also gained a lot of experience in data cleaning and experience dividing work among a team based on skill and interest.

For the eviction project, we met with many different representatives to learn about eviction in Athens and the programs in place to help tenants. This project was more exploratory and data-focused. The outputs are not necessarily just for one community either; they can be used by many different groups, like the housing advocacy groups, tenants, and the government. In this project, I learned a lot about the subject of housing and eviction and more about the city I currently rent in. I cultivated more of my R skills, learning how to work with date and time data, how to create time series and graduated color bar graphs, and how to make csv files from data frames. On Friday, May 5th, we will have our public presentation event at the local library, where we will share our work. I have not done something like that, so I am excited.
 
The mechanical aspects of GIS could be applied to every area of geography. We also learned about the subject of Community Geography. I did not know this was a subject to be studied, even going into the class. There are many different methods and practices of community geography, specifically in how academics partner and work with communities to solve a geographic problem. The theoretical distinctions among the different practices are minimal, but they can have a big impact on the accessibility of the work. There is emphasis in the literature that an academic should work with the community, viewing them as a partner with equal but different knowledge and stake in the project, rather than viewing themselves in a “superior” position to the community. I think academia has a superiority complex built-in to the institution, so consciously thinking about this when going into work can help equalize the process. Learning about this showed me that geography and mapping is more than just the outputs–the process and the relationship between partners really matters.
 
So, how do I bring this knowledge and experience back into my chosen field? I believe there can be an intersection between the environment and community geography. Protecting the environment protects people, and there are many groups of people that rely on rural lands in order to make a living. The government has a long history of taking land from local people and establishing their own control without having local ecological knowledge or caring for the environmental health that would affect local peoples. I plan to work for the government, so using my experiences in this class, I feel more prepared taking into account the needs of the communities by working with them, rather than having the perspective that I am working for or against them. Community GIS is definitely more complex than the mechanical, environmental GIS I was used to going into the class.
