---
title: "Mapping Labor Geographies in the 1958 Athens Directory"
date: "2023-09-19"
---

In summer 2023, Jai and Peyton--two undergraduates at UGA--worked as research assistants in the lab through UGA's Center for Undergraduate Research Opportunities. They were contributing to our continuing project to digitize the1958 Athens city directory. This included both doing some data cleaning and also using the directory to profile two historic Black areas of the city:Linnentownand Hot Corner. More specifically, they used the employment information provided by the directory to map the labor geographies of these neighborhoods. For the residential neighborhood of Linnentown, this was documenting where residents worked. For the commercial district of Hot Corner, it was where they lived.

You can read more about this project in the storymaps Peyton and Jai created, linked below. We're glad they could spend the summer working in CML!
Where did Linnentown work? Peyton Gunn

Hot Corner, 1958, Jai Gonzales
