---
title: "Situated Mapping as a UGA Student"
date: "2023-05-05"
author: "Jai'anna Gonzales, Community GIS student in Spring 2023"
---

By Jai'anna Gonzales, Community GIS student in Spring 2023

I decided to take Community GIS for a few reasons. The first is to have the opportunity to work on a project where the data is not neat and prepared for you and has real-world implications. The second is to have more experience in community engaged work, particularly because I have an interest in urban planning. The third is because I knew about the work the Community Mapping Lab did with Linnentown and it opened my eyes to the power of mapping.

Situated mapping is a concept introduced to our class through a research article by Taylor Shelton, who came to speak to us about his paper this semester. It was an enlightening conversation about how we can approach mapping from a more complex viewpoint. In this paper, Shelton argues that we can “simultaneously use maps to prove that inequality exists…while also demonstrating that the ways we conventionally think about space through maps are not really sufficient to understand what is actually going on in the world” (Shelton, 2021). The world typically views maps as a quantitative and authoritative method of constructing knowledge. Being able to use GIS beyond these conventional goals and implementing more qualitative and subjective ways of mapping is a useful way to shift the ways we view the world around us, and this has certainly shifted the ways I think about GIS work.

For example, another article we read this semester was about anti-eviction mapping in San Francisco, where personal stories, community art, and subjectivity were incorporated into mapping efforts. Instead of simply mapping where evictions occurred, Manissa Maharawal, Erin McElroy, and community members worked to create maps and stories with the intention of making the marginalized visible and challenging the processes that forced people out their homes. These efforts were in direct service to community action and advocacy (Maharawal & McElroy, 2017). Instead of viewing mapping/ GIS as simply a means to an end for tracking an event or occurrence, I can now see how mapping for a specific situation or viewpoint can create maps for action instead of just knowledge. Maps that are about people, not datapoints. This is the framework we established before diving into our work with evictions in Athens.

The second half of this spring semester we have been working with eviction data collected by The Athens Housing Advocacy Team, AHAT. We spent the first few weeks getting familiar with the data, other possible data/information sources, the specifics of EPP (an eviction relief program run by the city of Athens) and how it was run, and how our work fits into a larger context of community-engaged mapping. We have broken into groups to address key research questions about the eviction landscape such as: Who is doing the most evicting? Where are landlords located? Who benefitted from EPP? What are the demographics of the communities facing the most evictions? I am on the “categorizing landlords” team, where we are trying to determine how to categorize landlords by number of properties, eviction filings, eviction outcomes, and see how these categories compare. Once it was time to dig in, our team got caught up in the details quickly, so I want to take a moment to reflect on how our work contributes to the concept of situated mapping.

By focusing on mapping and understanding landlords instead of tenants, we are attempting to aim the conversation surrounding evictions on those pushing forward the processes of dispossession. Through this project we were able to identify the landlords in Athens filing the most evictions and gather information about their eviction behavior, such as how many filings resulted in evictions. Instead of simply asking ourselves where the evictions are happening, we have tried mapping for action. AHAT and those facing housing stress can reference this data about landlords when deciding the best avenues for advocating for tenants’ rights.

Learning critical cartography as a UGA student also provides a better understanding of what exactly our situatedness as students entails. We have access to resources that allow us to help community issues be taken seriously by institutional power. Resources that are not accessible to many Athens residents. Students also have a massive influence on the housing market in Athens, so it’s important to recognize the ways in which we can contribute to the problem even as we play a role in trying to address it. Ultimately, our situatedness as a group less likely to face eviction, with access to institutional power, and a major force on the housing market inevitably inform our work. Recognizing my own situatedness and the truths often overlooked by traditional mapping are lessons from Community GIS that I will carry with me for the rest of my career.
 
References 
Maharawal, M. M., & McElroy, E. (2017). The anti-eviction mapping project: Counter mapping and oral history toward Bay Area Housing Justice. Annals of the American Association of Geographers, 108(2), 380–389. https://doi.org/10.1080/24694452.2017.1365583
 
Shelton, T. (2021). Situated mapping: Visualizing Urban Inequality between the god trick and strategic positivism. ACME: An International Journal for Critical Geographies, 21(4), 346–356. https://doi.org/10.31235/osf.io/8zswy
