---
title: "A Reflection on My Change in Perspective Pertaining to the Field of GIS"
date: "2023-04-18"
author: "Morgan Mize, Community GIS student in Spring 2023"
---

By Morgan Mize, Community GIS student in Spring 2023

Before starting college I had never heard of GIS, and if asked I would probably have responded with a similar look of confusion that my peers display when I tell them I’m a GIS major. Yet I have learned so much since then so I would like to reflect on how my knowledge of GIS has changed throughout my time in college. I came to UGA and within my first year changed my major about 3 times before I settled on Wildlife and Fisheries at the College of Warnell. I was happy with my choice until Fall of my junior year when I had to take Spatial Analysis of Natural Resources, a class that everyone told me was horrible. Yet instead of dreading the class like most of my friends, I enjoyed the work and found myself constantly helping my friends on the lab assignments. During this semester I decided to add a major called Natural Resources and Sustainability with an emphasis in geospatial.
 
After that I started to really focus on my geospatial major and that spring I did a co-internship with the Athens-Clarke County Geospatial Office and Keeping Athens Clarke County Beautiful (KACCB). This internship was my first experience in GIS applications outside of natural resources. During my internship I learned about ArcGIS Online and discovered just how broad GIS applications can be. This was my first experience in which I got to learn how GIS applies to the community. My own project was focused on helping the community find and report information relevant to the Adopt-A-Highway program.
 
This semester, Community GIS has given me a chance to once again use GIS to help the community. The biggest difference with this class versus my past experience is that the need for GIS comes directly from the community. Before the work I was doing was based on what my supervisors at KACCB wanted so that KACCB could create a better chain of communication with their volunteers but I personally never interacted directly with the community outside of the KACCB and geospatial office. In contrast the two projects we are doing with this class allows for direct interaction with the community with a specific need.
 
Not only is the method of communication different in Community GIS, but this class has taught things in more of a real world context application then any other class I have taken. For example Community GIS helps people in the Athens community that have a current problem and are searching for a solution in the present. In my other classes the teaching methods tend to always use old or fake data with a set of instructions to get an expected final product that matches the professor’s answer key. The different teaching method helps me to correlate what I am learning to a long term purpose besides an A on this week’s lab assignment. Instead of following the bulleted points meant to walk me through a fake analysis that I will forget the following week, this class allows me to understand how to use and work with raw data. In contrast to other GIS classes, Community GIS is unique because the work is all done for a reason with learning occurring along the way. 
 
Overall this class is very unique compared to any other UGA class. I find this to be an interesting experience as I take it alongside another service learning class. While this class works together to achieve goals to benefit the community, my other service learning class is made up of smaller groups working directly with a single property owner. Taking these two classes alongside each other has shown me different perspectives of how one can use UGA knowledge to provide a service to another. In my opinion working with the community requires a more in depth analysis concerning not only the goals, but also looking at why this is an issue to begin with. This then leads into issues involving population demographics and even prejudice towards low income. While my other class is more surface level in which the priority is implementing a plan to help the property owner generate income of some kind. In Community GIS, the relationship with the community is much more delicate in which one has to take into account the emotions of the individuals in the community.

While I didn’t start my college journey knowing GIS, I am ending it knowing more about it then I ever thought I would. The past semesters have shown me the wide range GIS has in our world. This class has given me a very different perspective on the impact GIS has in a community. While I still see myself pursuing a career using GIS in natural resources, I believe I can bring with me key takeaways from this class to my future career. For example I believe this class has given me insight into the importance of a client’s emotional connection. For example the history or memories made at a piece of property might mean more to a client than a management plan for timber. I believe that the area of natural resources tends to be more detached from the emotional connection of clients, but I can see how it would be imperative to understand why a client might want to preserve certain areas of land based on emotional rather than textbook reasoning. Whether that reason is because of the client’s memories or history, the emotional connection is something that still needs to be addressed and shows that what the client deems valuable might not always be numbers on a spreadsheet.
