---
title: "Building bridges: Perspectives from 'across the river'"
date: "2024-06-06"
author: "Zane Frentress, Spring 2024 Community GIS Student"
---

By Zane Frentress, Spring 2024 Community GIS StudentThis winter, our Community GIS class began work with Rashe Malcolm, a local activist and proprietor of Rashe’s Cuisine, to compile a neighborhood profile of Inner East Athens. Rashe is working on a redevelopment plan for Triangle Plaza and the surrounding area that would increase food access and affordable housing options for neighbors. Triangle Plaza is located at the point where Vine St. and Nellie B. Ave intersect, across the street from Bert’s Grocery and just down the road from the Nellie B. Community, in the heart of Inner East Athens. This historically Black neighborhood, roughly bounded by the Oconee River to the west, the Loop to the south and east, and North Avenue, has experienced dramatic socioeconomic changes in the past few decades. Many long term residents find themselves vulnerable to displacement as developers and real estate agents steer homebuyers “across the river” to the East side. As a geographer-- and a renter-- in Athens, I’m more than aware of the predatory housing market and how skeezy developers are driving up the cost of living, pushing out anyone who can’t keep up with the astronomical rise in rent and property taxes. I knew this was happening in East Athens, but I had personally never spent time in the area. What I knew about the neighborhood was filtered through my connections at the University and secondhand sources. Now, I found myself in a Community GIS class collaborating on a project with Rashe Malcolm and other community members trying to find ways to connect our ways of knowing Inner East Athens, as geographers and community members, that can support Rashe in her food access and economic justice initiatives. The project we are working on with Rashe is an act of translation-- we are building a bridge “across the river.”
 
We first met Rashe at Triangle Plaza this January. For the first time in my personal experience, I came to Inner East Athens by crossing the river, not by zooming in on Google Maps. Many of my classmates had the same experience. Instead of reading through computer screens, we squinted through the winter sun to see Rashe’s vision for the neighborhood. We met Rashe in the community hall in Triangle Plaza, where she pointed out the empty rows of electrical outlets left over from previous salon and laundry businesses, and talked about what bringing back businesses could mean for the community. We stood with her in the parking lot, where she saw potential for garden beds and an industrial kitchen. We followed her to the (mostly) empty lot behind Triangle Plaza, where she saw a full service grocery store to serve the surrounding community. As we spent time with Rashe, her vision for the neighborhood embedded itself in the way I saw the landscape. The maps and census groups we used to define Inner East Athens in our early GIS labs materialized as roads and homes and businesses and we were able to think through the ways that Rashe’s material vision and our virtual one connected, and how these perspectives could build on one another. These connections informed the way we designed our research questions for the rest of the project. We are currently working to finalize a document that focuses on five geographic aspects of Inner East Athens: demographics, property ownership, businesses, gentrification, and food access.
 
Our meeting with Rashe was informative, not only because of what we learned but from the ways it highlighted how much we still had to learn on our own. Back in the classroom after our visit, we learned more about business turnover through data on business and property transfer over time. We read more about the complexities of defining food access and how location alone cannot predict which residents might experience challenges in having access to nutritious and culturally appropriate food. During our visit to Triangle Plaza, we noticed that the residents passing by-- most of whom were Black-- were eyeing us with reasonable suspicion. We learned about “studentification,” and the ways that the University we represent has wrecked the housing market in Athens by accepting more and more students from wealthier backgrounds without building new on-campus housing for them. This has forced many Black residents out of their neighborhoods as developers rush to cash in on the student boom by buying up housing with a low market value and flipping it back to students with a high price tag. As students ourselves, we spent a good deal of time talking about “positionality,” and what kinds of knowledge we do and do not possess as outsiders from the University, and how we can be both learners and contributors in the translation project we were working on with Rashe.
 
Collaborative knowledge production has a nice ring to it. I was particularly excited to learn more about the various ways to approach research in community geography. Over the next couple of months, our class went back and forth not only with Rashe, but with other people affiliated with the neighborhood such as artists, business owners, city commissioners, and journalists. Then, we went back and forth with ourselves over how to process the abundance of information we just got. Then, we revisited our own cartography and data processing skills, and learned some new ones along the way. By cycling through these stages of asking, learning, doing, reflecting, and reworking, we are engaging in my favorite word from this class: praxis. Praxis is the process of applying the things we learn to the things we do, learning from that process, and doing it all over again. After a few weeks of this, though, we found that we needed to break the ice and address how deeply uncomfortable it can be to learn and unlearn this way. Working with large groups and partners requires maintaining a delicate balance between listening and realizing what you can or can’t offer in discussion. We’re trying to render visible something we’re only just starting to see, and pass it on to someone who has a clear vision, who doesn’t need the color gradients and zipped .csv files to verify her lived experience.
However, throughout this class we have also seen over and over how powerful geospatial data can be as a tool to communicate. We learned how to sort through census data to isolate specific information that could help us back up our collaborators’ experiences in Inner East Athens. We found we could track things like studentification over time by looking at fields like “percent of residents between 18-24 years of age,” “percent of residents renting vs. residents who own a home,” and “percent of residents with secondary education or higher,” over several decades. We learned how to use tools like Business Analyst to show how Inner East Athens stacked up against the rest of the city in terms of amenities, and who was using them. We learned how to track down whether property owners and business owners lived in the neighborhood to see just how much of the money spent in the neighborhood actually stayed in it to support the community. We learned how to run programs on GIS software that could calculate walking and driving times from a given point so that we could see how far away residents had to travel to get food. Even though many of us in the Community GIS class had only crossed the river for the first time this winter, and still consider ourselves outsiders, we still found that we were able to contribute to this larger project through praxis: We work with Rashe to bridge the world that we have come to know with the world that she wants to build in a way that accommodates multiple ways of knowing Inner East Athens. It’s been messy, but the work we do will continue to live and change through Rashe’s long term investment in redeveloping the neighborhood.
​
