---
title: "my first look at east athens"
date: "2024-03-18"
author: "Steven Peay, Community GIS Student in Spring 2024"
---

By Steven Peay, Community GIS Student in Spring 2024I am a fourth-year geography major at the University of Georgia with certificate programs in Geographic Information Systems and Urban and Metropolitan Studies. This is my third semester at UGA. One of my classes is “Community GIS” and we are currently learning about the city of Athens outside of the university and downtown, specifically East Athens. Despite living on East Broad Street for over a year now, I have never visited East Athens until our class took a trip to Triangle Plaza last month in January. Rashe Malcolm, a local business owner and resident of East Athens, spoke to our class about her personal experience with studentification, housing prices, property taxes, and racial zoning.
 
East Athens, located immediately east of Downtown Athens, seems cut off from the rest of the city, even though Triangle Plaza in the center of the community is less than two miles from the UGA Arch. The neighborhood has a lot of old houses that could use some renovation, roads full of large cracks and potholes, with two small strip malls in the middle of the neighborhood. While some major roads of Athens go through this community, like East Broad Street and Arch Street, I saw very few people driving through East Athens, and Google Maps always directs me to take either North Avenue or Lexington Road when driving to either Atlanta or Lavonia. Most of the ACC bus routes drive around East Athens with few stops in the actual community, which is odd, as East Athens has a low median household income and likely also a low car ownership rate. I don’t want to jump to conclusions or make unreasonable claims, but it feels like I’m not supposed to know about this neighborhood and it is being hidden from people who live outside of Athens. When I first heard “East Athens” I originally thought of places like Georgetown Square in the eastern part of Athens-Clarke County near Winterville, rather than immediately east of downtown.
 
Rashe is the founder and CEO of Rashe’s Cuisine, a Jamaican soul food joint. She has run this small business for over 30 years and since not many people drive through East Athens, most orders are deliveries and takeout/pickup orders. During her speech to our class, she stated that many old houses are being destroyed to make space for new student housing, as the community is seen as “ghetto”, while most of the rest of Central Athens is seen as historic. Rashe wants a community garden and a grocery store in or near Triangle Plaza, as East Athens is a food desert, meaning there is no easy and affordable access to fresh fruits and vegetables, lean meat, bread, and dairy products. She also advocates for tax breaks on life-deed houses, or houses willed to their current occupants by previous generations. Most houses are owned by the current residents, but they can’t afford the rising property tax caused by gentrification, studentification, and inflation.
 
East Athens is a majority-black neighborhood and is a result of historic redlining and racial zoning, which has led to the community’s status as a food desert, poorly funded schools, little public transportation access, and poor infrastructure, leading to the high poverty rate, keeping the community underdeveloped. There is hope for this neighborhood, as people like Matthew Epperson and Imani Scott-Blackwell run non-profits to help integrate the isolated community with the rest of the city of Athens. They both work for Hivemind, a cooperative that strives to fight poverty and elevate low-income communities in Athens and surrounding counties.
 
I hope that using open-source and easily accessible GIS information the people of East Athens can make their voices heard and achieve funding for affordable housing and mixed-use business and apartment buildings for residents to live and work, more access to public transportation through East Athens, slower gentrification in the area to allow them to build wealth and afford to live, and eventually break barriers and “invisible walls” dividing them from the rest of the city. With the spread, popularity, and increasing access to the internet and public information, it has become much easier to find out more about how to find resources for rent/tax assistance, location of affordable housing, and local nonprofits. I am very optimistic that these goals can be reached, not only in East Athens, but in every low-income community in the United States still suffering from racist political and financial decisions made nearly a century ago, creating more integrated and united cities and localities, at the cost of no one’s life or financial prosperity.
