---
title: "Moving from the “Where” to the “Why” in Eviction Mapping"
date: "2024-06-10"
author: "Logan Wiley"
---

By Logan Wiley

Last month, my labmate Annie and I presented our research on the Athens eviction landscape at UGA’s annual Center for Undergraduate Research (CURO) Symposium. We had spent many of our research hours in two places: at the Athens Magistrate Court Office digitizing eviction files or in the Community Mapping Lab entering data into our online dashboard. So, discussing our work with professors, community partners, and other student researchers offered a refreshing and rewarding culmination of our effort during the semester. Our poster focused on the relationship between eviction filing and non-local property ownership, visualized by our map of eviction hotspots in the county and filings identified by non-local and local ownership. Through my work on the project this year, I developed my understanding of mapping’s role in analyzing housing inequities but also realized that our maps lack many of the causes and contexts necessary for addressing these issues.

Our updated map of eviction filing hotspots and rental property ownership showed four eviction hotspots dispersed in west, east, and north Athens. Most of these hotspots concentrate around apartment complexes including Lexington Heights, Arbor Ridge Apartments, and Hidden Pines Apartments. Based on my readings of the files, tenants often receive an eviction affidavit after being late or partially behind on rent due to job loss or temporary illness. From my perspective, eviction filings exacerbate housing insecurity in impoverished areas of Athens and perpetuate income inequality. Along with updating our visualization of the eviction hotspots, we wanted to analyze how nonlocal property speculation affects housing insecurity in Athens by investigating the business locations of evicting property owners. This analysis was overdue after the purchase of duplexes by non-local investment company Prosperity Capital Partners led to rent increases and displacement for low-income Athens tenants in June 2022.
I would like to expand analysis of nonlocal property ownership to include some statistical analysis, but for this poster we conducted preliminary examination and visualization of nonlocal speculation. Out of the twelve property owners with more than fifty evictions filed within their properties, nine of them are based outside of Georgia (75%). Prosperity Capital Partners dominates the list with more than 350 filings across their many Athens properties, equating to more than 10% of all eviction filings recorded within our period of analysis. The next highest evicting owner, Filmore Capital Partners, has about 175 filings recorded, half the amount of Prosperity Capital Partners. Even from these first analytical steps, it’s clear that non-local property speculation plays a role in displacement and must be considered for future policies and housing activism. The updated hotspot and nonlocal property ownership analysis produced engaging discussion before and during the conference, but I believe the next phase of the project must find a new community partner or expand our local network to properly use our data and inform organizations addressing the housing crisis. Mapping where evictions occur has been an important foundation for the project; now, we must expand analysis on why evictions occur and how we can address displacement in our community.

So far, we have worked well with the local government and the activist group Athens Housing Advocacy Team (AHAT), but I feel that the project lacks the experiences of tenants experiencing the housing crisis. Although still vague, I hope to help include more community perspectives in further analysis, possibly through alternative mapping methods or explorations of the roles of gender, race, and language in the experience of housing insecurities. After developing a strong research network in the Community Mapping Lab and learning practical skills through geospatial analysis and visualization, I feel confident to identify and fill in the blind spots of our current eviction analysis.

Logan Wiley is an undergraduate at UGA majoring in Geography and Psychology. He has been working in the CML for the last two years.
