---
title: "a reflection on co-production of research in geography from an ecologists perspective"
date: "2024-04-25"
author: "Paige Robinson ​"
---

By Paige Robinson ​
As an ecology major, my perspective on engaged research is perhaps a bit different from some of my fellow geography students. In my previous experiences working on research projects, I am used to taking a very traditional scientific approach. We come up with a hypothesis, create an experiment to test it, and then interpret results. It is very logical and straightforward with everything being guided by previous research. I have enjoyed that approach in the past because of how straightforward it is; there is no outside noise to worry about, and it’s all up to you and your small team to work towards the results you want. I will say there is of course ecological research that involves social science and there are different methods in ecological research that may mimic this class more, but they are projects to which I have not been exposed. For our specific project in Community GIS, we have been tasked with assisting Rashe Malcom, a business owner in Inner East Athens, with her goals of building a community garden, a new grocery store, and more affordable housing in this community.

Rather than the traditional scientific approach of question-answer, this project is far more nuanced and open ended. We will get quantitative results, sure, but what to do with them will be a very complex answer that isn’t up to us. We are serving as the grunt work for Rashe to research her questions about the Inner East Athens community to better inform her decisions moving forward. Her input is part of the process of co-production, which involves ensuring that researchers and the people being researched both have a voice in the production of the research and how it is used. This is an important concept for this project, as it's meant to ensure that people aren’t taken advantage of. These questions are: What is the business demographic of Inner East Athens(IEA)? What does food access look like in IEA? What are the demographics of the people in IEA and how does that compare to the rest of Athens? Who owns property in IEA? What areas of IEA are gentrified and which areas are most susceptible to future gentrification? Doing a whole project working towards what we know will be a complex answer rather than black and white results will take some getting used to. Over the course of the semester, I have shifted my mindset from being used to the satisfaction of a definitive answer, to more of a satisfaction from knowing our work will eventually be used to help inform future decisions out of our control. It’s more hands-off in the long run but I am excited to see where these results take Rashe’s goals and how she will use them to uplift her community.
​
Another aspect that is perhaps a bit less familiar for me is having our work split up so much into smaller groups. It can almost feel like we are working on entirely different projects at times, rather than just working on different aspects of the same project and working towards the same goal. The scientific research I am used to can also involve a team aspect of course, but it is usually on a much smaller scale. Working with such a large group and coordinating so many different people’s opinions and ideas on the best way to perform our tasks has been overwhelming at times. However, I think having multiple perspectives is also useful, especially when the results of our work will not directly affect us. Most of us do not live in IEA, and will likely not be involved in this project once we leave this class. Therefore, hearing out everyone’s opinions and making sure we do this right is very important. In comparison, working on ecological research in a lab feels different because the stakes often feel more personal; it feels as though since there are fewer of us working on a project, we are all more personally tied to its results- especially because the projects are usually not tied directly to another group of people (as is the case with our research on IEA).

While there are pros and cons to both methods/types of research, I think co-production is extremely beneficial for this project. I have really enjoyed learning how to incorporate other people’s perspectives from outside of our group into this project, and I understand its immense importance. Working with animals or plants or any other non-human part of ecology, it is rare to see a perspective like this that is so conscious of the impact of research results and processes. Having experience with both during my time at UGA has already changed the way I think about research and will only continue to improve my skills in the future. I think more ecologists should be aware of concepts like co-production and be better about division of labor, impacts on the people living in study areas, etc. I hope that as I enter my career, I will be able to take what I have learned about these things from this class and improve my research going forward.

Paige Robinson, a third year Ecology student with a minor in geography and certificates in GIS and Sustainability.

Keywords: Scientific Research, Research Methods, East Athens, Co-production
