---
title: "A step out of my comfort zone: a reflection on the process of public and community engaged"
date: "2024-04-25"
author: "Peyton White, Community GIS Student Spring 2024"
---

By Peyton White, Community GIS Student Spring 2024Stepping out of one's own comfort zone is just as it sounds: uncomfortable. This was what I chose to take on as an Ecology major adding a GIScience certificate, with which I was largely unfamiliar with, yet eager to experience. I am currently enrolled in “Community GIS” at the University of Georgia, where the focus is to put geographic tools to use in real-world problem-solving applications. Putting these GIS skills that I have only recently learned into practice through collaborative research has been new territory for me.

Prior to this class, I had no experience in community engagement or service-learning projects. In my GIS certificate classes thus far, I had felt as if I was just going through the motions of downloading data, making maps, and turning them in for a grade. I can fairly say I had a sense of imposter syndrome, as people around me had dedicated their entire majors to Geography and I felt as if I was just jumping in and skimming by. This differs from Community GIS in the sense that we routinely meet as groups for collaboration with our classmates and occasionally with community members via interviews, and most of our work is a team effort towards one final goal. Now that our deliverables are to be used for a purpose rather than merely a grade, I feel as though this is the step up to the plate I had been preparing for.

The community service project for this term involves assisting Rashe Malcolm, a business owner in Inner East Athens (IEA), in her plans to revamp the area surrounding the “Triangle Plaza” by constructing a grocery store, laundromat, community garden, and affordable apartment-style housing for the community. We intend to create demographic, economic, and business profiles of this area and provide what we create to equip Rashe with information to use as she sees fit.

The most impactful part of this class to me has been our interactions with Rashe and going out to see East Athens as a class. Crossing over the North Oconee River felt foreign, and being met with turned heads and stares from residents, I felt out of place in a way I had never experienced. Upon stepping out of my car, and other students stepping out of theirs, we were met by Rashe with warm greetings and inviting energy. She spoke with us about her plans, and walked us to the site where she intends to make it all a reality. I love learning of Rashe’s ambitions and goals for the community, and I am so glad our class can support her endeavors.

Furthermore, the impacts of this project could reach not just Rashe, but the whole community. Although we are only creating deliverables for Rashe herself, the materials we provide could potentially lead to the broader impact of Rashes proposed plans being executed. Rashe is also currently running for Commissioner of District 6, and the information we will provide could be meaningful for non-IEA residents to understand IEA and how it compares to Athens-Clarke County. It makes me so grateful that she is placing her trust in our class’s budding expertise, and it is refreshing to know our work is going to a purpose far more meaningful than just a grade.

Having spent four years in Athens completing my undergraduate degree and never hearing of East Athens until this semester, I can say this class has been such an eye opening experience. Looking back on how I would tell others that I live in Athens makes me feel like an imposter – I never truly understood the disparity between college student life and resident life of Athens. Just two miles from the renowned UGA Arch and less than a mile from high-rise student housing, infrastructure and demography undergoes a sudden change.

With my newfound knowledge of Athens and the new meaning of GIScience I hold, I am becoming comfortable with being uncomfortable. Breaking free from the imposter syndrome I felt throughout my progress in this degree certificate, I no longer feel like my major is a hindrance to my ability to succeed in my GIS classes. I no longer feel behind, out of the loop, or less than. This step of taking Community GIS has given me such vast and valuable knowledge of my community, and ties together what all of those tools I learned are meant for. Wrapping up this certificate with this course and project makes all of that learning come full circle, and I can not recommend this course enough.

Peyton is a 4th year B.S./M.S. Ecology DoubleDawg student at the University of Georgia, pursuing a certificate in GIScience. Her current research is a multidisciplinary approach of genetics, biogeography, and physiological ecology to understanding the North American Atlantic coast mussel species, Geukensia demissa.Keywords: Community projects, engaged scholarship, imposter syndrome
