---
title: "behind the scenes of Geographic information sciences"
date: "2024-06-06"
author: "Nicholas Lounsbury, Spring 2024 Community GIS Student"
---

By Nicholas Lounsbury, Spring 2024 Community GIS StudentMuch of my learning in my undergraduate path came from the Community Geographic Information Science course led by Dr. Jerry Shannon. This course spends a lot of time collaborating to assist local community members. In past semesters most Geography courses for me were following directions from an assignment sheet to create maps in Geographic Information Systems (GIS) software but this course was different. This course is much more about the research and development part of GIS that I’ve never had to deal with before; in the past professors would just give us cleaned-up data and tell us how to visualize it. But this course spent the most of its time allowing us the opportunity to see what goes into the background of community-based GIS work including interactions with community members as well as processing and visualizing data to fit our research purposes. I spent the majority of this semester working with my classmates and with feedback from community partners to research the neighborhood of Inner East Athens, a neighborhood that has long been ignored by Athens government officials and is undergoing gentrification as residents get driven out by rich renters seeking affordable housing. A big part of the community research process in my project was communicating with a resident of the Inner East Athens (IEA) community, Rashe Malcolm, a local restaurant owner and county commissioner candidate. Malcolm voiced her concerns with her neighborhood as well as project goals she wants to achieve for the community. By sharing information between our two groups we can gain a more comprehensive understanding of the community to more easily address the plans Malcolm has in mind. This process is known as the co-production of knowledge, where information is shared between groups to achieve a more relevant and beneficial outcome from research for both parties involved. We had multiple meetings with Rashe Malcom to get an understanding of what she wants from us, using our technical experience with GIS, as well as to get feedback so the work we do is relevant and useful to her. This kind of back and forth community interaction is something I never got from another GIS or geography course and provides a clear insight into what community-focused GIS work could really be like, which is a lot of planning and brainstorming meetings. Throughout much of Community GIS’s course we spent time split up into separate groups tackling issues we pointed out with the community including matters like food access, property ownership, and gentrification, the last of which I spent my time working on. As I stated before, past geography courses I took revolved around being given data and being told what to do with it, but here we don’t have that luxury as we must learn to gather and apply the data ourselves in a way we think would best assist the community. We had many meetings just going over ways we can display the risks of gentrification to the East Athens neighborhood which involved finding articles of past efforts to visualize gentrification to modify to best fit our purposes. We discovered a few variables such as economic vulnerability, demographic change, and housing sales price changes to be the best way we can achieve this goal of greater understanding of gentrification risk. To get most of this data we downloaded census information and spent time in Excel cleaning up the data to prepare it for GIS software visualization. It took a surprising amount of time just processing a few datasets to prepare for GIS work. This data processing work is something most of us never did before even if we had past GIS classes because the datasets usually come prepared for GIS software already, so learning how to format data on our own was a valuable and eye-opening learning experience. I believe this course was a valuable insight into behind-the-scenes work that goes into geographic research beyond the obvious map-making endeavor that is only the tip of the iceberg and final touches to a community project that spanned multiple months of collaborative and independent work.

Bio: Nicholas Lounsbury is a fifth-year undergraduate Geography student passionate about urban planning and transportation issues. Having spent time in his undergraduate path learning about GIS techniques and cooperative research, Nicholas plans to use those skills outside of college after he graduates later this year

Keywords: Communities, GIS, Inner East Athens, Gentrification, Research, Co-Production, Data

References:

Norström, Albert V., et al. “Principles for Knowledge Co-production in Sustainability Research.” Nature Sustainability, vol. 3, no. 3, Jan. 2020, pp. 182–90. https://doi.org/10.1038/s41893-019-0448-2.
