---
title: "Community mapping, co-production of knowledge, and how i understand research"
date: "2024-03-18"
author: "Brandon Latimer, Community GIS Student in Spring 2024"
---

By Brandon Latimer, Community GIS Student in Spring 2024

Community GIS is a class offered at the University of Georgia each spring semester and is taught by Dr. Jerry Shannon. As described on the Geography Department website, it is a course designed around a service-learning project that “[provides] GIS support for a group in the community.” I signed up to take the Community GIS class this semester with little idea of what it actually entailed. I was excited to apply GIS, a field I have been interested in throughout my time at UGA, to local issues. However, I had a poor understanding of what that work might look like. I came in eager to hop on the computer and begin to map whatever it was I needed. I quickly learned that this is just one small part of what community mapping projects, and research projects in general, look like. I will use the concept of knowledge co-production as an example of how my understanding of research has shifted.
 
Co-production emphasizes the importance of collaboration in order to create knowledge that incorporates a diverse set of information and experiences within relevant contexts. It is a holistic approach that attempts to limit partiality and maximize the positive impacts of knowledge production. Norström et al. (2020) write about the four fundamental aspects of knowledge co-production, noting that research should be context-based, pluralistic, goal-oriented, and interactive. Pluralistic and context-based work results in the implementation of a variety of skill sets and information to address a specific problem, along with the many contexts in which that problem exists. The research is goal-oriented in order to create a clearly defined objective for all involved parties to work towards. In order to do this, the work must be interactive, ensuring that everyone is involved throughout the entirety of the project. This guarantees that each party’s voice and expertise are accounted for.
 
As our class read about and discussed this concept at the start of the semester, I appreciated its emphasis on transdisciplinary research. However, it was still very early in the semester, and I was a little unclear about its role in our work. Once again, I was looking forward to just sitting down with some music and mapping out some local topics of interest. As the semester has progressed, we have learned more and more each week about what a community-based project entails, including our role in knowledge co-production. One of the most essential elements of this type of work is learning how to properly engage with community members in order to understand how we can best help each other.
 
Our specific task in the Community GIS course is to work with Rashe Malcolm, a business owner in East Athens. East Athens is a community that has long been neglected and mistreated. As the University of Georgia continues to grow practically across the street, East Athens remains less developed than other surrounding neighborhoods. With the student population expanding each year, studentification creeps into East Athens. Studentification is a form of gentrification with social, cultural, and economic changes that are specifically related to the influx of college students (Pickren, 2012). Broadly, Rashe is attempting to redevelop East Athens for locals to enjoy, not for a constantly overturning student population. Included are plans for apartments, a grocery store, and a community garden. Rashe is encouraging entrepreneurship and improving the community’s access to healthy foods. Our role is to provide Rashe with any data and information she might find useful in this process.
​
While I could always read about these issues, my understanding would be insufficient without our class's partnership with Rashe. As a longtime business owner in East Athens, Rashe is an integral part of our work. Throughout the semester, our class has remained in touch with Rashe through Dr. Shannon, including visiting her in East Athens. Listening to Rashe’s perspective and vision for the community was far more informative and inspirational than anything I could read or hear in a classroom. This trip helped me learn more about the context in which studentification and the uneven development of the city occur and more clearly outline the goal of our collaboration. Currently, the class is preparing to interview local individuals, including members of the East Athens community, East Athens representatives, and more, to further our understanding of the neighborhood. Additional interviews will expose us to new perspectives and concerns regarding the East Athens community. This process is one of the ways in which we can stay engaged throughout the project, as well as providing us with a variety of valuable viewpoints.
 
Co-production of knowledge is a concept that applies well to what we are doing in Community GIS but is also a valuable tool in many types of research. As the first half of this semester has flown by, I am learning more and more each week about how to properly engage with community members to conduct ethical and impactful work. I now see an incredibly important side to research that I had previously been overlooking, and I am excited to discover anything else that I might have been ignoring.

Brandon Latimer is an anthropology and geography major, graduating in May 2024. Brandon is working on Urban Studies and GIS certificates and will be getting into the field of global development after graduation.

References
Norström, A. V., Cvitanovic, C., Löf, M. F., West, S., Wyborn, C., Balvanera, P., Bednarek, A. T., Bennett, E. M., Biggs, R., de Bremond, A., Campbell, B. M., Canadell, J. G., Carpenter, S. R., Folke, C., Fulton, E. A., Gaffney, O., Gelcich, S., Jouffray, J.-B., Leach, M., & Le Tissier, M. (2020). Principles for knowledge co-production in sustainability research. Nature Sustainability, 3(3), 182–190. https://doi.org/10.1038/s41893-019-0448-2
 
Pickren, G. (2012). “Where Can I Build My Student Housing?”: The Politics of Studentification in Athens-Clarke County, Georgia. Southeastern Geographer, 52(2), 113–130. https://doi.org/10.1353/sgo.2012.0019 
​
