---
title: "The art of research"
date: "2024-06-06"
author: "Andrew Mote, Spring 2024 Community GIS Student​"
---

By Andrew Mote, Spring 2024 Community GIS Student​As a fifth year Geography major at the University of Georgia, I have learned a lot about how the world changes and why it does so. All of these classes, such as Commodification of Food and Urban Geography, have taught me valuable concepts like how urban spaces sprawl and how that’s changed over time, or how food is commodified and globalized. I have acquired plenty of valuable skills and foundational knowledge to help me understand the world but Community GIS is the first class that really has taken what I’ve learned and applied it to the real world. I’ve always strived to do good in the world as I move forward and learning about these concepts was my answer to doing so. I want to learn about the people around me so I can help them if they ask for it. So far, my coursework has really solidified my understanding of power structures and the systems we live in, but I haven’t had many chances to learn how I can help in a more direct manner or how I can move forward and help the others around me do so as well. Community GIS along with a few other experiential learning classes have become my foundation for the so-called “art of research.”
 
Research, just like any other worldly endeavor, has its own artform that guides its creation. Just as with a canvas, the person behind the brush has control over how it forms but not entirely. The art is in the process. You can plan out your artwork as much as you want, cover the canvas in sketch lines, but it’s not until you’re halfway through and asking questions that the art begins to take shape. Similarly in research, you can plan it out as much as you want, but only when you step out and start talking to people and looking at patterns that the artwork starts to form. This idea is reinforced by a concept I learned in Community GIS, called co-production of knowledge. The kind of research that focuses on incorporating community voices that the data is based on, the kind that avoids extractive tendencies that often go with studies of society. Before this class, I didn’t think I was the type of person to promise to help a community with my research and leave without completing my end of the deal, but to see this concept had a name and a study of its own was quite intriguing.
 
 “Co-production of knowledge” focuses on doing research in a manner that supports all the parties involved. It not only does this, but it also recognizes the varying positionalities involved in the project and how those multiple types of expertise can be best utilized. It’s not just about academic experience but also the lived experience of the community partners which helps produce knowledge collaboratively. The goal of it is to step away from extractive forms of research, the ones where a professor at a university goes into a community, makes a bunch of promises, and then as soon as they have their data, they leave. The knowledge created by these practices is more pure because it incorporates many perspectives. Producing research with this in mind, grounds the knowledge in place and establishes context which makes it more true to itself. It is artistic in nature because it accounts for the process in and of itself. It recognizes that the process taken to acquire data shapes the data itself but it’s also important to understand how it emphasizes that this process is impossible to empirically show and can only be truly understood by the people involved.
 
Not only is it about how the research is used after the fact, but I think it also helps guide the research process as a whole. One of the biggest things I learned is how important it is to understand everything you can about your study area before you even look at the relevant factors to one's research. I got a better understanding of this outside of Community GIS as I was interviewing a UGA Geography graduate student. Pablo Arias-Benavides is a PhD student who focuses his research on Costa Rica and how sustainability policies affect locals going through their day to day life. A lot of his research hinges on interviewing locals and the way he talks about the interviewing process really shifted my view on how to conduct research in general. While you’re interviewing or in the middle of researching, you have to let the process itself guide you. Particularly in interviews, often it takes its own direction and you have to let that happen to a certain extent as that will show more truth than any question you can ask. Though, if you don’t understand what you’re researching beforehand, you are bound to get caught up in the tiny details when it’s time to figure out the big story.
 
There is so much value in understanding the basic demographics of an area before diving into the more specific research related questions. It goes so much further than this though, I learned that if you only study the quantitative data of an area, it is impossible to truly understand how a place functions. I think that’s a common thing Geographers get stuck on, they focus on telling the story through a map but forget that it’s only a single paint brush on a massive canvas. This is why it is crucial to allow time for verbal knowledge to be exchanged. While a zoom call with the client may never create a useful data point that can be used in the final document, one single discussion can make a huge difference in the quality of the data down the line.
