---
title: "addressing food access in East Athens: A Conversation with district commissioner Tiffany Taylor"
date: "2024-04-25"
author: "Nishad Kute, Community GIS Student Spring 2024"
---

By Nishad Kute, Community GIS Student Spring 2024

Intrigued by the intersection of community development and Geographic Information Systems, I decided to enroll in the Community GIS course taught by Dr. Jerry Shannon at the University of Georgia. As a 4th year ecology major completing the Geographic Information Science certificate, I was drawn to the opportunity to apply my newly acquired GIS skills to real-world challenges facing Athens. I had never taken a service-learning course before, so I was not entirely sure what to expect. My initial expectations for this class involved fine-tuning my pre-existing skills in GIS and learning how to apply them in a real-world environment. I quickly discovered that this was not the case, as I found myself having philosophical discussions and interviewing local political figures. The core of Community GIS focuses on the co-production of knowledge by working collaboratively with community partners to contribute to positive change in underserved communities like Inner East Athens.

Located roughly a mile from downtown, Inner East Athens seems to be in a central location in the city but in reality feels much more isolated than the rest of Athens. East Athens has a long history of neglect from Athens Clarke County, leading to issues regarding food access, education, public transportation access, and poverty. Our project focuses on the area in and around the Triangle Plaza in Inner East Athens. Triangle Plaza currently has several small businesses, including a grocery store and liquor store, as well as a police precinct. Also located in the plaza is Rashe’s Cuisine, a Jamaican restaurant owned by Rashe Malcom, a local business owner and community partner for our class project.

Rashe’s vision for East Athens involves the redevelopment of the area in the Triangle Plaza, including plans for affordable housing units for residents, a grocery store, and a community garden. Our role as students in this course is to assist Rashe by providing any data and maps that supports her vision for redevelopment of Triangle Plaza. Rashe recognized the lack of access to healthy foods in East Athens, and her plans for redevelopment aim to encourage entrepreneurship and increase access to affordable, healthy food within the community.

Recently in this class, we have started the pre-proposal phase of our class project. Students have been grouped into different issues that are impacting East Athens, such as gentrification, demographics, food access, and more. Food access was something that had piqued my interest, especially after interviewing District 3 Commissioner Tiffany Taylor. My interview with Commissioner Taylor provided me with valuable insight and context to the issue of food insecurity in East Athens, inspiring me to choose it for the topic of our group projects.

Commissioner Taylor is an East Athens native and has deep ties to the community. She currently serves as the director of the Mothers of Black Sons Development Program, a non-profit organization aimed at mentoring young men and boys in East Athens to learn work ethic, trades, and fostering a sense of brotherhood within the community. When asked about food accessibility and her role as district commissioner, she acknowledged the lack of access to affordable and healthy food, defining East Athens as a “food-swamp”. A food swamp is different from a “food-desert” in the sense that it is characterized by a wide availability and accessibility of foods with low nutrient density, often provided by fast food restaurants and corner stores. Food deserts on the other hand are simply characterized as areas with limited access to healthy food. Within Inner East Athens, the only close-by options many residents have for groceries are either the Family Dollar or the Pan AM Supermarket. Both stores sell mainly overly processed foods, and don’t have many options for fresh produce and meat. Commissioner Taylor reflected on her childhood growing up in East Athens when there were many more options for fresh produce and meat. She mentioned that the Pan AM Supermarket sold fresh food in the past, but now she claims that it’s more of a hair product store than a supermarket. She also mentioned a grocer called the Quality Market, which sold fresh food but was unfortunately torn down for the construction of the Firefly trail, a recreational walking and biking trail that spans from downtown into East Athens. Learning that healthy food was more accessible in the past made me realize the scope in which the city's government has failed this community and has highlighted the need to create resources that provide healthy food to residents.

Commissioner Taylor was also in full support of Rashe’s plan for a community garden, placing emphasis on the importance of creating a community initiative to teach children sustainable gardening practices and cultivating relationships through shared work and collaboration. The benefits of building a community garden go far beyond providing affordable and healthy food to the community, as they also provide opportunities for education and skill development, promote physical and mental health, serve as local sources of economic empowerment, and revitalize the neighborhood. I am learning a lot from this class about how large-scale community projects are carried out, and I hope to one day see the results of our efforts come to fruition.

Nishad is a 4th year undergraduate student pursuing a bachelor’s of science in ecology along with a minor in landscape studies. He is working on finishing his GIS certificate this semester and plans on starting his master’s program in landscape architecture following graduation in May.

Keywords: food accessibility, food justice, community engagement, East Athens
