---
title: "The first six Weeks: a conceptual retrospective of community GIS"
date: "2024-04-25"
author: "Jamie Jordan, Community GIS Student Spring 2024"
---

By Jamie Jordan, Community GIS Student Spring 2024

Through reflection on the initial six weeks of our Community GIS class, I noticed several things that have stood out in our project working with East Athens. Our project will mutually benefit students and community members. Given my intrinsic longing for structure, I have appreciated Dr. Shannon loosely sequencing the course through a series of conceptual frameworks with which to interface and better understand community-engaged research. Regularly revisiting these concepts has proven useful in planning our project.

One major through-line in our course is the co-production of knowledge. In community-engaged research, developing co-produced knowledge involves a collaborative, inclusive approach to generating knowledge. It demands active and equitable participation of researchers and community members throughout the research process, from defining goals and questions to interpreting findings and implementing solutions. Co-producing knowledge emphasizes mutual learning and shared decision-making, recognizing the expertise that researchers and community members bring to the table. By breaking down traditional research hierarchies, we aim to create meaningful knowledge by respecting diverse perspectives. In our specific project in East Athens, we believe involving local residents will help us produce research that better addresses the community’s needs and visions, integrating their firsthand knowledge with our analytical skills as community geographers.

Early in the semester, Dr. Shannon challenged us to understand “strategic positivism,” which involves carefully considering power imbalances, cultural differences, and community details in research. This approach is great for community-focused research because it examines the bigger picture of social, cultural, and power structures. Unlike purely objective views, strategic positivism acknowledges that community partners’ personal experiences matter. It aims to balance thorough research methods with an understanding of the complex dynamics within a community. By using this approach, we can create a more inclusive and relevant research process, specially tailored to East Athens.
​
Another important concept is praxis, which, in community-engaged research, means combining theoretical knowledge (from the strategic positivism approach) with practical application. Praxis is a cycle where theory guides action, and critical reflection helps refine and question existing ideas. For our research, praxis highlights the relationship between abstract theory and context, recognizing that enlightenment and adjustments will arise from this interplay. By using praxis, we will bridge the gap between community research principles and practical engagement in East Athens, rendering our approach more comprehensive and reflective. Ideally, our project will benefit from both archival research, conducted in Dr. Kurtz’s supplementary course studying local historical geographies, and input from East Athens residents.


Praxis | Lifelong Learning Matters (annwalkerwea.wordpress.com/2013/08/04/praxis)
The importance of maintaining awareness of researcher positionality in community-engaged research cannot be overstated. Positionality refers to a researcher’s social orientation, including their identities, characteristics, and roles as they influence their perspectives and interactions within the research process. Acknowledgment of researcher positionality in the context of our analysis of East Athens is crucial for several reasons. For instance, positionality informs the design of the research and often the format of the deliverable. Scrutinizing researcher positionality ensures that methods, structure, and stylistic choices are culturally appropriate, and that data collection and analysis techniques are sensitive to the community’s context and needs.

In the context of my engagement in researching East Athens, I have reflected on my status as a student of GIS, rather than a professional geospatial analyst, which has made me realize that the way I understand and utilize GIS software is different from that of, say, someone working in supply chain management. This awareness encourages a more nuanced approach to integrating GIS analysis within the community, respectful of local context. Recognizing positionality also prompts researchers to critically reflect on their own biases, preconceptions, and potential power dynamics. The reflexivity achieved through examining my positionality helps mitigate the risk of imposing outsider perspectives that otherize the community, fostering a more equitable research process.

Beyond the scope of research design, positionality is fundamental to building trust and nurturing relationships within the community. Transparency about our backgrounds and intentions as researchers is paramount for establishing credibility, allowing community members to understand our perspectives better. Responsible researchers consider positionality frequently to ensure the research process is collaborative and respects the autonomy and agency of community members. For example, it has proven useful for our class to consistently remind ourselves that as students, we are in fact complicit in the gentrification of East Athens through our patronage to student housing complexes. Embracing positionality is needed to conduct ethical, sensitive and effective community-engaged research, as it contributes to the development of genuine partnerships, enhancing the sustainability and applicability of research outcomes to the community. This does not mean I should feel guilty for attending the University of Georgia, but that I should expect my enrollment status to affect my relationship with East Athens and its residents’ disposition toward our class’s research.

I trust that the class time spent this semester interpreting the relevance of various research concepts in the context of East Athens will render our deliverable and analysis more comprehensive, tactful and socially impactful.

Jamie Jordan is fourth-year geography major interested in urban planning and housing inequality, exploring the intersection of archival and analytical community-engaged geographic research.

Keywords: Collaboration, Engagement, Participatory, Positionality
