---
title: "Strategic positivism in inner east athens"
date: "2024-04-25"
author: "Jake Ferus, Community GIS Student Spring 2024"
---

By Jake Ferus, Community GIS Student Spring 2024I am a fourth year Ecology major at the University of Georgia currently enrolled in GEOG 4385 “Community GIS'' taught by Dr. Jerry Shannon. Not having previously taken a service learning class, I was ecstatic to get this experience even though I wasn’t sure what to expect going in. All that was known was that my skills in GIS, Geographic Information Science, will contribute to a community partner in Athens. I was surprised when the first half of the class focused on the relationship between the researcher and community partners instead of going straight into work. The many readings we discussed helped us think through the positives and challenges of doing community engaged research. One concept we discussed really put in perspective what it means to be part of this relationship, the idea of strategic positivism.
 
Positivism is the concept that there is an objective truth that can be derived scientifically. Often, this is proven mathematically through empirical observation and models, which creates laws. Scientists in the search for truth are disinterested, meaning they observe outside their own subject matter resulting in conclusions without personal bias. This theory seemed to align with my own personal values because I believed science shows the truth of the world through research and fact-finding. An objective perspective in research seems like the best way to learn about the world around us. However, as we discussed in class, I learned that looking at the world through universal truths can be dangerous and limiting to progress. This is because knowledge and truth is context-specific. What is true for one time and space is not necessarily true across all time and space. Everyone, whether they want to or not, has a bias they look at the world through. This is something that can’t be avoided and is beneficial in the context of service learning. Consider a community that was forcibly removed so new stores could be built: Using objective numbers would not be able to correctly display the effects this had on those families. The quantified data would highlight the increase in economic revenue instead of correctly showing the hardships put on the families since it is hard to quantify emotional weight.
 
Correctly showing the afflictions on communities is why Strategic Positivism is essential when doing community service work. Strategic Positivism is the realization that science can’t be objective and that subjectivity in science can be intentional in helping those studied. Realizing that everything has subjectivity allows researchers to create emphasis on their claims to guide the information collected to a desired outcome. Let's return to the thought experiment given earlier about the families being displaced. Using strategic positivism, information can be collected and presented in a way that could benefit those families by presenting the extent of the wrongdoings and earning reparations. In hindsight, this concept of presenting data with a goal in mind makes sense, but it was something I never really considered before considering my very objective mindset.
 
In the second half of the class we learned about our community partner Rashe Malcom, the owner of Rashe’s Cuisine located in the middle of Triangle Plaza. She is a community member in East Athens and is proposing a plan to revitalize Triangle Plaza into a commercial center where the community will be able to invest in themselves. She plans on adding a grocery store, a community garden where people can learn to grow their own food, and an open kitchen which allows for people to gain the skills necessary to start their own business in the area. This plan is vital to the health of the community as Inner East Athens is in a food desert, a community where their nearest food source is an unreasonable distance away. Our class is tasked with providing Rashe with local geographic information of Inner East Athens so she can present the information for further grant money. Grant money previously has been given to Five Points and Downtown Athens in large amounts while Inner East Athens has been grossly overlooked. The Inner East Athens is not considered commercially viable and is at constant threat of gentrification from the ever growing UGA student population. The information we can provide can help Rashe showcase the area as a viable center for commercial business to not only improve the lives of the people living in the area but also help strengthen the community as a whole.
 
A large portion of our class was trying to figure out the parameters of our project with Rashe. Besides the frequent talks on what information we should provide, we as a class have been wrestling with how we should compile and use the information we collect. This falls onto strategic positivism to guide our research to meet Rashe’s goals instead of a removed objective stance that positivism would create. As students at the University of Georgia, we have an outsider's perspective that also can be seen as perpetrators to the gentrification in the area. It is important to present the information in a way that not only helps Rashe and her goals but keeps locals informed and benefiting from our information. Some ways our class is trying to put emphasis on our research is by making sure to explore how people in the community are affected by mapping out food sources, walking distance to stores, percentage of ownership of land, and other ways to show how the population demographics is faring compared to the rest of Athens. Highlighting and presenting this information is strategic positivism as it focuses on presenting the side of Inner East Athens that was being neglected with the goal of benefiting the area. Hopefully, the information we will provide will result in Rashe getting the grant money she is aspiring for the betterment of the Inner East Athens Community.

Keywords: East Athens, Strategic Positivism, Inner East AthensReferences:
Wyly, E. (2009). Strategic Positivism. The Professional Geographer, 61(3), 310–322.
