---
title: "What does community mapping praxis look like?"
date: "2024-06-06"
author: "Shaifali Prajapati, Spring 2024 Community GIS Student"
---

By Shaifali Prajapati, Spring 2024 Community GIS StudentI’m currently a student in the Community GIS class, pursuing my first year as a PhD Geography major at the University of Georgia. Even before attending UGA, learning about the ongoing work Dr. Jerry Shannon’s Community GIS class has been doing with the Linnentown Project made the course stand out to me. Students across different iterations of classes each year were able to utilize GIS as part of efforts to bring the stories of the people of and connected to Linnentown to the surface. I was intrigued to hear about a course that strives to integrate service-learning and GIS together, guided by community mapping and critical GIS. While I took several GIS courses as a Geography major in undergrad, all of them focused on learning to use various associated software through projects meant to emulate topics students would use for layered spatial analyses geared towards industry job prospects. Beyond completing deliverables for the labs, there was a lack of instruction in understanding why and how these processes were carried out. Considering all of these factors, I had set my sights to take this class if I ever attended.
 
For this semester’s Community GIS class we’re working with community partner Rashe Malcolm, the local business owner of Rashe’s Cuisine located right in the Triangle Plaza area of Inner East Athens. We’re developing a project to aid in her proposal to revitalize Inner East Athens with consideration to the already-established culture and demographics in the neighborhood. As part of this project, we are working to provide a profile of Inner East Athens through mapping current demographic and business dynamics, processes of studentification (similar to gentrification in which the needs of student populations of higher education institutions drive social, cultural, and economic displacement of local residents), property ownership and food access affecting the area (Pickren 2012).
 
While I’ve had prior experience working on community-based mapping, it is through this class that I’ve been able to take part in the praxis of community geography by applying critical theories of mapping with a critical lens on GIS through attention to conducting inclusive research. This blog itself is one aspect of this ongoing process to critically reflect on the implications of our work. So far, we’ve discussed and reflected on being conscious of using GIS through a critical lens. One of the core ideas we’ve been paying attention to is avoiding extractive (extraction of knowledge and resources) research and instead striving to carry out inclusive (mutually beneficial) research that examines implications of the research we’re doing for the people and places that are being studied. Some of the ways we’ve been conscious of these implications are through conducting interviews with prominent local figures also advocating for Inner East Athens to gain their perspectives on the prospects of revitalization as well as key concerns affecting the area. We also took a trip to learn about the Inner East Athens community and the historical legacy of Triangle Plaza from Rashe. As Rashe was guiding us through locations where she was planning for revitalization by building a community garden, grocery store, and affordable housing, I was able to situate myself in the actual locations we’ll be collecting data for and have a more nuanced understanding of local business owners and residents from Rashe’s perspective.
What stuck with me most during this visit is Rashe pointing out murals dedicated to women in the neighborhood that were commemorated for their strong community leadership, and her dedication to continue those efforts as a community leader herself.
 
With these informed perspectives in mind as well as our own perspectives of being students and residents of Athens, we are using our skill sets as a class by researching, compiling, and presenting spatial dynamics that Rashe has requested for her plans of continuing development in this community. Throughout this process, I really appreciate having discussions with Rashe as a class because it gives us the opportunity to hear her thoughts directly and time for us to ask questions. Additionally, getting feedback from her and the interviewed local figures on our project deliverables has been an integral part of approaching work with a critical perspective centered on community partners through working with informed perspectives and having strong communication. My hope is that our project is helpful to Rashe and that future classes can continue working with her in her goals to revitalize Inner East Athens, and I’m curious to see how the project develops and changes over time as well as how Inner East Athens is viewed and the people residing there view their neighborhood themselves.
 
Presently, as we’re nearing the end of class, I’m glad to be able to take part in this unique blend of learning and practicing GIS. While it can help with job prospects through the project management skills we’ve gained as a class along with learning how to use GIS software and carrying out spatial analyses, the goal throughout the semester to me has been to guide students to critically consider the impacts of what it means to be “doing community geography ” (Fischer 2022).
 
 
Keywords: community mapping, Critical GIS praxis and pedagogy, inclusive research

References:​
Fischer, H., Block, D., Bosse, A., Hawthorne, T. L., Jung, J. K., Pearsall, H., ... & Shannon, J. (2022). Doing community geography. GeoJournal, 87(Suppl 2), 293-306.
 
Pickren, G. (2012). “Where Can I Build My Student Housing?”: The Politics of Studentification in Athens-Clarke County, Georgia. Southeastern Geographer, 52(2), 113–130. http://www.jstor.org/stable/26229005
