---
title: "approaching the task of planning a large-scale group project"
date: "2024-04-25"
author: "Radu Casapu, Community GIS Student Spring 2024"
---

By Radu Casapu, Community GIS Student Spring 2024I think we’ve all done class group work in the past where no one can work together and no good ideas come out of the discussion. You leave the class wondering, “Did our group just not mesh well?” or “What is the professor even asking of us?” It can certainly be frustrating to propose group work and end up with a less-than-ideal end result. While I don’t claim that there will always be a solution to this, I found that through our collaboration and group discussions, we were able to overcome these issues in our UGA Community GIS class. So how were we able to do it?
 
For context, our Community GIS class took on a challenging project this semester, working with East Athens business owner Rashe Malcolm in researching and analyzing data involving the neighborhood as she hopefully looks to build a grocery store and community garden for the historically Black neighborhood. Her idea is not simple - it will take into account food accessibility, gentrification, and business ownership, among other things. Rashe’s got plenty on her plate, so we as Community GIS students accepted the challenge.
 
First and foremost, we had to make sure that our project does all it can to be to the utmost benefit for Rashe and gets her approval through every step. We applied a valuable method known as co-production of knowledge, which would best help us work in the environment of multiple parties being involved. After all, “High-quality co-production requires frequent interactions among participants to occur throughout the process” (Norström et al., 2020), therefore taking in the input of everyone involved. The strategy of co-production emphasizes that both parties involved should bring knowledge and ideas to the table when possible. That way, the final product brings more value to everyone, including both Rashe and us students. Before even asking the questions for the project, we made sure to collect as much experience and knowledge as we could through various means, whether it be interviews with community leaders or on-site exposure. With all that under our belt, we reached the most daunting part yet: the planning process.
 
We allotted ourselves multiple class periods to work through this process. As the saying goes, Rome wasn’t built in a day. We needed time to disassemble the pieces of the project and then put them back together in a way we could handle. Our first task was brainstorming questions. These questions involve what we are trying to find out through our project. The goal here was to come up with as many as possible - we would make them more defined and concise later - but at that moment it was best to simply get everyone to ask questions. This way we can see our project through every perspective. Through our multitude of questions we practically got to see the thought process of every group member. There are no wrong questions, but there are very many right questions that could be asked. After a lot of discussion between each other and together with Rashe, we steadily narrowed down some questions, combined others, and got to a few solid ones that encompass all that we want to research.
 
Next, we brainstormed potential data and methods. For every question we thought of the different ways it could be answered. These methods don’t necessarily have to be directly answered by GIS, since even though our class is centered around GIS software, not every student comes in the class with the same knowledge or background. Technical skills vary, college majors vary, and obviously our personal experiences are all different so we will have different ideas. This is an important value of Community Geography in general, which as Fischer et al. (2021) point out, promotes flexibility and diversity of methods when approaching a project’s goals and research questions. We worked through our ideas and assessed how feasible they were and which were our favorites. We went around and identified our favorites from other groups and gave edits or suggestions on how to improve them.
 
Finally, with questions and strategies established, we could come up with centralized goals that we want to achieve. We had to do many rounds of categorizing and dividing up the questions and strategies but ultimately we found five paths we could take to address all our goals. These five paths would become our 5 groups in which we take on different aspects of the project. And so, within a few rounds of brainstorming and discussion in our groups, we were able to get a good start on our project. This was simply possible through the cooperative effort of everyone, making sure that it made sense for us as researchers splitting up this work and for Rashe, who will benefit from a well-organized final product which provides just as much valuable information from each of the five aspects of the study.
 
My conclusion from this experience is that there are a few things we can take on how to have more productive group work. Firstly, use your groups’ differences to your benefit through different experiences and perspectives which allow for entirely different solutions which you might have never thought of otherwise. Stressing the importance of contributions from all parties involved is a crucial point of co-production, whether it be through asking questions or discussion. In addition, don’t go into the discussion expecting a final product. It can take a while, and it might not come through in the way you expected it, and that’s perfectly fine. Refining our questions or goals was a very steady process which we did over time by involving everyone. Finally, be willing to take risks or unexpected approaches. Bringing a completely new question to the table might spark discussion on something that had not come up at all before. Once again, the power of involvement in co-production allows for this to come from anyone engaged in this research on any side.

Radu is a third-year undergraduate student majoring in Geography and pursuing a certificate in GIS science, interested in urban planning and mapping.

Keywords: Co-production of knowledge, research planning, community projects, Inner East Athens

References:Fischer, Heather, et al. “Doing Community Geography.” GeoJournal, vol. 87, no. S2, June 2021, pp. 293–306. https://doi.org/10.1007/s10708-021-10457-8.
​
Norström, Albert V., et al. “Principles for Knowledge Co-production in Sustainability Research.” Nature Sustainability, vol. 3, no. 3, Jan. 2020, pp. 182–90. https://doi.org/10.1038/s41893-019-0448-2.
