---
title: "My first experience in east athens"
date: "2024-02-26"
author: "Peyton Gunn, Community GIS Student in Spring 2024"
---

By Peyton Gunn, Community GIS Student in Spring 2024

For our Community GIS class this semester, we are studying the area of East Athens. This area is relatively east, but not in the way I was thinking when I first joined the class. Personally, I thought it was referring to the area near where I lived off of Barnett Shoals, and when I first heard the words East Athens used, I thought “Whoa, this is awesome! I know this place so well!” Little did I know that I was completely wrong, and that the area we were talking about was one I had never even heard of before.

​East Athens is actually very close to campus, but seems very isolated when driving around. Some places other people might know are near it are the North Oconee River Parks and Firefly Walking Trail. There are many ways to get to it, but I would say the most common ways people get there is by turning off Oconee Street or North Avenue. From there, many roads can be used to traverse the area in what is considered East Athens: Peter Street, Vine Street, Arch Street, First Street, and Nellie B Avenue. We had talked about the area once our class really got more involved in studying East Athens, and it seemed like a decent place. We had been looking at the area to hopefully help Rashe with some government funding for the area, but exactly what she wanted to do I wasn’t sure of yet. A nice shopping area with Rashe’s Cuisine and a barbershop, plenty of houses for people to live in, and a police station nearby to keep the area safe. These were my perceptions of East Athens before I went there, but now it was time to see it for myself.

On a Friday in late January, a few different classes made the trek over to Triangle Plaza, the shopping center to which I alluded before, and it felt a lot different than the picture online. Lots of people walked around the streets like they were sidewalks, which struck me as fascinating just because that wasn’t something I had not seen on Google Maps (which would be hard to depict, but that was my only frame of reference). Once most of the people had gotten there, we went into one of the rooms of Triangle Plaza, which looked like it was being used as a community center. Rashe, our East Athens tour guide for the day, told us that in the past it has had multiple different uses. It was originally a barbershop, hence the raised flooring at the front. Afterwards, it was a laundromat, hence all the outlets along all of the walls. It has had other uses, but those were the ones that had lasting impacts of the room. It was interesting to learn this, as it was kind of learning about the history of the geography of just that room, with so many uses showing what was important to the people at the time.

Once we left the community center, we went up to the outside of the building to a mural that had been painted by Broderick Flanigan of some of the most important advocates and civil rights activists from the East Athens area. Jessie Barnett, Evelyn Neely, Miriam Moore, and Virginia Walker were all very important black women of Athens civil rights, and them being on the main business building in East Athens shows that they were very important to not just the progression of Athens as a city, but East Athens as a community. After this, Rashe had a wonderful proposition for us. She said she wanted to build a multi-use building outside Triangle Plaza that had a laundromat, grocery store, and apartments on top of them. She explained how she would keep the rent of those apartments low by using the potential renter’s income to see if they make enough money to pay it, but not enough to where the rent would increase to where no one else could afford it. She said she needed our help, though, with maps and diagrams to show county commissioners and other important government officials to get grants to pay for the ideas she had for the area. This is very exciting, as what we will be doing is going to have a real life and long term effect on the community for the better, such as helping the process of having a central place they can go to do their everyday needs, as well as add living space that would not be there unless we were, which can help people live where they want that is affordable.

Learning about East Athens has taught me a lot about being aware of where I live. Certain aspects of East Athens definitely stuck out to me, such as the strong African-American pride exhibited in a lot of businesses and murals as well as a strong community with people everywhere talking and walking together. The goal of this project is to help the people of East Athens grow more as a community, as well as adding amenities that currently are not there, such as a grocery store and laundromat. Using public opinion and GIS work could help figure out exactly where amenities can go to have the most impact on the people that live there. Personally, I believe this will definitely move the community in the right direction going forward. Like I said, I had never heard of or seen this area before, so it was interesting getting to know the place and learn more about it, and I cannot wait to be more involved in the community as we move further towards the project. 

Peyton Gunn is a third year geography student at the University of Georgia pursuing a degree in geography with a minor in geology.
