---
title: "A student researcher's perspective on studentification"
date: "2024-04-25"
author: "Paige Overmyer, Community GIS Student Spring 2024"
---

By Paige Overmyer, Community GIS Student Spring 2024As we are over halfway through the semester in my Community GIS class, a collaborative research course studying a section of Athens, I have gained a better understanding of what it means to be an intentional researcher. We’ve spent weeks reading about the science of displacement, positionality, and ethical mapping, and have just finished the planning phases for making a detailed profile report on Inner East Athens (IEA). Over the years, IEA has been experiencing demographic shifts and housing pressure. Due to this, it is critical to make maps and charts displaying businesses, food access, and demographic dynamics that can properly aid future development plans and maintain the core community structure of this area.
 
The concept of studentification introduced in this class from a reading by Graham Pickren has deeply resonated with me, and I strive to use this newly found knowledge to be a better researcher both in this class and in the future. To understand studentification, it’s critical to first understand gentrification: the process of displacing people from an underserved community to bring in wealthier inhabitants and thriving businesses, without sharing that wealth with the original community that was driven out. Studentification involves displacement driven by the needs of students, leading to changes in community dynamics through the repurposing of housing, amenities, and recreation to better accommodate growing student populations from nearby colleges. These go hand in hand because studentification “builds a student’s cultural capital that leads them to be gentrifiers later in life” (Pickren, 2012).
 
As I read Pickren’s paper on studentification, I was immediately uncomfortable. That discomfort stemmed from being confronted with my own actions that promoted students dominating an area when I went to college in Milledgeville. I was complicit and even advocated for nearby housing to be more accessible to students when I lived in a historic home with four other women and was faced with city fines from having too many unrelated roommates in a single home. My thought process was that since my college was the driving force in tourism to the city (it is not), students should be able to have housing that is close to campus. I felt so threatened that locals didn't want us there, but I didn't consider the fact that students have been slowly pushing them out, deteriorating their sense of community. I tried to fight for something I didn’t fully understand because I was clouded by my own wants, but I am thankful that I have been more exposed to inner workings (and impacts of) studentification and gentrification through readings and community interactions.
Studentification isn’t as simple as students deciding to slowly migrate into underserved areas, it’s a complex process that has political and environmental components. As one of the largest universities in the state, University of Georgia has an immense amount of money and power, enabling it to prioritize serving students’ educational needs by acquiring land to enhance school programs and accommodate a growing student population. This puts the university in conflict with the Athens community as both fight over the best utilization of the same land. Other key stakeholders include environmentalists, who prioritize the safekeeping of greenspaces around the community. From the reading, I learned that this group largely helped in developing the 1999 comprehensive plan for Athens by keeping rural areas rural to preserve the community’s rich greenery. This meant that redevelopment would have to be located in urban areas where services are already in place. Areas that are underserved with affordable housing are now targeted since they’re seen as the cheapest to redevelop. Though this process is meant to benefit students, the reading made me realize that it’s not (completely) student-led.
 
Our class has spent this semester learning how to properly research the East Athens Community with the help of Rashe, a community member who owns a restaurant in the area. Being intentional with researching the East Athens Community means delivering a report while understanding the biases we may have considering our position as students at an institution that promotes gentrification. Though gentrification may happen in this area regardless, it’s critical to this community that the changes are beneficial and do not drive anyone out. Since we are outsiders in this area, we are continuing to talk to those in and around the community to get a better sense of what they want out of this research. I was part of a group that interviewed Broderick, a community organizer, artist, and Executive Director of the Economic Justice Coalition in Athens. Listening to his journey on making positive change within the city reinforced my thinking that the university has a lot of power over the community, so a lot of decisions that are made are driven by the goal of university prosperity. As an institution, it’s crucial that we do everything we can to be intentional and understand how our expansive actions affect locals.
 
I’m in a group within the course working on mapping gentrification and studentification in Inner East Athens and how it compares to the county as a whole. While this is a daunting task, it’s one that will be able to highlight demographic variables over the last decade or so to provide a clearer picture of trends. We are planning to build a matrix that quantifies the susceptibility of an area to gentrification using prior research models. Throughout this process, I aim to be both inquisitive and considerate, as we map out and make visuals of the changes East Athens has experienced as well as its future potential. Both residents of the Athens community and students deserve to know the impact of gentrification, especially since student needs are what drive these changes that inevitably affect the entire community.
Paige is a 2nd year graduate student studying Disaster Management and Public Health. She is interested in hazard mapping and infrastructure resiliency, with a focus on prioritizing protection for vulnerable populations.
Keywords: Studentification, Gentrification, East Athens, GIS

REFERENCES: Pickren, G. (2012). “Where Can I Build My Student Housing?”: The Politics of Studentification in Athens-Clarke County, Georgia. Southeastern Geographer, 52(2), 113–130. https://doi.org/10.1353/sgo.2012.0019
