---
title: "community gis and studentification in east athens"
date: "2024-04-25"
author: "Kali Lyons, Community GIS Student Spring 2024"
---

By Kali Lyons, Community GIS Student Spring 2024When deciding which course to take, this class stuck out to me as it was focused on providing a real-world experience. We would be building a project from the start and would responsible for data sourcing, creating deliverables, and working with one another and community members to create useful projects. I expected most of our class time to be spent working independently on computers with occasional communication with community members to guide us. I was wrong. Before we even started talking about the topic of our project, Dr. Shannon helped build our knowledge of research methods. Rashe Malcolm, a local entrepreneur and proponent of East Athens, helped build our knowledge of local history, introduced us to East Athens, and helped direct our goals.

As an Athens resident, I was aware of gentrification in Athens but was not aware of the concept of “Studentification,” or even the full extent to which gentrification had taken place. I have only lived here for three years and hadn’t visited much prior to moving here for school so, I had no concept of what had changed. In the time that I have lived here, though, there have been apparent changes made for the benefit of those that attend the University. Apartment complex after apartment complex has been built. Many of these places are only available to those who can afford them, namely students who receive financial help from their parents.

In Athens, historically underprivileged communities that are predominantly occupied by people of color have been the most affected by this process. The Lodge, for example, located on North Avenue was once a mobile home park. Residents were forced to relocate, or even worse, ousted from their homes that were deemed unfit by local zoning ordinances as they did not meet the codes at that time. These displacements caused compounding negative effects that community members are still striving to overcome today. 
 
The severity of studentification has been a major focus in this class. In one of our very first labs, we used house sales data to track how the price per square foot of home sales in Athens-Clarke County has changed over recent decades. Although prices generally increased across Athens-Clarke County, there was an increase of at least $50 per square foot in Inner East Athens specifically, with some homes selling for at least $500 per square foot. Increasing property taxes have added to the burden, forcing many residents to sell to developers. This can be detrimental to a community that is already under so much stress. The loss of familial homes and affordable housing from local residents to temporary students as rental homes can have a trickling effect leading to distrust and disengagement with the community. 

As we visited Rashe Malcolm at the Triangle Plaza, the heart of Inner East Athens, she emphasized how a once thriving business community has been lost in recent decades. Options to purchase foods are limited, as convenience stores are the primary sources for purchasing foods and most grocery stores require travel by car or bus. Travel time, time allotted for cooking meals, and the cost of fresh food may also be factors discouraging IEA residents from consuming nutritionally dense foods. Affordable available foods are usually restricted to processed foods that provide almost no nutritional value. A local grocery store (developed for community members), a thriving community center and garden, and affordable housing will hopefully restore Inner East Athens. Her hopes are to reinvigorate her community and to increase community engagement.

My team is working to create deliverables that accurately reflect the current and historic demographics of both Inner East Athens and Athens-Clarke County. Changes in demographic variables, like income, renter/homeowner status, and rent burden over the past 20 years might indicate how the draw from the University is affecting different areas of town. We have yet to produce a final product, but I am excited to aid in the development of supporting materials for Rashe’s plans. Aside from creating real usable material as a final project, this class has also been heavily group oriented. The research questions, methods, and plans have all been meticulously made through the course of the semester by the students (with guidance of course). It is challenging but has also been a valuable experience that I feel will be applicable to real world GIS work.

Kali is an undergraduate student at the Odum School of Ecology pursuing a GIS certificate.
Keywords: studentification, community GIS, housing
