---
title: "Research in Brooklyn Cemetery: Honoring its residents through the use of GIS"
date: "2025-12-12"
---

Zachary Mitchell, CURO research assistantOver the course of the fall 2025 semester, I have had the privilege to work with Brooklyn Cemetery through the Center for Undergraduate Research (CURO) at the University of Georgia. Brooklyn Cemetery is one of the first African American cemeteries in Athens, Georgia. It was established in 1882 and currently resides behind Clarke Central Middle School and Holy Cross Lutheran Church on Baxter Street and West Lake Drive respectively. The cemetery serves as a resting ground for residents of the Brooklyn and Hawthorne area of Athens, both of which are located on the west side of town. As time has gone on though, not much maintenance work was done over the years, which has led nature to overtake the cemetery. Tombstones have fallen over or are completely missing, signage has rusted over due to age and exposure to the elements, and lots of shrubbery has overtaken the cemetery. The scope of my research had to do with improving the state of the cemetery, and the means of which I did this is through the use of Geographic Information Systems (GIS) with Dr. Jerry Shannon and Owen Setterlind.
More specifically, the main task we were given was to create subsections in the cemetery. The primary goal in the creation of these subsections was to improve the accuracy of where gravesites are located on a map. We first tried to do this through using an RTK unit, but since there is so much canopy cover over the cemetery (it tended to stay around 15 feet off of a person’s actual standing location), we found it easier to create subsections using more traditional methods.
We created a method to create subsections by locating trees using land surveying techniques. The first step was to find trees with a general circumference of 5 feet. These trees are big enough to be distinct markers compared to the countless small trees in the cemetery. From there we used a tape measure and compass to gather the distance between trees and azimuth between trees. By gathering this data and marking subsequent trees, we could create a web of distances to find the exact point of specific trees in the cemetery. This was one of the main skills I learned over the course of my research, data collection. It’s super important to have good data collection skills as someone who works in GIS. You want to make sure your field data is accurate, precise, and accounted for before you begin to work on it in the lab.
Once we had compiled our field data, we began to process said data in the lab. We did this by using R. With so much data we had collected and compiled into a spreadsheet, it would be a lot easier to automate the process with R rather than manually going through the process. The script would perform the logic of reading the spreadsheet data and iterating through the data up to 100 times. From there it would calculate forward (which means to compute new coordinates for unknown trees based on known start points, distance, and azimuth). Each tree was located relative to at least two others. Once all tree locations has been calculated, the script averages these out to a single point. Once the script is completed, it generates an output csv file.
After we obtained this file, we put it into QGIS as a delimited text layer. This displayed the tree data accurately. We then used those points to create subsections. We did this by creating a new polygon layer and enabling snapping in QGIS to edit it. The team decided to create 3 different subsections for the section of the cemetery we were working in. Once we had our subsections layer made, we exported it from QGIS and uploaded it to ArcGIS Online. We then went into the field to do some ground truthing to update gravesite locations and put them in their appropriate subsections if they weren’t already mapped as being in there. 
What I have learned from my time as an undergraduate researcher with a focus on GIS is that GIS matters in the sense of community. These subsections can be used not only as ways to better locate gravesite locations, but they can also be used by the community. Say if someone wanted to adopt a subsection and maintain it. This could promote the widespread upkeep of the cemetery and bring more light to the people buried there. By utilizing GIS, we can create a memorialization of people’s histories who could be forgotten to time.
