---
title: "Black Life in Athens: Acknowledging Pasts, Recognizing Presence,and Amplifying Futures through Community Mapping"
date: "2025-04-30"
author: "Madi McFarland"
---

by Madi McFarlandWhen I registered for Community GIS with Dr. Shannon earlier this spring, I didn’t give it too much thought. The class had an open seat, filled the last gap in my schedule, and would give me the final credits I needed to complete my certificate in Geographic Information Science. I did not expect my final geography course to fundamentally change the way I thought about my position as a student at the University of Georgia.

Coming into this class, GIS was a set of tools I was learning to use. I dutifully sat in front of the high performance computers during weekly lab periods and completed assignments accompanied by step-by-step instructions on how to present geographic data that I was mostly disconnected to. While it was fundamental for gaining skills in using programs like ArcGIS, it was often technical, abstract. This semester, I had the opportunity to become personally invested in the data. It wasn’t just about mapping features, it was about mapping lives, histories, and absences.

I found myself making regular trips to Brooklyn Cemetery, a historically Black burial ground quietly nestled west of the University of Georgia campus. The site is more akin to a hiking trail than what you might envision when you think of a cemetery. In place of the neatly manicured lawns and paved roads of nearby cemeteries like Oconee Hill, there are piles of brush and dusty dirt pathways. PVC pipes by patches of sunken ground denote the locations of unmarked graves. Brooklyn is maintained by a small group of dedicated stewards that serve as caretakers for the site and advocates for the families interred there, but apart from that, the city of Athens has seemingly forgotten about it. This is not by coincidence.
Katherine McKittrick’s paper “Plantation Futures” describes the legacy of the plantation- not just on a material scale, but as a conceptual framework that continues to manifest in structures of power that disenfranchise people of color to this day. These systems predominantly see minorities from low-income communities doing the bulk of the work for little pay, while a small number of people in charge profit. They can be incredibly difficult to escape, as they inherently enforce a dichotomy of poverty and power. After reading the paper, I began recognizing plantation structures that quietly persist all around us- prisons, agricultural industries, resorts, and even universities.

As a student at the University of Georgia, I’ve come to realize the city of Athens as one such plantation geography, shaped by a deep history of land dispossession and enslavement. Historically Black neighborhoods and cultural areas have faced decades of erasure and displacement, often at the hands of administrative action by the school. “Hot Corner”, located on the intersection Washington and Hull downtown, was once the most prosperous Black business district in the city. Black presence is still very much there, but it has changed shape through gentrification and expansion practices. Linnentown, a lively neighborhood along Baxter Street, was seized by the University of Georgia in the 1960s to make space for new residence halls. More recently, an on-campus renovation project at Baldwin Hall uncovered the remains of 105

individuals of African descent- likely those of enslaved people whose labor built the University. This discovery was tremendously mishandled by school administration, who attempted to quietly reinterred the remains at a historically segregated cemetery away from the eyes of the media and likely descendants.
Despite major displacements and mishandlings, it is important to recognize that Black life in Athens persists. “Cartographies of Black Presence: Mapping Praxis through Community Geography and Black Geographies” by Rachelle Berry et al. presents GIS as a powerful tool for preserving Black history and elevating Black futures. Rather than focusing solely on displacement, there is an opportunity to center livingness. As UGA affiliates working with the legacy of Brooklyn Cemetery, effectively doing so requires both a dedication to amplifying the stories of the people buried there and a commitment to repairing decades of broken trust between the University and Black Athens residents.

This class pushed me to confront my own positionality. I am not from Athens, I am not a person of color, and I have no personal ties to Brooklyn Cemetery, but as a student, I am a participant in a system that has long benefited from Black erasure. This recognition comes with responsibility. As outsiders, we must seek to engage with those whose histories have been suppressed and give them agency in how their spatial histories will be represented. Community mapping asks us to consider who we are in relation to a space, and what it means to work with communities, rather than just mapping on them. I now carry a deep awareness of how my skills can be used to not just represent geographies, but to advocate for the histories within them.

Madi McFarland is a fourth-year student at the University of Georgia. She is pursuing a dual Bachelors and Masters Degree in Ecology with a GIS certificate.Keywords: plantation geography, cartographies of black presence, positionality​
