---
title: "How Geographers are increasing visibility in Brooklyn Cemetery"
date: "2025-04-30"
author: "Zachary Mitchell"
---

by Zachary MitchellThe definition of Geography is that it is the study of the physical features of a landscape. Geographers represent this study of the landscape through many different means such as maps, spreadsheets, scientific research papers, etc.. Geographers can provide an analysis and study of the physical features of a landscape, but what about the stories behind those landscapes? 

In the Spring 2025 semester I had the privilege of taking the Community GIS (Geographic Information Science) course at the University of Georgia. This is a service learning class that provides students with an opportunity to apply the academic skills that they have learned to a community-identified problem or need. In this course, our class was tasked with telling the stories of families buried in Brooklyn Cemetery. Brooklyn Cemetery is a historically black cemetery that has been established in Athens, Georgia since 1882. The cemetery is directly behind Clarke Central Middle School and Holy Cross Lutheran Church . The cemetery isn’t directly visible due to this, and our goal in the course was to create more visibility through geographic analysis . We analyzed the space through many different types of GIScience-based skills such as data collection, QGIS, and ESRI ArcGIS Story Mapping, but the most important skill we had to encompass in our time in the course was the way in which we interacted with the community and its members. 

At the start of the course we began to hone our skills of how to respectfully work in the community through a geographic viewpoint. One of the papers we read that I found to be most helpful in learning this skill was “Doing Community Geography” by Heather Fischer et. al. In the reading, Fischer provides us with three principles to abide by when doing CG (community geography) work: Who, Why, and How. The Who describes who we’re working with in our CG work, in this case the Brooklyn community. This includes living descendants of family members who are buried in the cemetery but also those who work in/with the cemetery. One person who comes to mind who has helped guide the work we have done is one of the founders of ‘Friends of Brooklyn Cemetery’, Linda Davis. She has helped restore, rebuild, and commemorate the cemetery grounds and the individuals that are laid to rest there. The Why is the justification and benefits of our work in the community, and the work that Ms. Linda and Friends of Brooklyn Cemetery have done aligns with ours; we want to help increase the visibility of Brooklyn Cemetery by commemorating the stories of the families who are buried in the cemetery. We’ve attempted to increase the visibility of Brooklyn through community events where we presented the results of our findings to living family members. The How is the types of geographic methodologies that we use to do our work, in this case data collection and the use of ArcGIS Story Maps. We used ArcGIS to create maps of the cemetery and the residences of family members, giving a brief history of their lives.

In our research of the families buried in Brooklyn Cemetery, we decided to analyze the 7 largest families in the cemetery. My group was tasked with researching the Daniel family. We started our research by gathering data on just who was buried in our family plot, that of which we found in a directory of Brooklyn Cemetery created by Meriwether Rhoades. In the directory we found the names and birth/death dates of 10 individuals from the Daniel family. From there we began to collect data on the family members by using sources such as FamilySearch, FindAGrave, City Directories, and Census entries. We found data on family member’s residency, their relationship to the head of the residency, birth place, race, sex, marital status, occupation, literacy level, and more. Once we had gathered a satisfactory and complete amount of data on our family members, it was time to create a story map to help tell the individual stories of family members buried in the cemetery.

ArcGIS StoryMaps is a story authoring web-based application that allows you to share maps in the context of narrative text and other multimedia content. In general our class’ story maps all follow the same structure: an introduction of the family, a family tree showing different generations of family members that differentiates between those who are buried in the cemetery and those who aren’t, a map tour of the gravesites, family history over different years, and a spotlight on a specific family member. For the Daniel family, their history in Athens-Clarke county traces back to 1880, where Philip and Margaret Daniel’s marriage registration was found in FamilySearch. From there we found multiple years of census data that showed where certain family members lived, and even some death reports showing when family members passed away. For example we learned the histories of Judge and Settie Daniel, 2 long time Athens- Clarke county residents. We were able to find multiple years of their family history including census records spanning 50+ years and marriage/death certificates. We were also able to find information on their children and grandchildren through census data.

In the grand scheme of my time in the course, I feel as though the work we have done in helping create visibility to Brooklyn Cemetery is truly valuable and important. By letting Brooklyn cemetery continue to be vulnerable to being forgotten due to no visibility by the community, these stories face the risk of being forgotten. Geographers can help increase visibility of the cemetery through creating maps and outreaching to the community to show their findings and garner more interest in telling and preserving these stories. By doing this, we can create a memorialization of people’s histories who could be forgotten to time.
​
