---
title: "Reflections on work with brooklyn cemetery"
date: "2025-03-15"
author: "Olivia Yahne"
---

by Olivia YahneThis semester my classmates and I are participating in a service-learning course in which our objective is to research and compile information about the individuals/families of those buried in the Brooklyn Cemetery here in Athens-Clarke County. While we have spent a majority of the semester in the lab, collecting and compiling data, we have also completed our first site visit to Brooklyn Cemetery in order to get a better understanding of the environment we are researching. Our class then split into groups, dividing up the family plots, so we each had specific people to research, and my group was assigned the Cole/Woodall family which consists of six individuals. We began this course by interacting with some readings by Donna Haraway, Norström, and Cunliffe and Karunanayake to gain a better understanding of why this project is important, how we can provide unbiased information when conducting a project like this, and how our findings will affect the Brooklyn Cemetery community. The next week we spent familiarizing ourselves with the project (and what we hope to achieve with it), data we would be utilizing for this course, and dusting off our GIS skills (mainly in QGIS).

I can’t speak for the rest of my classmates, but the first few classes I truly got a sense of how important this project was simply regarding the lack of information available to us when trying to collect data. In addition, once we completed our trip at the Brooklyn Cemetery, I was surprised at the conditions the environment was in; the littered pathway, the lack of identification markers, and the outside factors such as the school and house plotted on the sides of the cemetery. The next few classes consisted of more focused research, where we personally looked into a specific family to create a solid foundation to ensure our baseline data (conducted by previous members of this GIS course) was correct and once that was ensured we broke into our small groups. We have utilized FamilySearch, Athens city directories, Ancestry library edition, photos, etc. to compile background information about the individuals of our specific families including information ranging from their date/place of birth to how many hours they worked per week or if they could read/write. These past few classes have been wrapping up this compilation of data and our next steps will entail creating a digital archive and map of Brooklyn Cemetery.

This course and project have been particularly interesting to me as a lot of the recent classes I’ve taken have revolved around the “othering” of individuals/groups which is often prevalent in the landscape of these communities. It is evident with the geography of Brooklyn Cemetery as the conditions reveal past and continued acts of discrimination and prejudice, yet the current day efforts highlight the strive to preserve, improve, and empower the cemetery and the community. A particular class that stood out to me was when Dr. Shannon had Ms. Linda Elder Davis, the cofounder of the Friends of Brooklyn Cemetery community group, come speak to us about her experiences within the cemetery and its community. Her insights and connections provided valuable information that could not be obtained through digital archives in which she even provided contacts of certain descendants still in the area who might be able to provide further data. Her efforts and dedication once again drove home for me how important this project and service-learning projects as a whole are to communities on a multitude of scales.

In addition, a class that stuck out to me was the day after we did our first site visit to Brooklyn Cemetery where we discussed the experience. The conversation pertaining to the abundance of trees and the concealing canopy was a particularly interesting discussion as some people found that the number of trees further added to the concealment and secretion of the cemetery and the community it serves. Others felt like the opposite was true, that the trees not only added to the quiet beauty of the cemetery but also represented continuation of life and resilience regarding the intertwining of the gravesites and the trees. This project has provided me with readings that have expanded my understanding of the work geographers do and why they do it, the opportunity to improve my technical GIS skills by broadening my knowledge of software such as QGIS, and the ability to create something that will positively influence a historic landmark and the community involved. I am grateful for this opportunity and am looking forward to continuing to expand the archives available for Brooklyn Cemetery as well as helping restore a sense of identity in the community. 

Olivia Yahne is an undergraduate student majoring in Geography and Disaster Management. 
Keywords: Brooklyn Cemetery, data, research
