---
title: "GIS, Mapping, and Reese Street in Athens"
date: "2025-05-27"
author: "Jessica Muniz"
---

By Jessica Muniz

I'm a first-year student who spent the Spring 2025 semester conducting research in the University of Georgia's Community Mapping Lab (CML). My research focuses on creating a digital walking tour of the Reese Street Neighborhood, a historically Black neighborhood in Athens, Georgia, during the period of the 1950s. The project's objective is to assist the community with learning and remembering the neighborhood's history, especially the local youth.

After my acceptance to UGA, I was offered a CURO Honors Scholar scholarship. This fancy title means that I am in a four-year cohort, and we all conduct research on absolutely anything we choose. After taking Dr. Hysjulien's Introduction to GIS class, I instantly grew a passion, so I knew a research project with GIS would be a great idea. Shortly after the class, Dr. Shannon, the professor, Amber, the graduate researcher, and Jamie, my research partner, welcomed me into the lab with open arms.
 
In my first few weeks of researching, I read a graduate thesis by Ms. Amy Andrews. The thesis provided a good background of the Reese Street Neighborhood, allowing me to understand my future tasks. Next, I was given a huge spreadsheet that was a digitized version of the 1958 Athen's directory. My task was to compare the data in the spreadsheet to the original directory and ensure the data was accurate. We also started meeting with Historic Athens, a community partner, to discuss the semester's timeline and new ideas. I truly appreciated Dr. Shannon and Amber for always taking the time and providing instructions, especially when furthering my GIS skills.
 
As the semester progressed, my research role turned more qualitative than quantitative, meaning I dealt with more words than numbers. My new task was to do genealogy research on certain people and places. Simply, I had to learn as much as possible about certain people from historical records, newspapers, and images. In this process, I found a rhythm sifting through the websites Ancestry, FamilySearch, and Georgia Historic Newspapers. I also learned how to retrieve archival documents and images from the University of Georgia's Special Collections Library. Our meetings with Historic Athens and other researchers were essential in filling in the gaps or finding mistakes that I had found or made along the way.
 
Towards the end of the semester, my research partner, Jamie, and I presented at an undergraduate research conference called the CURO Symposium. Previously, I had presented on mini-research projects in Georgia 4-H, but no presentation was to the degree of undergraduate research. Indeed, I was nervous, hoping that my presentation skills would shine, and that I would not stutter. Nevertheless, Jamie and I had an amazing presentation, and the audience asked multiple questions, only growing my confidence. As the semester has come to an end, I am currently polishing the last edits of the 1958 walking tour.
 
On a final note, I have learned numerous lessons and skills this semester, but I will spare you the time and speak only of two. As I have stated countless times, I learned how to conduct genealogy and archival research, but these skills hit "very close to home." My mom's side of the family has lived in the Starr's Mill, Georgia area for many years. I have always wondered about our family history spanning to the days of slavery, as my mom's side of the family is African American. Now, through the mentorship and training of Dr. Shannon and Amber, I can trace my family history, and hopefully, create a website or walking tour of my own to teach my family about our history. Secondly, I learned the importance of resilience. As a freshman, college was a crazy adjustment, especially academically. The research lab allowed me to fail and try again. In fact, many of my facts would be slightly off, or I would have an incorrect picture. Nevertheless, everyone supported me, and I would, simply, try again. Truly, I am grateful for the opportunity to have worked in the Community Mapping Lab, and I cannot wait to see the future growth of the Reese Street Neighborhood project!
