---
title: "Learning and working with Brooklyn cemetery"
date: "2025-04-30"
author: "Riley Viskochil"
---

by Riley ViskochilThis semester I am taking community GIS, a class offered at the University of Georgia that is centered around community organizations through map making. Since I am majoring in ecology, most of my experience in GIS has been focused on wildlife and land use data. I thought this class would be more focused on the methodology of GIS or similar projects I have done. However, this class could not be more different from what I thought it would be. Throughout this semester I have learned valuable things about myself, the community of Athens, GA, and how maps have the power to affect peoples’ lives. This class has made me question my positionality as a student at the University of Georgia and a person outside the black community of Athens, as well as the roles I play in my community of Athens and in society as a whole. This has become clear in the community aid projects done in Athens and how we have worked with them.

​In early February, when the trees had no leaves and the cold air bit at our face, our class made our first trip to Brooklyn Cemetery, a historically Black cemetery nestled in the craze of Athens. Brooklyn started interring members of the black community of Athens in the 1800s and stayed active until the late 1970s. While we walked through the cemetery, our thoughts were accompanied by the crunch of leaves and thumps as our feet bumped into tree roots. Brooklyn has been a victim of severe neglect having been constructed in the aftermath of American chattel slavery and active throughout the era of Jim Crow. A typical image of a cemetery that I am familiar with is one of short grass and clear paths, an image of which Brooklyn does not possess. Compared to other cemeteries in Athens, where most of the people interred were white, Brooklyn did not and still does not have the same resources to maintain its grounds and inventories. Because of this, the cemetery has withstood extreme neglect and overgrowth. The paths are made of dirt, there are sunken and various unmarked graves, and vegetation and tall trees whose roots have intertwined with the grave sites are scattered throughout the landscape. This view was hard to stomach seeing it for the first time. I remember at this moment thinking that letting a final resting place fall into such disrepair was disrespectful to the memory of those buried there.

However, while still devastating and unjust to the people buried in Brooklyn Cemetery, I have learned this semester that it is also not fair to people that have faced oppression to view them solely as victims. Throughout history, people who have faced great adversities have triumphed in their fight for justice and equality. Many people have helped me come to see this but one notable person is Ms. Linda Davis, a member of the Athens community who works with the organization “Friends of Brooklyn Cemetery” that is helping to bring the history of the cemetery to the community. She has given us priceless knowledge and insight that we have used to work on our project this semester. At one meeting we had with her, she shared an experience she had one day in the cemetery. She remembered it being a spring day in which the trees’ leaves began to grow back and rays of light shone through the canopy that covered the graves. Upon looking up, she spotted a deer foraging on the grass. The deer noticed her and they held a moment of eye contact before the deer trotted away. Her story made me realize that although Brooklyn did not have the images of cemeteries that I am familiar with, it has its own sense of beauty in the face of neglect. The gravesites of families buried there have acted as a sanctuary that has cultivated new life. The roots of trees have intertwined with various graves and thus the essence of new life is connected to previous one. The vegetation supports animals in the surrounding area. While we do not have the resources to give Brooklyn a makeover, nor the will to disrupt the peaceful nature it has grown, there are other methods to give a sense of justice to those buried there. In this aspect arose the idea for our project this semester.

In previous years, other community GIS classes have compiled geographical data about the cemetery, and have located unmarked graves and provided coordinates for others. This semester, we have been more focused on the lives of the people there before they were interred at Brooklyn. Throughout this term, we have compiled genealogical data on a number of families in order to tell their stories. We focused on things like census records and city directories to find out more about them. By solely looking at a grave, you cannot tell how a person lived, but now with the information we have, we know different family relations, where they worked, and how they fit into their communities. It sounds silly to say, but seeing this information about peoples’ lives made the project seem more real. Through the use of the geographical data, we can see the routes they might have taken to commute to work. Although this was just a small part of a person’s everyday life, it is just one small detail we’ve come across that has fleshed out someone’s life.

The geographical and biographical data was put into ESRI story maps that show the family history and the lives they lived in Athens. We plan to present our story maps at Historic Athens history hour and tell the lives of the families of Brooklyn history, not just as victims of neglect, but everyday people who contributed to society, who loved and laughed with their family, and were valuable members to their communities.
 
Riley Viskochil | University of Georgia
Keywords: Community GIS, Brooklyn Cemetery
