---
title: "the role of 'community' in GIS Class"
date: "2025-04-04"
author: "Blake Burtzlaff"
---

by Blake BurtzlaffThis past semester, I enrolled in Community GIS. Going into this class, I assumed that it would strictly deal with GIS, like the other classes I have taken, while on track to complete my GIS certificate. However, I have been surprised by how important this class's “Community” aspect has shaped my learning experience. This class is not just about doing labs with existing GIS data, but about learning to work in groups on meaningful community projects and educating myself on how this work can impact a certain community. As one of our readings states, “Community geography (CG) fosters collaboration between researchers and local groups, creating meaningful partnerships that drive action-oriented research and social change” (Fischer et al., 2021). So again, it is not just about GIS but about engaging with people, understanding their needs, understanding where they come from, and using GIS as a tool to support the communities we work with throughout our semester.

During this class so far, I have come to appreciate the difference between simply conducting research and engaging in meaningful community-based work. When conducting public research, we need to have an awareness of both the technical and social implications of our research projects. We built this foundation early on in this class, where we had a bunch of readings around the idea of community-based research. From simply learning new words, to strongly enhancing my understanding of what proper community research is supposed to look like through class discussions over texts like (Fischer - Doing Community Geograph). Past GIS labs I have done have primarily focused on individual work; during this class, we have heavily focused on group work and direct engagement in dealing with real-world problems. We have learned that good and thoughtful community service work does not mean coming into a space with our solutions, but rather working with these community members to understand their perspectives, experiences, needs, and goals. This class takes a hands-on approach that sets it apart from my other GIS courses by giving me and my classmates real-world experience in how GIS operates beyond the university, especially in learning to seek out or create data ourselves rather than having it provided.
This semester, I have been lucky to be a part of working around the Brooklyn cemetery.

For this class, we all got into groups and were given a family to create a StoryMap depicting somewhat of what their life might look like. Also connecting all of the records to create a family tree. To find data, we have looked through several different resources like Family Search, census data, Athens city directory, Ancestry, Find a Grave, and many more. This has been very different from any of the work I have done in any college class, but I have enjoyed it. This project is not just about creating maps but about
restoring histories, connecting descendants with their ancestors, and preserving a crucial part of Athens's cultural landscape.

While the community and research focus has been central to this course, GIS remains a vital tool in our work. Applying GIS in real-world research settings, especially creating, cleaning, and validating our data has been both challenging and valuable for developing my skills. In the Brooklyn Cemetery project, we've used GIS to enhance our research, such as mapping the “Young” family to help locate hard-to-find graves hidden by nature. My group is also creating a multi-layer map in ArcGIS Pro showing where members of the Young family lived and worked, adding depth to our story map beyond just dates and names.

This class has shown me how my understanding of GIS and working with data can be used to create meaningful social change. Coming into this class, I was interested in improving my technical GIS skills, as software like ArcGIS or QGIS. While I am still eager to continue getting better at those skills, I am so happy with the work I am doing in this class. I enjoy the idea of doing something that can help a mostly unheard community by spreading awareness of this issue and other issues in Athens regarding the mistreatment of black graves, in the hope of change and recognition of the past. In conclusion, I look forward to continuing to explore the intersections of GIS and the “Community” aspect of this class and aim that our class work will have a meaningful/helpful impact on the family members connected to Brooklyn Cemetery.

Blake Burtzlaff is a third-year undergraduate economics student minoring in geography and also getting his certificate in GIS.
