---
title: "connection and community engagement in research spaces"
date: "2025-04-04"
author: "Amelia Shugart"
---

by Amelia ShugartCemeteries can be a place of peace in otherwise bustling spaces. For many, they are a space to connect to loved ones. Others, places for historical exploration and curiosity. Tucked between Clarke Middle School and Holy Cross Lutheran Church, Brooklyn Cemetery has experienced both historic neglect and grassroots revitalization over the past few decades.

What do you think of when you think of a cemetery? When thinking of a cemetery, you may think of an expansive lawn-scape with tightly organized burial plots. You may think of old trees or wind chimes. Brooklyn Cemetery is hidden in a forested space: shaded by large trees, leaves blanketing pathways and graves, and various plants growing wildly among the burial plots. It is one of the first Black cemeteries in Athens, a final resting place for many residents located in the Brooklyn/Hawthorne neighborhood. In the late 1900s and early 2000s, the cemetery was disturbed by surrounding construction projects and housing development. At the same time, it fell into a state of neglect due to funding shortages and government inattention. This neglect is evident in the cemetery: PVC pipes as grave markers, vine overgrowth, and sunken gravesites. In recent years, community members have worked to restore the cemetery and collect information regarding the families buried there. Leading these efforts is Friends of Brooklyn Cemetery, a community organization spearheaded by Ms. Linda Davis. Their work, alongside UGA students and faculty from various disciplines, has helped catalog geographic and historical data to preserve the cemetery’s legacy.

In our Community GIS class, we are working to collect and map genealogical data on families buried there. We are compiling census, city directory, FamilySearch and Ancestry records in order to build a StoryMaps that highlights the history, geography and connections within a family buried in Brooklyn Cemetery. With this information, we hope to be able to tell parts of their stories. GIS tools are essential for representing these families’ stories, but humanizing the data is just as important. Publicly engaged research is complex, because we often have different personal backgrounds that may influence our perceptions and experience throughout the project. As a student of UGA, an institution responsible for injustice toward the Black community in Athens, understanding positionality and UGA’s history is crucial. When we started the project, I wasn’t aware of Black history or geographies in Athens. I felt more neutral. Throughout the process, I’ve found myself becoming progressively more emotionally connected to the project, and taking on more of an activist perspective. This is a new experience, because my previous research experience has been largely quantitative and fundamentally neutral. Being actively engaged in pragmatic and community-focused research has expanded my prior perceptions of what it means to be a researcher, emphasizing the importance of being an active community member and an advocate.

A few weeks ago, our class had the opportunity to speak with Ms. Linda Davis. As she talked about the history of the cemetery, she explained the importance of the trees in preserving the memory and physical life of people buried there. Hearing her experiences was incredibly influential in connecting to the project on a personal level. Walking in Brooklyn Cemetery exemplifies this: the tall tree canopy, birds flittering between branches, and patchy sunlight through the dense leaf coverage. While sifting through records on FamilySearch, I was able to find the marriage certificate of Elsie and Robert Callaway. I wrote down the marriage date, then realized that they were married on Christmas day in 1892. Finding this record was early into researching the Evans/Callaway family. Thinking about the couple being married on Christmas day stirred up slight emotion. Feeling a more personal connection to a research project was new to me. This seemed like a pivotal moment in the process of researching this family’s history, because I had never felt any sort of emotional connection to data I worked with. I was reminded of the responsibility of human-subjects research and our place as researchers in facilitating the storytelling of the Evans/Callaway family.

A theme throughout our class and human-subject research as a whole is the complexity of “hyphen-spaces” in research projects. “Hypen-spaces” refer to the fluid and active identities of researchers conducting human-subject research. Positionality and context are key components of identity within “hyphen-spaces” of research. The complexity of “hyphen-spaces” as fluid relationships between communities and researchers is evident in our research process. As an outsider with no prior knowledge of Brooklyn Cemetery, I didn’t come into the project with much of a connection. Through the process, I’ve learned that being both a researcher and an active community member can sustain relationships and foster pragmatic solutions.

Amelia Shugart is an undergraduate student in Ecology, pursuing certificates in GIS and Sustainability.Keywords: Hyphen-spaces, Community-engaged research, Collaboration, Research
