---
title: "Doing Research in Brooklyn Cemetery"
date: "2025-04-30"
author: "Liam England"
---

by Liam EnglandParticipating in the Community GIS course has been a rewarding experience. The nexus of the course is about how UGA students can use the technical tools and practices of the GIS field to connect with local history and tell the story of a place and a community – in our case, Brooklyn Cemetery, a historic Black burial ground here in Athens. Due to a lack of financial resources, the cemetery experienced a period of neglect beginning in the 1980s, but it is now being cared for by dedicated community members and the organization Friends of Brooklyn Cemetery. Our class has been contributing to this effort by working to understand and share the stories held within its grounds through the creation of online resources like storymaps.

Like many GIS courses that teach software and data analysis, this class provided me with opportunities to learn those skills. But what has really resonated with me, and for good reason, is the human side of this work. Visiting Brooklyn Cemetery for the first time definitely shifted my perspective and my expectations of what a cemetery can look like. Instead of a neat, orderly space with mowed grass and uniform headstones that I had pictured, it was a sprawling, wooded area with many graves marked only by PVC pipes, or not at all. Seeing the many types of markers representing past lives alongside visible signs of past neglect underscored the profound importance of our project. This contrast prompted me to think about how we, as temporary student researchers, can respectfully and accurately share the stories of people who have been memorialized in this space.

For the past couple of months, two other classmates and I have been researching the Horton family -- one of many families with plots in Brooklyn Cemetery -- to create a storymap about them. This involved trying to piece together details about their lives through census records and city directories. I personally found this research both worthwhile and reminiscent of my own genealogical explorations, and my group and I were able to learn more about the family in the process. One particularly interesting thing we found out was that descendants and relatives of the Horton family buried in Brooklyn Cemetery have resided in the same house in Athens since the 1940s, revealing a tangible link between the past and present beyond the cemetery grounds. However, outside the dry biographical details conveyed in public records, we don’t really know much who the Horton family was and what their lives were like. My group and I are hoping to have a conversation with the family members who still live in Athens and are trying to get in touch with them. Not only is this an important step in learning much more about the family, it is essential in undertaking this work to acknowledge that we are attempting to tell the story of a family that isn’t ours, and that our information is incomplete and perhaps inaccurate.

Creating the storymap had its technical challenges. Sometimes the limitations of the platform made it tricky to present the Horton family's story in the manner that we envisioned. Issues like these are an important lesson that while technology is powerful, it has its limits, and we need to be prepared to work around these limitations while ensuring that the integrity of the stories centered in our community-engaged work remains our priority. While modern technology has undeniably streamlined impactful participatory mapping actions like sharing locations and

information, this project highlighted the irreplaceable value of personal connection: each participant's positionality and the significance of the topic or area to them. Even with technological tools, community GIS fundamentally involves mapping people's stories and their connections to place, a task I believe inherently requires human connection, emotion, and empathy.

Visiting Brooklyn Cemetery later in the semester, after weeks of research, and standing in the area where members of the Horton family are buried, was a meaningful moment. These weren't just names on a page or on a tombstone anymore. This experience made it clear that our work in this course can turn data into really personal and meaningful narratives. I hope our work helps others learn more about the history within Brooklyn Cemetery, and I hope to continue being engaged in work that is not only personally interesting, but beneficial to the community after graduating from UGA.

Liam England is a third-year undergraduate at UGA majoring in Computer Science and minoring in Geography with a certificate in Geographic Information Science. He has been a part of CML since Fall 2024.Keywords: positionality, Brooklyn Cemetery, research, Athens
