---
title: "Meanings of cemetery landscapes"
date: "2025-03-15"
author: "Holden McCullough"
---

by Holden McCullough This semester, I have had the privilege of participating in a service-learning course at UGA involving Brooklyn Cemetery in Athens. The service component of this course is important to me as I seek to be a part of community-based projects both personally and professionally. Through my background as a landscape architect, I am particularly interested in the positionality of place, meaning the spectrum of perspectives held by people of different life experiences. I feel drawn to Brooklyn Cemetery and the many meanings that this landscape holds to the individuals who have ties to this symbolic place.
I believe that the landscape is indicative of who we are, who we have been, and who we will become. The landscape of Brooklyn Cemetery is an intricate museum of past injustices, present day dedication and perseverance, and hope for the future. However, these sensations are simply from my personal perspective. Being in the cemetery for the first time reminded me that people experience different emotions and draw contrasting meanings from the same landscape, especially one as complex as an African-American burial ground in the American south.

My first observation of being in the cemetery was how secluded it was. I enjoyed its private and relatively quiet atmosphere – away from any major sources of noise or disruption. It seemed to be a conducive environment for contemplation and emotional wandering. However, I did notice violations of the cemetery’s agency as a contemplative space. The most glaring of these was the house near the entrance, seemingly recently constructed, which imposed its presence into the ground physically, as well as over the greater sensation of privacy in the space. The school at the rear of the cemetery seemed to turn its back on the cemetery, as if to suggest that the cemetery was an inappropriate space to enter or acknowledge. The sight of the recently completed fence affirmed this sensation. I also noticed the various objects that were used to mark graves. Iron rods from machinery, PVC pipes, and decaying headstones marked graves all the same.

However, the great equalizer across the gravesites was the presence of a strong canopy of trees. To me this was the most marked departure from what would be considered a typical cemetery. I found a great depth of meaning in the trees, given that they had intricately intertwined their root systems with each other and the remains of those buried beneath the ground. To me it is symbolic that these people whose lives once were intertwined on this earth are still presently communing amongst each other through the trees. I found it to be a beautiful manifestation of the promise of life after death and that protecting the tree canopy was necessary to retain this meaning.

However, mine is not the only valid perspective. A conversational debrief after the visit revealed that several of my peers had different experiences. Some felt that the secluded nature of the cemetery was an effort to intentionally hide it from view, thus further erasing the legacy of African Americans in the Athen’s landscape. Others felt that the trees were a symbol of the lack of general management of the cemetery, and this further reflected the prolonged injustices experienced by black members of the community. Honestly, I did not disagree with these perspectives. My peers’ experiences were not my own, but this does not make them incorrect in the slightest. Positionality was taking shape within our small group of observers. Furthermore, none of us have a personal connection to this cemetery or anyone buried within it. Who are we to impose our outsider perspectives on a space that has a depth of meaning to the community who is personally connected to the cemetery? This leads me to my broader question: how do we respect the positionality of the Brooklyn Cemetery community in our work this semester?
​
This question is of paramount importance to me as we are simply an outsider group of individuals participating in this project for a short period of time in its much longer history and future. I have been dedicating a lot of thought to what position we should take when conducting our research as we document the story of this landscape and its people. This project has led me to adopt a new way of thinking about the landscape, especially the landscapes that I get to touch as a designer. My lived experiences are simply a narrow window into a much broader matrix of perspectives and perceptions. Trying to see outside of my personal understanding and into others has presented a new and important challenge as someone who has the qualification to draw implied meanings from the landscape and alter its physical characteristics accordingly. I foresee that this change in my positionality will have resounding impacts on my service oriented ambitions in this class and in the future.
