---
title: "Revealing the Hidden: Our Work at Brooklyn Cemetery, Athens, GA"
date: "2025-04-04"
author: "Scott Messick"
---

by Scott Messick

Brooklyn Cemetery is a hauntingly serene space, nestled behind Holy Cross Lutheran Church in Athens, GA. Upon my first visit at the site, I caught myself admiring the space from the perspective of a naturalist. Being surrounded by trees with light shining through their branches and a vast forest floor covered in tall, swaying grass, I felt admiration for the space. Then, as we continued further, we were warned to watch our feet. There were graves all around us. I looked around and spotted that there were, in fact, graves almost everywhere I could see. The thing is, they weren’t like the graves at Oconee Hill Cemetery - only a 15-minute drive away - rather, some had headstones which were broken, makeshift with PVC pipes, or downright missing. Despite the beauty of the cemetery at face value, many in our class said that they felt somewhat negatively about the overgrown forest enveloping the space - stating that the cemetery felt hidden from the rest of the world. I try to keep in mind that I am accustomed to a certain type of manicured cemetery, and so I will likely, whether I want to or not, compare those cemeteries with Brooklyn cemetery. The space in itself is a beautiful and historically important site, with dedicated volunteers who make every effort to maintain it. Keeping these things in mind, however, it is clear that disinvestment has played a role in the history of the cemetery. Thus, we hope to work with community members who have a stake in its legacy in order to tell the story of its inhabitants.

Katherine McKittrick wrote in her essay “Plantation Futures” about the spatial othering of Black communities as their localities are designated “uninhabitable” and themselves “inhuman” - a practice dating back to early colonialism. Brooklyn Cemetery, a historically Black cemetery, is a space where evidence of systemic disinvestment is visually obvious: ill-defined graves are scattered throughout the grounds (many of whom will never be identified) and paths are covered in forest debris - one by a fallen tree. The cemetery is tucked out of direct sight from the nearby road and further hidden by its overgrown forested canopy. Only a couple people in our class knew of its existence before beginning our project. I personally didn’t. Thus, our project in Community GIS (Geographic Information Science) this semester is to publicize and elaborate on the history which forms the context of the space. In doing this, we hope to recontextualize the space and emphasize its historical significance for the surrounding community. 

As mentioned, our Community GIS course is currently involved in telling the personal stories of the cemetery through spatial narrative - a task entailing archival record scouring, database structuring, image capturing, storymap creation, and engagement with local community members who have ties to the cemetery and/or its inhabitants. Gathering archival data and structuring a coherent database around it as a class is a tedious process, but I’ve found it extremely rewarding. Having uncovered parts of the lives of the Bailey/Green family (our class was split into groups, each assigned a specific family to research), I can only hope that our group’s research fosters a sense of connection between Athens residents and the cemetery, particularly if any descendants of the family still live here. During this process, I’ve come to reflect on the role of cemeteries in community and familial relationships. I, personally, don’t know where my relatives are buried, so I’ve never felt a connection to any particular cemetery. I enjoy walking around in cemeteries, often enjoying my natural surroundings, but have rarely allowed my thoughts to delve into the human side of cemeteries - as counterintuitive as that may sound to some. With this project, it is my hope that our project can supplement and enhance the gentle care voluntarily given to the cemetery with our spatial storytelling.

Part of the way through the process of data collection, we were introduced to Ms. Linda Elder Davis, who described her early life in Athens. She recalled a sense of community at some times, but a looming sense of judgement at others - one which stopped her from walking down certain streets and necessitated the creation of “safe routes” from place to place. This spatial exclusion stuck out to me from her discussion and represented a marginalizing force which shaped her existence as a Black woman in Athens at that time. The spatiality of communities is a central topic of this course which has interested me throughout our discussions, so I’m excited to reinforce Brooklyn Cemetery’s historical importance and the spatial contexts associated with its inhabitants. Telling these stories in a way which empowers the community via the incorporation of their inputs and personal stories will be of utmost importance if we want to ensure a truly collaborative effort.

As we continue developing our projects, I hope to spend more time in the cemetery and consider the personal connections that individuals in Athens may have with the space. It is easy to admire a space at face value, but to understand its context and the impact that it has can humanize it - anchoring it with a community of people and their descendants and helping to give them the spatial and visual presence that they deserve. 

Scott Messick is a 3rd year Ecology major pursuing a minor in Entomology and certificates in GIS and Water Resources

Keywords: Black Communities, Brooklyn Cemetery, Disinvestment, Spatial Narratives, Visibility
