---
title: "A Critical Evaluation of Our Brooklyn Cemetery Project"
date: "2025-04-30"
author: "Vijay Murthy"
---

by Vijay MurthyI have felt dissatisfied with this project for much of the class, and I have had time to think about why. Here, I evaluate our praxis so far based on the criteria set forth in the paper “Cartographies of Black Presence” by Rachelle Berry, Amber Orozco, Maya Henderson, Aidan Hysjulien, Maya Rao, and Jerry Shannon of the Community Mapping Lab. I believe these criteria reflect a set of values rooted in liberatory community geography, and we should make sure to follow them.
​
The first criterion is centering “Black livingness rather than absence” (Berry et al. 20xx, 3). On this point, I believe our project is on the right track. By highlighting the lives of the people under the gravestones (or lack of them), we make clear that Brooklyn Cemetery is not merely a neglected graveyard, it is the final resting place of real people with descendants who are still alive. However, one obstacle we have run into is that our portrayals of these individuals are mostly limited to scraps of demographic data: employment, dates of birth, places of residence, number of children. Centering Black subjectivities necessitates looking for personal narratives, and so far we have been unsuccessful in contacting descendants and learning their family stories.

The second criterion is “[m]aking visible the institutions, structures, and processes that disrupt
Black life” (Berry et al. 20xx, 4). I feel that our project completely fails here, at least for now. The bulk of our time has been spent on researching demographic data of people in certain families. A trained eye will notice traces of systemic oppression in this data, from the most common professions to the neighborhoods all the residences seem to be in. But the way we present this data does not highlight that this is a symptom of oppression, let alone the causes of this oppression. In not doing so, it risks naturalizing said oppression. Some ideas I have for improving this are presenting redlining and segregation maps alongside residence maps, providing context for the professions and wages of family members, and incorporating stories of facing and resisting racism that descendants can share with us. But here again we run into the problem of not having contact with descendants to tell us these stories.

The third criterion is “[e]xpanding capacity through reciprocal, trust-based relationships” (Berry et al. 20xx, 4). I feel that we have much work to do here as well. While this project originated with the suggestion of Mrs. Linda Davis, a longtime partner of the Community Geography Lab, and has kept her in the loop, it has had very limited success in bringing in more community members. When we held an open interest meeting, which Mrs. Davis promoted through her networks, only two other community members showed up. It’s good that they showed interest in our work, but we need more community buy-in. The problem goes beyond one community meeting; Mrs. Davis has not been able to get my group in touch with any Wingfield family members who can provide their input, and other groups have run into the same issue. We must seriously ask ourselves why that is. Is this project even desired by the family members and community? Are we contributing anything they find important or useful? 

The fourth criterion is “[c]reating research products that support Black futurity” (Berry et al. 20xx, 5). In other words, does our project address local social goals of the Black community? One could argue that it does, as it highlights the importance of funding renovation of the cemetery and provides people with more information about the people buried in the cemetery. But whose social goals are these? Do Mrs. Davis’ priorities reflect the priorities of Black Athenians, especially young Black Athenians, those who will be responsible for building the future? While we do not know yet, I have seen little evidence to suggest this might be the case. Even the scheduled time of the first community meeting, Wednesday at 2 PM, does not reflect an orientation towards Black Athenians of all ages. It’s no wonder that both community members who showed up to the meeting were retirees, those are the only people available then! If we want to support Black futurity, we should select projects which speak to those who will ultimately build it.

The fifth criterion is “[d]eveloping cartographic practices that represent the embodied
experiences of Black communities” (Berry et al. 20xx, 5). The paper recommends directly incorporating the “voices, faces, and stories of Athens’ Black residence” into our final product, rather than reducing people to mere data points (Berry et al. 20xx, 5). This is something we have not been able to do, not due to malpractice, but because we lack the voices, faces, and stories to incorporate. If we cannot find enough community members to give us feedback on our project, we should perhaps consider that they do not find our work important.

The underlying problem here is a lack of community engagement. This is a sharp contrast to the projects previously undertaken by the Community Mapping Lab. The Linnentown project provided an estimation of how much money displaced homeowners are owed by UGA, actively forwarding the reparations struggle. As an organizer, I made use of the Community Mapping Lab’s eviction project to choose which apartment complexes to focus on distributing eviction defense manuals in. By contrast, it does not appear that we have been able to contribute anything except a pretty data sheet to people who never asked for it. I could be missing the bigger picture here, but I do not think that this project so far has lived up to the values of the Community Mapping Lab, and I hope future classes learn from our mistakes.
