---
title: "Learning to Pivot"
date: "2025-05-27"
author: "Jamie Jordan"
---

By Jamie Jordan

My introduction to the Reese Street Mapping project was through an email I received from Dr. Shannon in April 2024 in which he sought undergraduate researchers to work on an ongoing effort to visualize and assist in the development of a narrative of Athens’ historic Black Reese Street neighborhood. I had just accepted an internship to work over the summer for the Carl Vinson Institute of Government’s Workforce and Economic Development division, located in the Lucy Cobb Building at the intersection of Reese Street and Milledge Avenue. While I was initially keen to get involved with any ongoing CURO project with the Community Mapping Lab (CML), this connection made me more excited about the prospect of learning more about this community in particular. Additionally. I had a friend who lived off Chase Street who told me about a nearby fraternity house, whose presence contributed to a tumultuous dynamic between generational locals and students. Cursory research revealed a fascinating, frustrating history of the frat’s role in creating a sort of student-driven gentrification in the community. This further piqued my interest in the Reese Street Mapping project. Although I failed to receive a CURO grant after applying over the summer of 2024, I managed to secure one upon reapplying in December.
 
In January 2025, I was thrilled to learn that I would be working alongside another undergraduate student, Jessica, on the Reese Street project, which enabled us to hone our mixed methods approach by divvying the work such that I focused primarily on the quantitative parts while Jessica explored the neighborhood more qualitatively. Our earliest tasks involved priming ourselves with a better understanding of the neighborhood, which we achieved through analysis of Amy Andrews’ thesis, “Reese Street’s Last Stand: An African American Local Historic District’s Fight to Retain Community and Identity.” Her thorough research laid the groundwork for our subsequent investigations, providing detailed insights into the history of change in the dynamic neighborhood. It also served to further contextualize the importance of our effort to showcase the evolution of the area and inspired us to think more critically about what our deliverable should look like.
 
In an early meeting with our partners at Historic Athens, including Hope Iglehart (a lifelong, generational Reese Street resident) and Denise Sunta, we discussed various possibilities of the most appropriate format for showcasing the narrative of change in the community. We explored several differently structured StoryMaps and collectively favored the idea of presenting multiple distinct time periods such that we could more clearly contrast a given era against another– this framework was loosely based on an exhibit in New York City’s Tenement Museum, which immerses guests into various temporal landscapes.

Due to the accessibility of census data, combined with the CML’s previous and ongoing research using the 1958 directory, we decided to begin by exploring the 1926-1927 and 1958 Athens city directories.
Jessica and I cleaned spreadsheets of census data using Google Sheets, which involved both basic quality control and identifying which Black residents lived within the geographic scope of the Reese Street neighborhood in a given time period– we then visualized where residents lived in 1958 in QGIS. This was especially tedious– involving some manual cross-referencing with data from Athens-Clarke County Open Data, which has contemporary shapefile boundaries of local historic districts– as well as Amy Andrews’ thesis, which details the expansion of the community’s geography over time. Despite these highly convenient sources, I learned through this process that outlining the boundary of a neighborhood is often a difficult and intensive challenge since communities are so geographically nebulous.

Later, I scrubbed data for the 1926-’27 city directory in preparation for its geocoding, such that we could visualize the residential occupancy of the Reese Street neighborhood for this time period. Upon geocoding in ArcGIS Pro, we produced a map that outlined where Reese Street residents lived in the mid-’20s and what their professions were, with a significant amount of confidence in its accuracy. By geocoding the census data from both this directory and the ‘58 directory, we were able to generate a “Web Experience” on ArcGIS Online (see Figure 1) which allows for convenient toggling between the two eras, enabling audiences to more easily visualize the expansion of the neighborhood over time.

Perhaps my foremost takeaway from this project has been an appreciation for the importance of pivoting and adjusting expectations when constrained by time. In our first meeting with Historic Athens, we set ambitious goals for the deliverable, discussing the possibilities of oral history efforts and more greatly implementing descendants of Reese Street residents into the StoryMap, but had to iteratively take a step back and reassess to determine what we could feasibly produce by the end of the semester that would be of good quality. One skill I honed through working on this project was data prepping for geocoding– I have learned through some of the relatively tedious scrubbing work I did mid-semester that even seemingly basic QCing requires significant patience and attention to detail. It was a privilege to work on the Reese Street Mapping Project this semester and I look forward to seeing how future CURO researchers with the CML further innovatively flesh out this important story using the structure Jessica and I developed.
