---
title: "The Brooklyn Cemetery: A symbol of systemic racism"
date: "2025-04-30"
---

by Rajath Prabhakar

Brooklyn Cemetery
Established in 1882, the Brooklyn Cemetery is the final resting place for residents of the Hawthorne area of West Athens. It was one of the first Black cemeteries established in Athens. Since then, it has been the victim of nature, time, and disrepair. In more recent times, there have been efforts to restore the cemetery, removing truckloads of debris over time. Our project sought to go one step further and bring the stories of the families buried in this cemetery to life. We sought to put the words of McKittrick into action, when she conceptualizes “plantation futures: a conceptualization of time-space that tracks the plantation toward the prison and the impoverished and destroyed city Sectors” (McKittrick 2). Our project also sought to serve as a guide for urban planners and for broader political action. As Andrea Roberts put it, “awareness of where a colony exists, or in some cases, once was located, opens the door to access. Gaining invited entry into a colony’s social system, to speak with those who call these places “home,” or to observe shared traditions is key to understanding these places and their history”(Roberts 15).

Many of these graves, 40 to be precise, are of Black WW1, WW2, and Korean War veterans. Recently, we met with the two community members that showed up. The point of this meeting was to discuss our progress with the project of preserving the genealogical histories of the families buried within Brooklyn Cemetery. This progress check was met with relative enthusiasm; if nothing else, it was nice to see that people liked the work that we did very much and brought them joy. But it sort of ended there; there are still insufficiently answered questions.

For example:
a. Why would people that aren't immediate descendants of these families care about these people?
b. What does this add that we don't already know? Specifically the broader history of the Black experience in America, even in Athens, Georgia specifically.

The disrepair of the cemetery is a continuation of the war on Black America
But the disrepair seen at Brooklyn Cemetery is just one more point in a long history of oppression and white supremacy seen in the United States, and in Athens alone. Whether in life or in death, Black people are treated as second-class citizens in Athens as well as in the US more broadly. Whether it is Brooklyn Cemetery, Baldwin Hall, or the Athens Housing Crisis most recently, the undercurrent of white supremacy is clearly seen.

Baldwin Hall
On November 17, 2015, the renovation of Baldwin Hall resulted in human remains being dug up. They would later be found to be the remains of former slaves. As is a theme with any issue involving the University of Georgia, the administration obstructed the process of justice at every turn,from not consulting the black community of Athens on the reinterment of those remains, prohibiting Athens community members from viewing said reinterment, and an unwillingness to address the legacy of slavery present.

An Underclass at UGA
A leading employer in Georgia and the dominant force in the Athens economy, Athens has a poverty rate of 38%(!), a strong indicator of its continuing legacy of exploitation. As of this writing, despite making up nearly 28% of residents, only 7.7% of students and 5% of faculty are Black. Breaking this down further, by occupation, only 7% of administrators, and as mentioned before, 5% of faculty are Black. However, Black people make up 44% of service employees, the lowest paid workers at UGA.

In addition to UGA’s poor treatment of its majority-Black service workers, the university has also taken steps to abandon its pretense of caring for its Black students. Take, for example, its replacement of the very specific C.L.A.S.S (Continuing the Legacy of African-American Student Success) Advocates with a nebulous “Resident Belonging Ambassador” this past year. The program was essential to making Black students feel welcome at UGA, and find community in the predominantly white institution (PWI). Its replacement cuts the direct support Black students received from the Class Advocate program, a logical endpoint to increasing roadblocks to the program, from not being provided the names of Black students, to being treated as RAs rather than as a position specific to Black students. 

Conclusion
The Brooklyn Cemetery stands as a stark symbol of systemic neglect. Its deterioration mirrors the broader injustices faced by the Black community in Athens - from the desecration of the graves of slaves underneath Baldwin Hall to the economic and educational disparities perpetuated by the University of Georgia.

Rajath Prabhakar is a 4th year Statistics major at UGA

Keywords: Brooklyn Cemetery, systemic racism, slavery

Works Cited
Enlighten Media Productions. “[CC] below Baldwin: How an Expansion Project Unearthed a University’s Legacy of Slavery.” YouTube, 9 Oct. 2020, www.youtube.com/watch?v=mwQcTfGqANQ. Accessed 27 Sept. 2024.

McKittrick, Katherine. "Plantation Futures." Small Axe, vol. 17 no. 3, 2013, p. 1-15. Project MUSE, https://muse.jhu.edu/article/532740.
Roberts, Andrea. (2017). Documenting and Preserving Texas Freedom Colonies. Texas Heritage Magazine. 2. 14.

Sawyer, Dawn. ““A Long Time Coming”: C.L.A.S.S. Advocate Program’s Removal Worries Black Students.” The Red & Black, 4 Apr. 2024, www.redandblack.com/uganews/a-long-time-coming-c-l-a-s-s-advocate-program-s-removal-worries-black/article_ef4dd9b4-f247-11ee-b044-b3e421b2c428.html.
