---
title: "brooklyn cemetery thoughts and reflections"
date: "2025-04-04"
author: "Luke Pearlman"
---

by Luke PearlmanThis semester, I have had the privilege of taking Community GIS, a service learning class at UGA. In such a class, rather than simply being taught concepts and information, students learn through working on real world projects involving engagement and interaction with the local community. In this class, we are working as part of a larger effort to rehabilitate Brooklyn Cemetery, a historic Black cemetery in Athens, and to help make the stories of families buried there more visible and accessible. Through this opportunity, I have not only honed my technical GIS skills and gained experience working as part of a team on a real world project, but broadened my perspective and worldview.

One of the earliest discussions we had in class surrounded the question of what exactly community geography is. As a preview to the discussion, we read the scientific paper “Doing Community Geography” [Fischer et al.], which stated that community geography is a framework and philosophy that “offers researchers, community groups, and students opportunities to engage in action oriented applied geographical research.” To me, that means engaging in projects and research in tandem with the communities of interest in order to address problems and or create solutions within them.

Fitting with this theme, one aspect of my experience in the class that I have enjoyed is putting technical skills I have learned throughout my college career to use in the community. As the name suggests, Community GIS is on some level a GIS related class. GIS, or Geographic Information Systems, is a type of software that allows the user to process and analyze geospatial data, and to create maps. While my previous experience in such classes was heavily based on gaining experience with learning to perform technical operations within the software, here, that has taken a backseat to the more organic, human side of geography.

Another discussion early on in the semester was related to the dichotomy of the cold, black and white nature of GIS software, and the inherently “gray” and complex nature of human issues and stories. In the software, collected data is clear cut and completely unambiguous, but through suites of maps, as well as written and visual aids, we are working to tell as full of stories as possible about these families. As part of this conversation, we discussed the frameworks of positivism and pragmatism. Positivism is a school of thought that arose during the enlightenment, and posits that all human knowledge is absolute, and that everything in the universe, including interactions between members of human societies, can be deduced through logic or mathematical proofs. This procedural view of the universe obviously has its limitations, especially when it comes to humanity, but is essentially how computer programs and code work– including GIS. Conversely, while pragmatism is still analytical and problem solving based, it views reality as somewhat indeterminate and observers never truly unbiased.

While working on the Brooklyn Cemetery project, I became very aware of the fact that I can never truly be a fully unbiased observer. Not only is there a lot that I haven’t experienced, but due to differences in brain chemistry and past experiences, I will not necessarily perceive the same events and ideas in the same way as others. One such situation arose during a discussion at the end of our class’s first tour of the cemetery. An unusual aspect of Brooklyn is that rather than a well manicured lawn like most cemeteries, its grounds are covered by a forest. Some of the class, myself included, thought that this contributed to a natural serene atmosphere, and noted the symbolism of continued life in the area sustained by those buried there. However, others saw them as actively hiding the cemetery, and yet another example of the history of neglect and mistreatment of the Athens Black community. While that is not the way I first perceived the tree cover, I fully understand how others could first interpret it that way– and trees aside, it is a fact that the cemetery has been neglected and is in relative disrepair, although there are ongoing efforts from the community to rehabilitate it. This debate strongly highlighted to me the idea that nobody can be a truly disconnected and unbiased observer, and while I think both opinions are valid, the thoughts of those who are a part of the historic community surrounding the cemetery should carry the most weight in this instance. It is their family and friends who are buried there, and they have past experience as being a part of the Athens Black community shaping their perception and decision making– something that I very much lack.

As a whole, I am very grateful to be a part of this spring’s Community GIS class and for everything I have learned. Not only have I been able to sharpen and expand my technical GIS skillset and gain experience working as a member of a team toward completion of a real world project, but I have also broadened my perspective and altered my way of thinking about the world. At the conclusion of the semester, I will take far more than just a letter grade away from this class– and more than technical and soft skills as well.

Luke is an undergraduate student at UGA pursuing a degree in Geography and certificate in Geographic Information SystemsKeywords: Brooklyn Cemetery, GIS, Community, Athens​
