---
title: "Community Mapping Brooklyn Cemetery"
date: "2025-04-04"
author: "Blake Neumann"
---

by Blake NeumannThis semester, the community GIS class is continuing ongoing work in Brooklyn Cemetery in partnership and under the direction of some of the community leaders and stewards of the Brooklyn community. This includes attempting to add depth to the public record of a number of families buried at Brooklyn Cemetery, many of whom still have representatives living around Athens today. We hope to accomplish this by consulting a variety of genealogical records to piece together stories of the individuals buried in Brooklyn Cemetery, then confirming these details with descendants of the individuals and ensuring we have gathered information that feels like it will allow for the creation of what they feel constitute meaningful stories.

​Personally, I am returning to grad school from having worked in the field of community conservation for the last few years. I spent time working directly with rural communities in the Adirondacks to help them develop a plan for mobilizing resources they had access to, while planning for ways to acquire more support from the state to assist in stewardship of the lakes that supported their local economies. A question I often pondered in that work, and still do in my own work, is: how are land use (as well as other environmental) decisions made in ways that appear democratic or benign, but are designed to serve particular groups at the detriment of others? For instance, a student asked Linda Davis (a devoted advocate of the Brooklyn Cemetery and community) about a home built near the Brooklyn Cemetery footprint (above). Mrs. Davis reflected that during the period that the University of Georgia owned the site, they had sold a plot (at that time, part of the cemetery) to fund maintenance efforts. The owners of the home built out the plot despite concerns about the potential location of infant graves somewhere in that section of the cemetery. What is the likelihood any of this would have happened if this was a white cemetery? 
​Thus far this year, we have been thinking about what it means to tell stories about the cemetery that connect to a political agenda – such as stories recognizing the continued existence of black communities in Athens, rebuking ongoing efforts of black erasure. We can look to the tattered land use history of Brooklyn Cemetery as glaring evidence of this attempted erasure: the carving off of a parcel here, a parcel there; the disruption of gravesites for construction. However, the stories we have been encouraged to tell are not about these infuriating transgressions; the stories to tell are ones of joy, of celebration, of a proud and devoted black Brooklyn community that continues to pour love and care into a space that connects past to present in a tangible way, reflecting those commitments back into the world, and inspiring other black communities to steward these important spaces as acts of resistance.
 
Telling the stories of the past, of the black families in Brooklyn Cemetery that have existed in Athens for well over a century and tying those stories to the descendants that continue to remain here today is an acknowledgment of the deep and meaningful connection to place exemplified by these families. It is, in itself, an acknowledgment of an act of ongoing resistance to the forms of racism, exclusion, and exploitation faced by these families through time. But more than that, it is also a celebration of these families’ continuing commitment to place and an opportunity to reflect on what this special form of relationship to place means. What does a multi-generational connection to place entail, and what opportunities does it present? As Katherine McKittrick would implore us to think, what kinds of black futurities can we imagine through these deep connections? And how do we get to those imagined futures from here?

​Continually, we have been encouraged to think in class: is the knowledge we are creating useful? We are still in the early days of this project, but continuing to turn this consideration over as we move through an iterative process of collection, dialogue, and reformulation with the community can only ensure that the knowledge being produced through this collective work provides some useful contribution to the important vision of the Brooklyn community. While it is beyond the scope of our engagement, it is also compelling to think: how does this knowledge generate new pathways for more sustainable black futurity in Athens? How can this knowledge ensure more affordable and abundant housing, higher wages, higher enrollment of black students from Athens-Clarke county at UGA, and other forms of reparation that are long overdue to the descendants of the folks that built this city and university? Hopefully our work this semester will ply the leaders of the Brooklyn community with resources to these ends.
