---
title: "Visibility and neglect at brooklyn cemetery"
date: "2025-03-15"
author: "Logan Wiley"
---

by Logan Wiley 

I love cemeteries – they make me feel grounded, connected to some deep historical truth. For the greater part of my second year as an undergraduate, I ran every morning through Oconee Hill Cemetery near my residence hall. I remember spiraling up the path around the tallest point and reading the names on the obelisks sticking out from the summit: Lumpkin, Hull, and others found elsewhere on building facades and street signs around the University of Georgia (UGA) campus and surrounding city of Athens. Even in death, elevation represents recognition; at the historically Black Brooklyn Cemetery a few miles away from Oconee Hill, neglected gravesites sink into the earth.
​ 
The racial inequalities between the burial grounds of Athens define this year’s Community Geographic Information Systems (CGIS) course at UGA, which focuses on the families buried in Brooklyn Cemetery. Joining my classmates and instructors to familiarize ourselves with the space, I arrived at the cemetery on a cool sunny afternoon. Ten minutes early, I walked from end-to-end and back – the grounds are relatively small and have shrunk over time. Even now, you feel a sense of encroachment from a residence, a church, and the newly-built Clarke Middle School on the north end of the eleven-acre plot. According to Ms. Linda Davis, the co-founder of the Friends of Brooklyn Cemetery, numerous people are likely buried under the buildings that dot the perimeter. A small “Black Lives Matter” banner on the side of the house facing the paths indicates to me that the residents are aware of their position next to (or maybe on top of) a Black cemetery. I passed a church member talking on the phone and another early classmate before reaching the fence separating the cemetery from the school. Thanks to the new construction, you can see clear across the massive parking lot to one of the more-frequented areas of Athens: a shopping mall with a Kroger, some clothing stores, and a fitness center. It feels like the cemetery is surrounded by a force slowly exposing what Ms. Linda calls “sacred ground”. What happens when a burial site moves from being ignored and neglected to being acknowledged and still neglected?
As Katherine McKittrick highlights in her piece Plantation Futures, encroachment, disinvestment, and neglect of Black spaces become normalized, commonsense, and inevitable. For decades, Brooklyn Cemetery was left behind, with its stories allowed to fade into the past. Eventually, developers regarded the space as lifeless despite it holding so many lives – In 2006, Ms. Linda joined a teacher at the adjacent school to defend the cemetery from replacement by a playground. Lacking stable funding, the cemetery relies on volunteers like Ms. Linda to prevent the normalization of the cemetery’s relative disrepair and push back against those waiting to build over the forested gravesites.
​
Despite the sunken earth, broken headstones, and PVC-pipe markers of the unnamed interred individuals, Brooklyn Cemetery is beautiful. On that January morning, our procession passed under tall, strong pine trees in silence, unbroken except for the crunching of leaves underfoot and laughter from middle-school sports, a reminder of the many generations present around us. Youth ministries, local volunteers, and student organizations from the surrounding high schools and universities visit the cemetery frequently, contributing to its upkeep under the guidance of Ms. Linda. Wooden signage to mark sections, clear maps in sturdy display cases, and stunning metalwork on the front gate all enhance the environment. Far from the narrative of lifelessness imposed upon the cemetery to smooth processes of development and piecemeal land seizure, walking through the grounds connected me to the broader streams of Athens’ history and the communal efforts to preserve, rebuild, and expand the cemetery.
This site visit is one of the first steps in our research process for this year’s CGIS class. As the semester continues, we will tell stories on those interred in the cemetery, focusing on Black Athenian families and their paths through the city across generations. On our walking tour, we passed many of these family plots, full of rich threads that we will later follow in the computer lab through census records, death certificates, and obituaries. Our maps, stories, and data will follow the broader process of opening Brooklyn Cemetery to the surrounding space; I am still learning how to ensure that our work celebrates and properly acknowledges family histories. Given the establishment of the cemetery in 1882, some people buried there have almost definitely become invisible; perhaps under the fingers of development at the cemetery edges, or unmarked by headstone, PVC pipe, or sunken earth. For those documented, we are responsible for carefully and respectfully telling their stories - to the classroom and then to the broader community. In this course, we will join the long line of others before us in caring for the cemetery, doing our best to make sure it doesn’t sink away from the story of Athens.

Logan Wiley is an undergraduate at UGA majoring in Geography and Psychology. He has been working in the Community Mapping Lab for the last three years.

Keywords: Positionality, Black cemeteries, Black Athens, disinvestment, development
