---
title: "birding in brooklyn"
date: "2025-04-30"
author: "Beckham"
---

by Beckham ClimeBirdwatching has trained my brain to seek overgrowth and disrepair in urban settings. Ephemeral brush piles, standing and fallen dead wood, piles of leaf litter, brambles, all provide crucial natural habitat to wildlife residents in urban areas – so often, there is a great deal of diversity to be found in the neglect. I noticed this in Brooklyn cemetery – I saw the burning blue flash of bright male bluebirds more than a couple times during my first visit. On my second visit, to confirm burial locations of our respective assigned family members, I brought my binoculars and paid a bit more attention. A host of charismatic bird species were present on this tiny, quiet wooded plot that Brooklyn cemetery rested in – woodpeckers and brown-headed nuthatches abounded in dense numbers! Even a Cooper’s hawk, a less common species than other urban hawks, alighted on a bent sapling directly above one of our family member’s headstones. Even in a place centered around the deceased, I saw the wildlife as a pleasant representation of continued life in wake of loss, propped up by the encroaching wild growth stemming from neglect. But I wasn’t here just to bird.

Over the course of the spring semester, I’ve taken part in Community GIS, a University of Georgia course dedicated to a unique research-learning environment where community members have an equivalent stake to academics in the process and outcome of a research project at UGA. This spring, we’ve been working with members of the Black community in Athens with ties to Brooklyn Cemetery, a historic black cemetery in Athens which has persisted through community ties despite heavy divestment, with no assistance provided by the city to maintain the grounds. The cemetery has been in use since the mid-1800s and hold the ancestral roots of living Black Athens residents. Many buried individuals are unmarked, unidentified, or have gravestones which have eroded and become unrecognizable over time.

After our first tour of the site as a class, we discussed the densely wooded nature of the cemetery, and it was very noticeable how different everyone felt. Some garnered a sense of peace and privacy emanating from the tall loblolly pines. Others correctly identified a material burden - leaves obscure footpaths, branches fall on graves, uprooted storm-felled trees laying across gravesites for weeks. The diversity of reaction reminded me how radically views on the purpose and function of a space can differ, even within our class group. To me, the kneejerk anticipation induced by the disrepair (there could be just about any species gleaning a bug out of that twig pile!) indicated my distant position to those closest to Brooklyn cemetery – when I looked there, I saw the birds first, and the gravesites second. Looking from a different perspective, one notices that the overgrown nature of the cemetery makes the maintenance of the space more difficult with few hands and little funding. 

This internal tension I experienced mirrors some others seen in conservation and environmentalism. Broadly, efforts to create, maintain, and protect natural spaces can come at the cost of resource access, cultural practices, or the autonomy of vulnerable communities. More specifically, seeing beauty in nature’s reclamation of human-altered spaces may be a common impulse for those ecologically-minded —but without nuance it risks overlooking the material reality of extant vulnerable communities. Witnessing the rewilding of Brooklyn Cemetery should be read in light of what is being abandoned and why.

In class, we read Katherine McKittrick’s Plantation Futures which details how the structure of the plantation—hierarchies of race, labor, land control, and extraction—are not relics of the past, but persist in present-day landscapes and institutions. These logics structure the uneven distribution of resources, care, and visibility into the modern day. In the case of Brooklyn Cemetery, it is apparent how this plantation hierarchy persists through systematic divestment, allowing a Black cemetery to fall into disrepair due to this inequitable distribution of resources. 

In addition to the weathering of Brooklyn Cemetery by nature, there also is no existing, navigable and easily accessible public record of individuals buried there currently available. As a class, through communication with our mentor Dr. Gerald Shannon and community leader Linda Davis, we have endeavored over the course of the semester to investigate what it would mean to provide a deliverable product to the community that achieves the best interests of those with intimate ties to Brooklyn Cemetery. In doing so, we have spent most of the semester building an accessible online genealogical history of some of the families interred at Brooklyn Cemetery. In doing so, through the theory we’ve read and the tools we put into practice in doing this community engaged research, I feel more prepared to take on ecological issues that concern human livelihood.

Henry Beckham Climie is a 4th year B.S. student in ecology. He is passionate about human-wildlife interactions, ornithology and birding, and wildlife conservation. In the future he hopes to engage in work directly with wild bird species and with human communities to bring awareness of wildlife issues to the public.

Keywords: Community science, Community GIS, Brooklyn Cemetery, Black cemeteries, Rewilding, Positionality, Ecology, Birding
